// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: chatim/v1/core.proto

package chatimv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RoomType int32

const (
	RoomType_ROOM_TYPE_UNSPECIFIED RoomType = 0
	RoomType_ROOM_TYPE_DM          RoomType = 1
	RoomType_ROOM_TYPE_GROUP       RoomType = 2
)

// Enum value maps for RoomType.
var (
	RoomType_name = map[int32]string{
		0: "ROOM_TYPE_UNSPECIFIED",
		1: "ROOM_TYPE_DM",
		2: "ROOM_TYPE_GROUP",
	}
	RoomType_value = map[string]int32{
		"ROOM_TYPE_UNSPECIFIED": 0,
		"ROOM_TYPE_DM":          1,
		"ROOM_TYPE_GROUP":       2,
	}
)

func (x RoomType) Enum() *RoomType {
	p := new(RoomType)
	*p = x
	return p
}

func (x RoomType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RoomType) Descriptor() protoreflect.EnumDescriptor {
	return file_chatim_v1_core_proto_enumTypes[0].Descriptor()
}

func (RoomType) Type() protoreflect.EnumType {
	return &file_chatim_v1_core_proto_enumTypes[0]
}

func (x RoomType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RoomType.Descriptor instead.
func (RoomType) EnumDescriptor() ([]byte, []int) {
	return file_chatim_v1_core_proto_rawDescGZIP(), []int{0}
}

type MessageKind int32

const (
	MessageKind_MESSAGE_KIND_UNSPECIFIED MessageKind = 0
	MessageKind_MESSAGE_KIND_TEXT        MessageKind = 1
)

// Enum value maps for MessageKind.
var (
	MessageKind_name = map[int32]string{
		0: "MESSAGE_KIND_UNSPECIFIED",
		1: "MESSAGE_KIND_TEXT",
	}
	MessageKind_value = map[string]int32{
		"MESSAGE_KIND_UNSPECIFIED": 0,
		"MESSAGE_KIND_TEXT":        1,
	}
)

func (x MessageKind) Enum() *MessageKind {
	p := new(MessageKind)
	*p = x
	return p
}

func (x MessageKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MessageKind) Descriptor() protoreflect.EnumDescriptor {
	return file_chatim_v1_core_proto_enumTypes[1].Descriptor()
}

func (MessageKind) Type() protoreflect.EnumType {
	return &file_chatim_v1_core_proto_enumTypes[1]
}

func (x MessageKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MessageKind.Descriptor instead.
func (MessageKind) EnumDescriptor() ([]byte, []int) {
	return file_chatim_v1_core_proto_rawDescGZIP(), []int{1}
}

type HistoryAnchor int32

const (
	HistoryAnchor_HISTORY_ANCHOR_UNSPECIFIED HistoryAnchor = 0
	HistoryAnchor_HISTORY_ANCHOR_LATEST      HistoryAnchor = 1
	HistoryAnchor_HISTORY_ANCHOR_OLDEST      HistoryAnchor = 2
	HistoryAnchor_HISTORY_ANCHOR_BEFORE      HistoryAnchor = 3
	HistoryAnchor_HISTORY_ANCHOR_AFTER       HistoryAnchor = 4
)

// Enum value maps for HistoryAnchor.
var (
	HistoryAnchor_name = map[int32]string{
		0: "HISTORY_ANCHOR_UNSPECIFIED",
		1: "HISTORY_ANCHOR_LATEST",
		2: "HISTORY_ANCHOR_OLDEST",
		3: "HISTORY_ANCHOR_BEFORE",
		4: "HISTORY_ANCHOR_AFTER",
	}
	HistoryAnchor_value = map[string]int32{
		"HISTORY_ANCHOR_UNSPECIFIED": 0,
		"HISTORY_ANCHOR_LATEST":      1,
		"HISTORY_ANCHOR_OLDEST":      2,
		"HISTORY_ANCHOR_BEFORE":      3,
		"HISTORY_ANCHOR_AFTER":       4,
	}
)

func (x HistoryAnchor) Enum() *HistoryAnchor {
	p := new(HistoryAnchor)
	*p = x
	return p
}

func (x HistoryAnchor) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (HistoryAnchor) Descriptor() protoreflect.EnumDescriptor {
	return file_chatim_v1_core_proto_enumTypes[2].Descriptor()
}

func (HistoryAnchor) Type() protoreflect.EnumType {
	return &file_chatim_v1_core_proto_enumTypes[2]
}

func (x HistoryAnchor) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use HistoryAnchor.Descriptor instead.
func (HistoryAnchor) EnumDescriptor() ([]byte, []int) {
	return file_chatim_v1_core_proto_rawDescGZIP(), []int{2}
}

type EditKind int32

const (
	EditKind_EDIT_KIND_UNSPECIFIED EditKind = 0
	EditKind_EDIT_KIND_ORIGINAL    EditKind = 1
	EditKind_EDIT_KIND_TEXT        EditKind = 2
	EditKind_EDIT_KIND_DELETE      EditKind = 3
)

// Enum value maps for EditKind.
var (
	EditKind_name = map[int32]string{
		0: "EDIT_KIND_UNSPECIFIED",
		1: "EDIT_KIND_ORIGINAL",
		2: "EDIT_KIND_TEXT",
		3: "EDIT_KIND_DELETE",
	}
	EditKind_value = map[string]int32{
		"EDIT_KIND_UNSPECIFIED": 0,
		"EDIT_KIND_ORIGINAL":    1,
		"EDIT_KIND_TEXT":        2,
		"EDIT_KIND_DELETE":      3,
	}
)

func (x EditKind) Enum() *EditKind {
	p := new(EditKind)
	*p = x
	return p
}

func (x EditKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EditKind) Descriptor() protoreflect.EnumDescriptor {
	return file_chatim_v1_core_proto_enumTypes[3].Descriptor()
}

func (EditKind) Type() protoreflect.EnumType {
	return &file_chatim_v1_core_proto_enumTypes[3]
}

func (x EditKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EditKind.Descriptor instead.
func (EditKind) EnumDescriptor() ([]byte, []int) {
	return file_chatim_v1_core_proto_rawDescGZIP(), []int{3}
}

type Room struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Tenant        string                 `protobuf:"bytes,2,opt,name=tenant,proto3" json:"tenant,omitempty"`
	Type          RoomType               `protobuf:"varint,3,opt,name=type,proto3,enum=chatim.v1.RoomType" json:"type,omitempty"`
	Name          string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	CreatedBy     string                 `protobuf:"bytes,5,opt,name=created_by,json=createdBy,proto3" json:"created_by,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	MemberCount   int32                  `protobuf:"varint,7,opt,name=member_count,json=memberCount,proto3" json:"member_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Room) Reset() {
	*x = Room{}
	mi := &file_chatim_v1_core_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Room) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Room) ProtoMessage() {}

func (x *Room) ProtoReflect() protoreflect.Message {
	mi := &file_chatim_v1_core_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Room.ProtoReflect.Descriptor instead.
func (*Room) Descriptor() ([]byte, []int) {
	return file_chatim_v1_core_proto_rawDescGZIP(), []int{0}
}

func (x *Room) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Room) GetTenant() string {
	if x != nil {
		return x.Tenant
	}
	return ""
}

func (x *Room) GetType() RoomType {
	if x != nil {
		return x.Type
	}
	return RoomType_ROOM_TYPE_UNSPECIFIED
}

func (x *Room) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Room) GetCreatedBy() string {
	if x != nil {
		return x.CreatedBy
	}
	return ""
}

func (x *Room) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Room) GetMemberCount() int32 {
	if x != nil {
		return x.MemberCount
	}
	return 0
}

type Message struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        string                 `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	ThreadRoot    uint64                 `protobuf:"varint,2,opt,name=thread_root,json=threadRoot,proto3" json:"thread_root,omitempty"`
	Seq           uint64                 `protobuf:"varint,3,opt,name=seq,proto3" json:"seq,omitempty"`
	Sender        string                 `protobuf:"bytes,5,opt,name=sender,proto3" json:"sender,omitempty"`
	Kind          MessageKind            `protobuf:"varint,6,opt,name=kind,proto3,enum=chatim.v1.MessageKind" json:"kind,omitempty"`
	Text          string                 `protobuf:"bytes,7,opt,name=text,proto3" json:"text,omitempty"`
	Cid           string                 `protobuf:"bytes,8,opt,name=cid,proto3" json:"cid,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	Ver           uint32                 `protobuf:"varint,10,opt,name=ver,proto3" json:"ver,omitempty"`
	Deleted       bool                   `protobuf:"varint,11,opt,name=deleted,proto3" json:"deleted,omitempty"`
	EditedAt      *timestamppb.Timestamp `protobuf:"bytes,12,opt,name=edited_at,json=editedAt,proto3" json:"edited_at,omitempty"`
	Hidden        bool                   `protobuf:"varint,13,opt,name=hidden,proto3" json:"hidden,omitempty"`
	Reactions     *ReactionSummary       `protobuf:"bytes,14,opt,name=reactions,proto3" json:"reactions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_chatim_v1_core_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_chatim_v1_core_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_chatim_v1_core_proto_rawDescGZIP(), []int{1}
}

func (x *Message) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *Message) GetThreadRoot() uint64 {
	if x != nil {
		return x.ThreadRoot
	}
	return 0
}

func (x *Message) GetSeq() uint64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *Message) GetSender() string {
	if x != nil {
		return x.Sender
	}
	return ""
}

func (x *Message) GetKind() MessageKind {
	if x != nil {
		return x.Kind
	}
	return MessageKind_MESSAGE_KIND_UNSPECIFIED
}

func (x *Message) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *Message) GetCid() string {
	if x != nil {
		return x.Cid
	}
	return ""
}

func (x *Message) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Message) GetVer() uint32 {
	if x != nil {
		return x.Ver
	}
	return 0
}

func (x *Message) GetDeleted() bool {
	if x != nil {
		return x.Deleted
	}
	return false
}

func (x *Message) GetEditedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.EditedAt
	}
	return nil
}

func (x *Message) GetHidden() bool {
	if x != nil {
		return x.Hidden
	}
	return false
}

func (x *Message) GetReactions() *ReactionSummary {
	if x != nil {
		return x.Reactions
	}
	return nil
}

type MessageVersion struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ver           uint32                 `protobuf:"varint,1,opt,name=ver,proto3" json:"ver,omitempty"`
	Kind          EditKind               `protobuf:"varint,2,opt,name=kind,proto3,enum=chatim.v1.EditKind" json:"kind,omitempty"`
	Text          string                 `protobuf:"bytes,3,opt,name=text,proto3" json:"text,omitempty"`
	By            string                 `protobuf:"bytes,4,opt,name=by,proto3" json:"by,omitempty"`
	At            *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=at,proto3" json:"at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessageVersion) Reset() {
	*x = MessageVersion{}
	mi := &file_chatim_v1_core_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageVersion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageVersion) ProtoMessage() {}

func (x *MessageVersion) ProtoReflect() protoreflect.Message {
	mi := &file_chatim_v1_core_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageVersion.ProtoReflect.Descriptor instead.
func (*MessageVersion) Descriptor() ([]byte, []int) {
	return file_chatim_v1_core_proto_rawDescGZIP(), []int{2}
}

func (x *MessageVersion) GetVer() uint32 {
	if x != nil {
		return x.Ver
	}
	return 0
}

func (x *MessageVersion) GetKind() EditKind {
	if x != nil {
		return x.Kind
	}
	return EditKind_EDIT_KIND_UNSPECIFIED
}

func (x *MessageVersion) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *MessageVersion) GetBy() string {
	if x != nil {
		return x.By
	}
	return ""
}

func (x *MessageVersion) GetAt() *timestamppb.Timestamp {
	if x != nil {
		return x.At
	}
	return nil
}

type CreateRoomRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          RoomType               `protobuf:"varint,1,opt,name=type,proto3,enum=chatim.v1.RoomType" json:"type,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Members       []string               `protobuf:"bytes,3,rep,name=members,proto3" json:"members,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRoomRequest) Reset() {
	*x = CreateRoomRequest{}
	mi := &file_chatim_v1_core_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRoomRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRoomRequest) ProtoMessage() {}

func (x *CreateRoomRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chatim_v1_core_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRoomRequest.ProtoReflect.Descriptor instead.
func (*CreateRoomRequest) Descriptor() ([]byte, []int) {
	return file_chatim_v1_core_proto_rawDescGZIP(), []int{3}
}

func (x *CreateRoomRequest) GetType() RoomType {
	if x != nil {
		return x.Type
	}
	return RoomType_ROOM_TYPE_UNSPECIFIED
}

func (x *CreateRoomRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateRoomRequest) GetMembers() []string {
	if x != nil {
		return x.Members
	}
	return nil
}

type CreateRoomResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Room          *Room                  `protobuf:"bytes,1,opt,name=room,proto3" json:"room,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRoomResponse) Reset() {
	*x = CreateRoomResponse{}
	mi := &file_chatim_v1_core_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRoomResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRoomResponse) ProtoMessage() {}

func (x *CreateRoomResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chatim_v1_core_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRoomResponse.ProtoReflect.Descriptor instead.
func (*CreateRoomResponse) Descriptor() ([]byte, []int) {
	return file_chatim_v1_core_proto_rawDescGZIP(), []int{4}
}

func (x *CreateRoomResponse) GetRoom() *Room {
	if x != nil {
		return x.Room
	}
	return nil
}

type SendMessageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        string                 `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	ThreadRoot    uint64                 `protobuf:"varint,2,opt,name=thread_root,json=threadRoot,proto3" json:"thread_root,omitempty"`
	Cid           string                 `protobuf:"bytes,3,opt,name=cid,proto3" json:"cid,omitempty"`
	Text          string                 `protobuf:"bytes,4,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendMessageRequest) Reset() {
	*x = SendMessageRequest{}
	mi := &file_chatim_v1_core_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMessageRequest) ProtoMessage() {}

func (x *SendMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chatim_v1_core_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMessageRequest.ProtoReflect.Descriptor instead.
func (*SendMessageRequest) Descriptor() ([]byte, []int) {
	return file_chatim_v1_core_proto_rawDescGZIP(), []int{5}
}

func (x *SendMessageRequest) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *SendMessageRequest) GetThreadRoot() uint64 {
	if x != nil {
		return x.ThreadRoot
	}
	return 0
}

func (x *SendMessageRequest) GetCid() string {
	if x != nil {
		return x.Cid
	}
	return ""
}

func (x *SendMessageRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type SendMessageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Seq           uint64                 `protobuf:"varint,1,opt,name=seq,proto3" json:"seq,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendMessageResponse) Reset() {
	*x = SendMessageResponse{}
	mi := &file_chatim_v1_core_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMessageResponse) ProtoMessage() {}

func (x *SendMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chatim_v1_core_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMessageResponse.ProtoReflect.Descriptor instead.
func (*SendMessageResponse) Descriptor() ([]byte, []int) {
	return file_chatim_v1_core_proto_rawDescGZIP(), []int{6}
}

func (x *SendMessageResponse) GetSeq() uint64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *SendMessageResponse) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type GetHistoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        string                 `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	ThreadRoot    uint64                 `protobuf:"varint,2,opt,name=thread_root,json=threadRoot,proto3" json:"thread_root,omitempty"`
	Anchor        HistoryAnchor          `protobuf:"varint,3,opt,name=anchor,proto3,enum=chatim.v1.HistoryAnchor" json:"anchor,omitempty"`
	Seq           uint64                 `protobuf:"varint,4,opt,name=seq,proto3" json:"seq,omitempty"`
	Limit         int32                  `protobuf:"varint,5,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetHistoryRequest) Reset() {
	*x = GetHistoryRequest{}
	mi := &file_chatim_v1_core_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHistoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHistoryRequest) ProtoMessage() {}

func (x *GetHistoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chatim_v1_core_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHistoryRequest.ProtoReflect.Descriptor instead.
func (*GetHistoryRequest) Descriptor() ([]byte, []int) {
	return file_chatim_v1_core_proto_rawDescGZIP(), []int{7}
}

func (x *GetHistoryRequest) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *GetHistoryRequest) GetThreadRoot() uint64 {
	if x != nil {
		return x.ThreadRoot
	}
	return 0
}

func (x *GetHistoryRequest) GetAnchor() HistoryAnchor {
	if x != nil {
		return x.Anchor
	}
	return HistoryAnchor_HISTORY_ANCHOR_UNSPECIFIED
}

func (x *GetHistoryRequest) GetSeq() uint64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *GetHistoryRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type GetHistoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Messages      []*Message             `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetHistoryResponse) Reset() {
	*x = GetHistoryResponse{}
	mi := &file_chatim_v1_core_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHistoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHistoryResponse) ProtoMessage() {}

func (x *GetHistoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chatim_v1_core_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHistoryResponse.ProtoReflect.Descriptor instead.
func (*GetHistoryResponse) Descriptor() ([]byte, []int) {
	return file_chatim_v1_core_proto_rawDescGZIP(), []int{8}
}

func (x *GetHistoryResponse) GetMessages() []*Message {
	if x != nil {
		return x.Messages
	}
	return nil
}

type EditMessageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        string                 `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	ThreadRoot    uint64                 `protobuf:"varint,2,opt,name=thread_root,json=threadRoot,proto3" json:"thread_root,omitempty"`
	Seq           uint64                 `protobuf:"varint,3,opt,name=seq,proto3" json:"seq,omitempty"`
	BaseVer       uint32                 `protobuf:"varint,4,opt,name=base_ver,json=baseVer,proto3" json:"base_ver,omitempty"`
	Text          string                 `protobuf:"bytes,5,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EditMessageRequest) Reset() {
	*x = EditMessageRequest{}
	mi := &file_chatim_v1_core_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EditMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EditMessageRequest) ProtoMessage() {}

func (x *EditMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chatim_v1_core_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EditMessageRequest.ProtoReflect.Descriptor instead.
func (*EditMessageRequest) Descriptor() ([]byte, []int) {
	return file_chatim_v1_core_proto_rawDescGZIP(), []int{9}
}

func (x *EditMessageRequest) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *EditMessageRequest) GetThreadRoot() uint64 {
	if x != nil {
		return x.ThreadRoot
	}
	return 0
}

func (x *EditMessageRequest) GetSeq() uint64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *EditMessageRequest) GetBaseVer() uint32 {
	if x != nil {
		return x.BaseVer
	}
	return 0
}

func (x *EditMessageRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type EditMessageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       *Message               `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EditMessageResponse) Reset() {
	*x = EditMessageResponse{}
	mi := &file_chatim_v1_core_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EditMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EditMessageResponse) ProtoMessage() {}

func (x *EditMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chatim_v1_core_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EditMessageResponse.ProtoReflect.Descriptor instead.
func (*EditMessageResponse) Descriptor() ([]byte, []int) {
	return file_chatim_v1_core_proto_rawDescGZIP(), []int{10}
}

func (x *EditMessageResponse) GetMessage() *Message {
	if x != nil {
		return x.Message
	}
	return nil
}

type DeleteMessageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        string                 `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	ThreadRoot    uint64                 `protobuf:"varint,2,opt,name=thread_root,json=threadRoot,proto3" json:"thread_root,omitempty"`
	Seq           uint64                 `protobuf:"varint,3,opt,name=seq,proto3" json:"seq,omitempty"`
	BaseVer       uint32                 `protobuf:"varint,4,opt,name=base_ver,json=baseVer,proto3" json:"base_ver,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteMessageRequest) Reset() {
	*x = DeleteMessageRequest{}
	mi := &file_chatim_v1_core_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteMessageRequest) ProtoMessage() {}

func (x *DeleteMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chatim_v1_core_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteMessageRequest.ProtoReflect.Descriptor instead.
func (*DeleteMessageRequest) Descriptor() ([]byte, []int) {
	return file_chatim_v1_core_proto_rawDescGZIP(), []int{11}
}

func (x *DeleteMessageRequest) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *DeleteMessageRequest) GetThreadRoot() uint64 {
	if x != nil {
		return x.ThreadRoot
	}
	return 0
}

func (x *DeleteMessageRequest) GetSeq() uint64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *DeleteMessageRequest) GetBaseVer() uint32 {
	if x != nil {
		return x.BaseVer
	}
	return 0
}

type DeleteMessageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       *Message               `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteMessageResponse) Reset() {
	*x = DeleteMessageResponse{}
	mi := &file_chatim_v1_core_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteMessageResponse) ProtoMessage() {}

func (x *DeleteMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chatim_v1_core_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteMessageResponse.ProtoReflect.Descriptor instead.
func (*DeleteMessageResponse) Descriptor() ([]byte, []int) {
	return file_chatim_v1_core_proto_rawDescGZIP(), []int{12}
}

func (x *DeleteMessageResponse) GetMessage() *Message {
	if x != nil {
		return x.Message
	}
	return nil
}

type HideMessageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        string                 `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	ThreadRoot    uint64                 `protobuf:"varint,2,opt,name=thread_root,json=threadRoot,proto3" json:"thread_root,omitempty"`
	Seq           uint64                 `protobuf:"varint,3,opt,name=seq,proto3" json:"seq,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HideMessageRequest) Reset() {
	*x = HideMessageRequest{}
	mi := &file_chatim_v1_core_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HideMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HideMessageRequest) ProtoMessage() {}

func (x *HideMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chatim_v1_core_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HideMessageRequest.ProtoReflect.Descriptor instead.
func (*HideMessageRequest) Descriptor() ([]byte, []int) {
	return file_chatim_v1_core_proto_rawDescGZIP(), []int{13}
}

func (x *HideMessageRequest) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *HideMessageRequest) GetThreadRoot() uint64 {
	if x != nil {
		return x.ThreadRoot
	}
	return 0
}

func (x *HideMessageRequest) GetSeq() uint64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

type HideMessageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HideMessageResponse) Reset() {
	*x = HideMessageResponse{}
	mi := &file_chatim_v1_core_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HideMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HideMessageResponse) ProtoMessage() {}

func (x *HideMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chatim_v1_core_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HideMessageResponse.ProtoReflect.Descriptor instead.
func (*HideMessageResponse) Descriptor() ([]byte, []int) {
	return file_chatim_v1_core_proto_rawDescGZIP(), []int{14}
}

type ClearHistoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        string                 `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClearHistoryRequest) Reset() {
	*x = ClearHistoryRequest{}
	mi := &file_chatim_v1_core_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClearHistoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClearHistoryRequest) ProtoMessage() {}

func (x *ClearHistoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chatim_v1_core_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClearHistoryRequest.ProtoReflect.Descriptor instead.
func (*ClearHistoryRequest) Descriptor() ([]byte, []int) {
	return file_chatim_v1_core_proto_rawDescGZIP(), []int{15}
}

func (x *ClearHistoryRequest) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

type ClearHistoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClearedAt     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=cleared_at,json=clearedAt,proto3" json:"cleared_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClearHistoryResponse) Reset() {
	*x = ClearHistoryResponse{}
	mi := &file_chatim_v1_core_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClearHistoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClearHistoryResponse) ProtoMessage() {}

func (x *ClearHistoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chatim_v1_core_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClearHistoryResponse.ProtoReflect.Descriptor instead.
func (*ClearHistoryResponse) Descriptor() ([]byte, []int) {
	return file_chatim_v1_core_proto_rawDescGZIP(), []int{16}
}

func (x *ClearHistoryResponse) GetClearedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ClearedAt
	}
	return nil
}

type GetEditHistoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        string                 `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	ThreadRoot    uint64                 `protobuf:"varint,2,opt,name=thread_root,json=threadRoot,proto3" json:"thread_root,omitempty"`
	Seq           uint64                 `protobuf:"varint,3,opt,name=seq,proto3" json:"seq,omitempty"`
	AfterVer      uint32                 `protobuf:"varint,4,opt,name=after_ver,json=afterVer,proto3" json:"after_ver,omitempty"`
	Limit         uint32                 `protobuf:"varint,5,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEditHistoryRequest) Reset() {
	*x = GetEditHistoryRequest{}
	mi := &file_chatim_v1_core_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEditHistoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEditHistoryRequest) ProtoMessage() {}

func (x *GetEditHistoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chatim_v1_core_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEditHistoryRequest.ProtoReflect.Descriptor instead.
func (*GetEditHistoryRequest) Descriptor() ([]byte, []int) {
	return file_chatim_v1_core_proto_rawDescGZIP(), []int{17}
}

func (x *GetEditHistoryRequest) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *GetEditHistoryRequest) GetThreadRoot() uint64 {
	if x != nil {
		return x.ThreadRoot
	}
	return 0
}

func (x *GetEditHistoryRequest) GetSeq() uint64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *GetEditHistoryRequest) GetAfterVer() uint32 {
	if x != nil {
		return x.AfterVer
	}
	return 0
}

func (x *GetEditHistoryRequest) GetLimit() uint32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type GetEditHistoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Versions      []*MessageVersion      `protobuf:"bytes,1,rep,name=versions,proto3" json:"versions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEditHistoryResponse) Reset() {
	*x = GetEditHistoryResponse{}
	mi := &file_chatim_v1_core_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEditHistoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEditHistoryResponse) ProtoMessage() {}

func (x *GetEditHistoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chatim_v1_core_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEditHistoryResponse.ProtoReflect.Descriptor instead.
func (*GetEditHistoryResponse) Descriptor() ([]byte, []int) {
	return file_chatim_v1_core_proto_rawDescGZIP(), []int{18}
}

func (x *GetEditHistoryResponse) GetVersions() []*MessageVersion {
	if x != nil {
		return x.Versions
	}
	return nil
}

var File_chatim_v1_core_proto protoreflect.FileDescriptor

const file_chatim_v1_core_proto_rawDesc = "" +
	"\n" +
	"\x14chatim/v1/core.proto\x12\tchatim.v1\x1a\x1echatim/v1/reactions_pins.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xe8\x01\n" +
	"\x04Room\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06tenant\x18\x02 \x01(\tR\x06tenant\x12'\n" +
	"\x04type\x18\x03 \x01(\x0e2\x13.chatim.v1.RoomTypeR\x04type\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"created_by\x18\x05 \x01(\tR\tcreatedBy\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12!\n" +
	"\fmember_count\x18\a \x01(\x05R\vmemberCount\"\xbc\x03\n" +
	"\aMessage\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\tR\x06roomId\x12\x1f\n" +
	"\vthread_root\x18\x02 \x01(\x04R\n" +
	"threadRoot\x12\x10\n" +
	"\x03seq\x18\x03 \x01(\x04R\x03seq\x12\x16\n" +
	"\x06sender\x18\x05 \x01(\tR\x06sender\x12*\n" +
	"\x04kind\x18\x06 \x01(\x0e2\x16.chatim.v1.MessageKindR\x04kind\x12\x12\n" +
	"\x04text\x18\a \x01(\tR\x04text\x12\x10\n" +
	"\x03cid\x18\b \x01(\tR\x03cid\x129\n" +
	"\n" +
	"created_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12\x10\n" +
	"\x03ver\x18\n" +
	" \x01(\rR\x03ver\x12\x18\n" +
	"\adeleted\x18\v \x01(\bR\adeleted\x127\n" +
	"\tedited_at\x18\f \x01(\v2\x1a.google.protobuf.TimestampR\beditedAt\x12\x16\n" +
	"\x06hidden\x18\r \x01(\bR\x06hidden\x128\n" +
	"\treactions\x18\x0e \x01(\v2\x1a.chatim.v1.ReactionSummaryR\treactionsJ\x04\b\x04\x10\x05R\x03pts\"\x9b\x01\n" +
	"\x0eMessageVersion\x12\x10\n" +
	"\x03ver\x18\x01 \x01(\rR\x03ver\x12'\n" +
	"\x04kind\x18\x02 \x01(\x0e2\x13.chatim.v1.EditKindR\x04kind\x12\x12\n" +
	"\x04text\x18\x03 \x01(\tR\x04text\x12\x0e\n" +
	"\x02by\x18\x04 \x01(\tR\x02by\x12*\n" +
	"\x02at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\x02at\"j\n" +
	"\x11CreateRoomRequest\x12'\n" +
	"\x04type\x18\x01 \x01(\x0e2\x13.chatim.v1.RoomTypeR\x04type\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x18\n" +
	"\amembers\x18\x03 \x03(\tR\amembers\"9\n" +
	"\x12CreateRoomResponse\x12#\n" +
	"\x04room\x18\x01 \x01(\v2\x0f.chatim.v1.RoomR\x04room\"t\n" +
	"\x12SendMessageRequest\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\tR\x06roomId\x12\x1f\n" +
	"\vthread_root\x18\x02 \x01(\x04R\n" +
	"threadRoot\x12\x10\n" +
	"\x03cid\x18\x03 \x01(\tR\x03cid\x12\x12\n" +
	"\x04text\x18\x04 \x01(\tR\x04text\"m\n" +
	"\x13SendMessageResponse\x12\x10\n" +
	"\x03seq\x18\x01 \x01(\x04R\x03seq\x129\n" +
	"\n" +
	"created_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAtJ\x04\b\x02\x10\x03R\x03pts\"\xa7\x01\n" +
	"\x11GetHistoryRequest\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\tR\x06roomId\x12\x1f\n" +
	"\vthread_root\x18\x02 \x01(\x04R\n" +
	"threadRoot\x120\n" +
	"\x06anchor\x18\x03 \x01(\x0e2\x18.chatim.v1.HistoryAnchorR\x06anchor\x12\x10\n" +
	"\x03seq\x18\x04 \x01(\x04R\x03seq\x12\x14\n" +
	"\x05limit\x18\x05 \x01(\x05R\x05limit\"D\n" +
	"\x12GetHistoryResponse\x12.\n" +
	"\bmessages\x18\x01 \x03(\v2\x12.chatim.v1.MessageR\bmessages\"\x8f\x01\n" +
	"\x12EditMessageRequest\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\tR\x06roomId\x12\x1f\n" +
	"\vthread_root\x18\x02 \x01(\x04R\n" +
	"threadRoot\x12\x10\n" +
	"\x03seq\x18\x03 \x01(\x04R\x03seq\x12\x19\n" +
	"\bbase_ver\x18\x04 \x01(\rR\abaseVer\x12\x12\n" +
	"\x04text\x18\x05 \x01(\tR\x04text\"C\n" +
	"\x13EditMessageResponse\x12,\n" +
	"\amessage\x18\x01 \x01(\v2\x12.chatim.v1.MessageR\amessage\"}\n" +
	"\x14DeleteMessageRequest\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\tR\x06roomId\x12\x1f\n" +
	"\vthread_root\x18\x02 \x01(\x04R\n" +
	"threadRoot\x12\x10\n" +
	"\x03seq\x18\x03 \x01(\x04R\x03seq\x12\x19\n" +
	"\bbase_ver\x18\x04 \x01(\rR\abaseVer\"E\n" +
	"\x15DeleteMessageResponse\x12,\n" +
	"\amessage\x18\x01 \x01(\v2\x12.chatim.v1.MessageR\amessage\"`\n" +
	"\x12HideMessageRequest\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\tR\x06roomId\x12\x1f\n" +
	"\vthread_root\x18\x02 \x01(\x04R\n" +
	"threadRoot\x12\x10\n" +
	"\x03seq\x18\x03 \x01(\x04R\x03seq\"\x15\n" +
	"\x13HideMessageResponse\"?\n" +
	"\x13ClearHistoryRequest\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\tR\x06roomIdJ\x04\b\x02\x10\x03R\tup_to_seq\"k\n" +
	"\x14ClearHistoryResponse\x129\n" +
	"\n" +
	"cleared_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tclearedAtJ\x04\b\x01\x10\x02R\x12cleared_before_seq\"\x96\x01\n" +
	"\x15GetEditHistoryRequest\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\tR\x06roomId\x12\x1f\n" +
	"\vthread_root\x18\x02 \x01(\x04R\n" +
	"threadRoot\x12\x10\n" +
	"\x03seq\x18\x03 \x01(\x04R\x03seq\x12\x1b\n" +
	"\tafter_ver\x18\x04 \x01(\rR\bafterVer\x12\x14\n" +
	"\x05limit\x18\x05 \x01(\rR\x05limit\"O\n" +
	"\x16GetEditHistoryResponse\x125\n" +
	"\bversions\x18\x01 \x03(\v2\x19.chatim.v1.MessageVersionR\bversions*L\n" +
	"\bRoomType\x12\x19\n" +
	"\x15ROOM_TYPE_UNSPECIFIED\x10\x00\x12\x10\n" +
	"\fROOM_TYPE_DM\x10\x01\x12\x13\n" +
	"\x0fROOM_TYPE_GROUP\x10\x02*B\n" +
	"\vMessageKind\x12\x1c\n" +
	"\x18MESSAGE_KIND_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11MESSAGE_KIND_TEXT\x10\x01*\x9a\x01\n" +
	"\rHistoryAnchor\x12\x1e\n" +
	"\x1aHISTORY_ANCHOR_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15HISTORY_ANCHOR_LATEST\x10\x01\x12\x19\n" +
	"\x15HISTORY_ANCHOR_OLDEST\x10\x02\x12\x19\n" +
	"\x15HISTORY_ANCHOR_BEFORE\x10\x03\x12\x18\n" +
	"\x14HISTORY_ANCHOR_AFTER\x10\x04*g\n" +
	"\bEditKind\x12\x19\n" +
	"\x15EDIT_KIND_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12EDIT_KIND_ORIGINAL\x10\x01\x12\x12\n" +
	"\x0eEDIT_KIND_TEXT\x10\x02\x12\x14\n" +
	"\x10EDIT_KIND_DELETE\x10\x032\xdc\a\n" +
	"\vCoreService\x12I\n" +
	"\n" +
	"CreateRoom\x12\x1c.chatim.v1.CreateRoomRequest\x1a\x1d.chatim.v1.CreateRoomResponse\x12L\n" +
	"\vSendMessage\x12\x1d.chatim.v1.SendMessageRequest\x1a\x1e.chatim.v1.SendMessageResponse\x12I\n" +
	"\n" +
	"GetHistory\x12\x1c.chatim.v1.GetHistoryRequest\x1a\x1d.chatim.v1.GetHistoryResponse\x12L\n" +
	"\vEditMessage\x12\x1d.chatim.v1.EditMessageRequest\x1a\x1e.chatim.v1.EditMessageResponse\x12R\n" +
	"\rDeleteMessage\x12\x1f.chatim.v1.DeleteMessageRequest\x1a .chatim.v1.DeleteMessageResponse\x12L\n" +
	"\vHideMessage\x12\x1d.chatim.v1.HideMessageRequest\x1a\x1e.chatim.v1.HideMessageResponse\x12O\n" +
	"\fClearHistory\x12\x1e.chatim.v1.ClearHistoryRequest\x1a\x1f.chatim.v1.ClearHistoryResponse\x12U\n" +
	"\x0eGetEditHistory\x12 .chatim.v1.GetEditHistoryRequest\x1a!.chatim.v1.GetEditHistoryResponse\x12O\n" +
	"\fReactMessage\x12\x1e.chatim.v1.ReactMessageRequest\x1a\x1f.chatim.v1.ReactMessageResponse\x12I\n" +
	"\n" +
	"PinMessage\x12\x1c.chatim.v1.PinMessageRequest\x1a\x1d.chatim.v1.PinMessageResponse\x12O\n" +
	"\fUnpinMessage\x12\x1e.chatim.v1.UnpinMessageRequest\x1a\x1f.chatim.v1.UnpinMessageResponse\x12d\n" +
	"\x13GetReactionSettings\x12%.chatim.v1.GetReactionSettingsRequest\x1a&.chatim.v1.GetReactionSettingsResponseB\x9a\x01\n" +
	"\rcom.chatim.v1B\tCoreProtoP\x01Z9github.com/ivannguyendev/chatim/pkg/pb/chatim/v1;chatimv1\xa2\x02\x03CXX\xaa\x02\tChatim.V1\xca\x02\tChatim\\V1\xe2\x02\x15Chatim\\V1\\GPBMetadata\xea\x02\n" +
	"Chatim::V1b\x06proto3"

var (
	file_chatim_v1_core_proto_rawDescOnce sync.Once
	file_chatim_v1_core_proto_rawDescData []byte
)

func file_chatim_v1_core_proto_rawDescGZIP() []byte {
	file_chatim_v1_core_proto_rawDescOnce.Do(func() {
		file_chatim_v1_core_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_chatim_v1_core_proto_rawDesc), len(file_chatim_v1_core_proto_rawDesc)))
	})
	return file_chatim_v1_core_proto_rawDescData
}

var file_chatim_v1_core_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_chatim_v1_core_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_chatim_v1_core_proto_goTypes = []any{
	(RoomType)(0),                       // 0: chatim.v1.RoomType
	(MessageKind)(0),                    // 1: chatim.v1.MessageKind
	(HistoryAnchor)(0),                  // 2: chatim.v1.HistoryAnchor
	(EditKind)(0),                       // 3: chatim.v1.EditKind
	(*Room)(nil),                        // 4: chatim.v1.Room
	(*Message)(nil),                     // 5: chatim.v1.Message
	(*MessageVersion)(nil),              // 6: chatim.v1.MessageVersion
	(*CreateRoomRequest)(nil),           // 7: chatim.v1.CreateRoomRequest
	(*CreateRoomResponse)(nil),          // 8: chatim.v1.CreateRoomResponse
	(*SendMessageRequest)(nil),          // 9: chatim.v1.SendMessageRequest
	(*SendMessageResponse)(nil),         // 10: chatim.v1.SendMessageResponse
	(*GetHistoryRequest)(nil),           // 11: chatim.v1.GetHistoryRequest
	(*GetHistoryResponse)(nil),          // 12: chatim.v1.GetHistoryResponse
	(*EditMessageRequest)(nil),          // 13: chatim.v1.EditMessageRequest
	(*EditMessageResponse)(nil),         // 14: chatim.v1.EditMessageResponse
	(*DeleteMessageRequest)(nil),        // 15: chatim.v1.DeleteMessageRequest
	(*DeleteMessageResponse)(nil),       // 16: chatim.v1.DeleteMessageResponse
	(*HideMessageRequest)(nil),          // 17: chatim.v1.HideMessageRequest
	(*HideMessageResponse)(nil),         // 18: chatim.v1.HideMessageResponse
	(*ClearHistoryRequest)(nil),         // 19: chatim.v1.ClearHistoryRequest
	(*ClearHistoryResponse)(nil),        // 20: chatim.v1.ClearHistoryResponse
	(*GetEditHistoryRequest)(nil),       // 21: chatim.v1.GetEditHistoryRequest
	(*GetEditHistoryResponse)(nil),      // 22: chatim.v1.GetEditHistoryResponse
	(*timestamppb.Timestamp)(nil),       // 23: google.protobuf.Timestamp
	(*ReactionSummary)(nil),             // 24: chatim.v1.ReactionSummary
	(*ReactMessageRequest)(nil),         // 25: chatim.v1.ReactMessageRequest
	(*PinMessageRequest)(nil),           // 26: chatim.v1.PinMessageRequest
	(*UnpinMessageRequest)(nil),         // 27: chatim.v1.UnpinMessageRequest
	(*GetReactionSettingsRequest)(nil),  // 28: chatim.v1.GetReactionSettingsRequest
	(*ReactMessageResponse)(nil),        // 29: chatim.v1.ReactMessageResponse
	(*PinMessageResponse)(nil),          // 30: chatim.v1.PinMessageResponse
	(*UnpinMessageResponse)(nil),        // 31: chatim.v1.UnpinMessageResponse
	(*GetReactionSettingsResponse)(nil), // 32: chatim.v1.GetReactionSettingsResponse
}
var file_chatim_v1_core_proto_depIdxs = []int32{
	0,  // 0: chatim.v1.Room.type:type_name -> chatim.v1.RoomType
	23, // 1: chatim.v1.Room.created_at:type_name -> google.protobuf.Timestamp
	1,  // 2: chatim.v1.Message.kind:type_name -> chatim.v1.MessageKind
	23, // 3: chatim.v1.Message.created_at:type_name -> google.protobuf.Timestamp
	23, // 4: chatim.v1.Message.edited_at:type_name -> google.protobuf.Timestamp
	24, // 5: chatim.v1.Message.reactions:type_name -> chatim.v1.ReactionSummary
	3,  // 6: chatim.v1.MessageVersion.kind:type_name -> chatim.v1.EditKind
	23, // 7: chatim.v1.MessageVersion.at:type_name -> google.protobuf.Timestamp
	0,  // 8: chatim.v1.CreateRoomRequest.type:type_name -> chatim.v1.RoomType
	4,  // 9: chatim.v1.CreateRoomResponse.room:type_name -> chatim.v1.Room
	23, // 10: chatim.v1.SendMessageResponse.created_at:type_name -> google.protobuf.Timestamp
	2,  // 11: chatim.v1.GetHistoryRequest.anchor:type_name -> chatim.v1.HistoryAnchor
	5,  // 12: chatim.v1.GetHistoryResponse.messages:type_name -> chatim.v1.Message
	5,  // 13: chatim.v1.EditMessageResponse.message:type_name -> chatim.v1.Message
	5,  // 14: chatim.v1.DeleteMessageResponse.message:type_name -> chatim.v1.Message
	23, // 15: chatim.v1.ClearHistoryResponse.cleared_at:type_name -> google.protobuf.Timestamp
	6,  // 16: chatim.v1.GetEditHistoryResponse.versions:type_name -> chatim.v1.MessageVersion
	7,  // 17: chatim.v1.CoreService.CreateRoom:input_type -> chatim.v1.CreateRoomRequest
	9,  // 18: chatim.v1.CoreService.SendMessage:input_type -> chatim.v1.SendMessageRequest
	11, // 19: chatim.v1.CoreService.GetHistory:input_type -> chatim.v1.GetHistoryRequest
	13, // 20: chatim.v1.CoreService.EditMessage:input_type -> chatim.v1.EditMessageRequest
	15, // 21: chatim.v1.CoreService.DeleteMessage:input_type -> chatim.v1.DeleteMessageRequest
	17, // 22: chatim.v1.CoreService.HideMessage:input_type -> chatim.v1.HideMessageRequest
	19, // 23: chatim.v1.CoreService.ClearHistory:input_type -> chatim.v1.ClearHistoryRequest
	21, // 24: chatim.v1.CoreService.GetEditHistory:input_type -> chatim.v1.GetEditHistoryRequest
	25, // 25: chatim.v1.CoreService.ReactMessage:input_type -> chatim.v1.ReactMessageRequest
	26, // 26: chatim.v1.CoreService.PinMessage:input_type -> chatim.v1.PinMessageRequest
	27, // 27: chatim.v1.CoreService.UnpinMessage:input_type -> chatim.v1.UnpinMessageRequest
	28, // 28: chatim.v1.CoreService.GetReactionSettings:input_type -> chatim.v1.GetReactionSettingsRequest
	8,  // 29: chatim.v1.CoreService.CreateRoom:output_type -> chatim.v1.CreateRoomResponse
	10, // 30: chatim.v1.CoreService.SendMessage:output_type -> chatim.v1.SendMessageResponse
	12, // 31: chatim.v1.CoreService.GetHistory:output_type -> chatim.v1.GetHistoryResponse
	14, // 32: chatim.v1.CoreService.EditMessage:output_type -> chatim.v1.EditMessageResponse
	16, // 33: chatim.v1.CoreService.DeleteMessage:output_type -> chatim.v1.DeleteMessageResponse
	18, // 34: chatim.v1.CoreService.HideMessage:output_type -> chatim.v1.HideMessageResponse
	20, // 35: chatim.v1.CoreService.ClearHistory:output_type -> chatim.v1.ClearHistoryResponse
	22, // 36: chatim.v1.CoreService.GetEditHistory:output_type -> chatim.v1.GetEditHistoryResponse
	29, // 37: chatim.v1.CoreService.ReactMessage:output_type -> chatim.v1.ReactMessageResponse
	30, // 38: chatim.v1.CoreService.PinMessage:output_type -> chatim.v1.PinMessageResponse
	31, // 39: chatim.v1.CoreService.UnpinMessage:output_type -> chatim.v1.UnpinMessageResponse
	32, // 40: chatim.v1.CoreService.GetReactionSettings:output_type -> chatim.v1.GetReactionSettingsResponse
	29, // [29:41] is the sub-list for method output_type
	17, // [17:29] is the sub-list for method input_type
	17, // [17:17] is the sub-list for extension type_name
	17, // [17:17] is the sub-list for extension extendee
	0,  // [0:17] is the sub-list for field type_name
}

func init() { file_chatim_v1_core_proto_init() }
func file_chatim_v1_core_proto_init() {
	if File_chatim_v1_core_proto != nil {
		return
	}
	file_chatim_v1_reactions_pins_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_chatim_v1_core_proto_rawDesc), len(file_chatim_v1_core_proto_rawDesc)),
			NumEnums:      4,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_chatim_v1_core_proto_goTypes,
		DependencyIndexes: file_chatim_v1_core_proto_depIdxs,
		EnumInfos:         file_chatim_v1_core_proto_enumTypes,
		MessageInfos:      file_chatim_v1_core_proto_msgTypes,
	}.Build()
	File_chatim_v1_core_proto = out.File
	file_chatim_v1_core_proto_goTypes = nil
	file_chatim_v1_core_proto_depIdxs = nil
}
