// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: chatim/v1/core.proto

package chatimv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RoomType int32

const (
	RoomType_ROOM_TYPE_UNSPECIFIED RoomType = 0
	RoomType_ROOM_TYPE_DM          RoomType = 1
	RoomType_ROOM_TYPE_GROUP       RoomType = 2
)

// Enum value maps for RoomType.
var (
	RoomType_name = map[int32]string{
		0: "ROOM_TYPE_UNSPECIFIED",
		1: "ROOM_TYPE_DM",
		2: "ROOM_TYPE_GROUP",
	}
	RoomType_value = map[string]int32{
		"ROOM_TYPE_UNSPECIFIED": 0,
		"ROOM_TYPE_DM":          1,
		"ROOM_TYPE_GROUP":       2,
	}
)

func (x RoomType) Enum() *RoomType {
	p := new(RoomType)
	*p = x
	return p
}

func (x RoomType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RoomType) Descriptor() protoreflect.EnumDescriptor {
	return file_chatim_v1_core_proto_enumTypes[0].Descriptor()
}

func (RoomType) Type() protoreflect.EnumType {
	return &file_chatim_v1_core_proto_enumTypes[0]
}

func (x RoomType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RoomType.Descriptor instead.
func (RoomType) EnumDescriptor() ([]byte, []int) {
	return file_chatim_v1_core_proto_rawDescGZIP(), []int{0}
}

type MessageKind int32

const (
	MessageKind_MESSAGE_KIND_UNSPECIFIED MessageKind = 0
	MessageKind_MESSAGE_KIND_TEXT        MessageKind = 1
)

// Enum value maps for MessageKind.
var (
	MessageKind_name = map[int32]string{
		0: "MESSAGE_KIND_UNSPECIFIED",
		1: "MESSAGE_KIND_TEXT",
	}
	MessageKind_value = map[string]int32{
		"MESSAGE_KIND_UNSPECIFIED": 0,
		"MESSAGE_KIND_TEXT":        1,
	}
)

func (x MessageKind) Enum() *MessageKind {
	p := new(MessageKind)
	*p = x
	return p
}

func (x MessageKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MessageKind) Descriptor() protoreflect.EnumDescriptor {
	return file_chatim_v1_core_proto_enumTypes[1].Descriptor()
}

func (MessageKind) Type() protoreflect.EnumType {
	return &file_chatim_v1_core_proto_enumTypes[1]
}

func (x MessageKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MessageKind.Descriptor instead.
func (MessageKind) EnumDescriptor() ([]byte, []int) {
	return file_chatim_v1_core_proto_rawDescGZIP(), []int{1}
}

type HistoryAnchor int32

const (
	HistoryAnchor_HISTORY_ANCHOR_UNSPECIFIED HistoryAnchor = 0
	HistoryAnchor_HISTORY_ANCHOR_LATEST      HistoryAnchor = 1
	HistoryAnchor_HISTORY_ANCHOR_OLDEST      HistoryAnchor = 2
	HistoryAnchor_HISTORY_ANCHOR_BEFORE      HistoryAnchor = 3
	HistoryAnchor_HISTORY_ANCHOR_AFTER       HistoryAnchor = 4
)

// Enum value maps for HistoryAnchor.
var (
	HistoryAnchor_name = map[int32]string{
		0: "HISTORY_ANCHOR_UNSPECIFIED",
		1: "HISTORY_ANCHOR_LATEST",
		2: "HISTORY_ANCHOR_OLDEST",
		3: "HISTORY_ANCHOR_BEFORE",
		4: "HISTORY_ANCHOR_AFTER",
	}
	HistoryAnchor_value = map[string]int32{
		"HISTORY_ANCHOR_UNSPECIFIED": 0,
		"HISTORY_ANCHOR_LATEST":      1,
		"HISTORY_ANCHOR_OLDEST":      2,
		"HISTORY_ANCHOR_BEFORE":      3,
		"HISTORY_ANCHOR_AFTER":       4,
	}
)

func (x HistoryAnchor) Enum() *HistoryAnchor {
	p := new(HistoryAnchor)
	*p = x
	return p
}

func (x HistoryAnchor) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (HistoryAnchor) Descriptor() protoreflect.EnumDescriptor {
	return file_chatim_v1_core_proto_enumTypes[2].Descriptor()
}

func (HistoryAnchor) Type() protoreflect.EnumType {
	return &file_chatim_v1_core_proto_enumTypes[2]
}

func (x HistoryAnchor) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use HistoryAnchor.Descriptor instead.
func (HistoryAnchor) EnumDescriptor() ([]byte, []int) {
	return file_chatim_v1_core_proto_rawDescGZIP(), []int{2}
}

type EditKind int32

const (
	EditKind_EDIT_KIND_UNSPECIFIED EditKind = 0
	EditKind_EDIT_KIND_ORIGINAL    EditKind = 1
	EditKind_EDIT_KIND_TEXT        EditKind = 2
	EditKind_EDIT_KIND_DELETE      EditKind = 3
)

// Enum value maps for EditKind.
var (
	EditKind_name = map[int32]string{
		0: "EDIT_KIND_UNSPECIFIED",
		1: "EDIT_KIND_ORIGINAL",
		2: "EDIT_KIND_TEXT",
		3: "EDIT_KIND_DELETE",
	}
	EditKind_value = map[string]int32{
		"EDIT_KIND_UNSPECIFIED": 0,
		"EDIT_KIND_ORIGINAL":    1,
		"EDIT_KIND_TEXT":        2,
		"EDIT_KIND_DELETE":      3,
	}
)

func (x EditKind) Enum() *EditKind {
	p := new(EditKind)
	*p = x
	return p
}

func (x EditKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EditKind) Descriptor() protoreflect.EnumDescriptor {
	return file_chatim_v1_core_proto_enumTypes[3].Descriptor()
}

func (EditKind) Type() protoreflect.EnumType {
	return &file_chatim_v1_core_proto_enumTypes[3]
}

func (x EditKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EditKind.Descriptor instead.
func (EditKind) EnumDescriptor() ([]byte, []int) {
	return file_chatim_v1_core_proto_rawDescGZIP(), []int{3}
}

type Room struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Tenant        string                 `protobuf:"bytes,2,opt,name=tenant,proto3" json:"tenant,omitempty"`
	Type          RoomType               `protobuf:"varint,3,opt,name=type,proto3,enum=chatim.v1.RoomType" json:"type,omitempty"`
	Name          string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	CreatedBy     string                 `protobuf:"bytes,5,opt,name=created_by,json=createdBy,proto3" json:"created_by,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	MemberCount   int32                  `protobuf:"varint,7,opt,name=member_count,json=memberCount,proto3" json:"member_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Room) Reset() {
	*x = Room{}
	mi := &file_chatim_v1_core_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Room) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Room) ProtoMessage() {}

func (x *Room) ProtoReflect() protoreflect.Message {
	mi := &file_chatim_v1_core_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Room.ProtoReflect.Descriptor instead.
func (*Room) Descriptor() ([]byte, []int) {
	return file_chatim_v1_core_proto_rawDescGZIP(), []int{0}
}

func (x *Room) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Room) GetTenant() string {
	if x != nil {
		return x.Tenant
	}
	return ""
}

func (x *Room) GetType() RoomType {
	if x != nil {
		return x.Type
	}
	return RoomType_ROOM_TYPE_UNSPECIFIED
}

func (x *Room) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Room) GetCreatedBy() string {
	if x != nil {
		return x.CreatedBy
	}
	return ""
}

func (x *Room) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Room) GetMemberCount() int32 {
	if x != nil {
		return x.MemberCount
	}
	return 0
}

type Message struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        string                 `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	ThreadRoot    uint64                 `protobuf:"varint,2,opt,name=thread_root,json=threadRoot,proto3" json:"thread_root,omitempty"`
	Seq           uint64                 `protobuf:"varint,3,opt,name=seq,proto3" json:"seq,omitempty"`
	Sender        string                 `protobuf:"bytes,5,opt,name=sender,proto3" json:"sender,omitempty"`
	Kind          MessageKind            `protobuf:"varint,6,opt,name=kind,proto3,enum=chatim.v1.MessageKind" json:"kind,omitempty"`
	Text          string                 `protobuf:"bytes,7,opt,name=text,proto3" json:"text,omitempty"`
	Cid           string                 `protobuf:"bytes,8,opt,name=cid,proto3" json:"cid,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	Version       uint32                 `protobuf:"varint,10,opt,name=version,proto3" json:"version,omitempty"`
	Deleted       bool                   `protobuf:"varint,11,opt,name=deleted,proto3" json:"deleted,omitempty"`
	EditedAt      *timestamppb.Timestamp `protobuf:"bytes,12,opt,name=edited_at,json=editedAt,proto3" json:"edited_at,omitempty"`
	Hidden        bool                   `protobuf:"varint,13,opt,name=hidden,proto3" json:"hidden,omitempty"`
	Reactions     *ReactionSummary       `protobuf:"bytes,14,opt,name=reactions,proto3" json:"reactions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_chatim_v1_core_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_chatim_v1_core_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_chatim_v1_core_proto_rawDescGZIP(), []int{1}
}

func (x *Message) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *Message) GetThreadRoot() uint64 {
	if x != nil {
		return x.ThreadRoot
	}
	return 0
}

func (x *Message) GetSeq() uint64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *Message) GetSender() string {
	if x != nil {
		return x.Sender
	}
	return ""
}

func (x *Message) GetKind() MessageKind {
	if x != nil {
		return x.Kind
	}
	return MessageKind_MESSAGE_KIND_UNSPECIFIED
}

func (x *Message) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *Message) GetCid() string {
	if x != nil {
		return x.Cid
	}
	return ""
}

func (x *Message) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Message) GetVersion() uint32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *Message) GetDeleted() bool {
	if x != nil {
		return x.Deleted
	}
	return false
}

func (x *Message) GetEditedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.EditedAt
	}
	return nil
}

func (x *Message) GetHidden() bool {
	if x != nil {
		return x.Hidden
	}
	return false
}

func (x *Message) GetReactions() *ReactionSummary {
	if x != nil {
		return x.Reactions
	}
	return nil
}

type ReactionCount struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Emoji         string                 `protobuf:"bytes,1,opt,name=emoji,proto3" json:"emoji,omitempty"`
	Count         uint32                 `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReactionCount) Reset() {
	*x = ReactionCount{}
	mi := &file_chatim_v1_core_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReactionCount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReactionCount) ProtoMessage() {}

func (x *ReactionCount) ProtoReflect() protoreflect.Message {
	mi := &file_chatim_v1_core_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReactionCount.ProtoReflect.Descriptor instead.
func (*ReactionCount) Descriptor() ([]byte, []int) {
	return file_chatim_v1_core_proto_rawDescGZIP(), []int{2}
}

func (x *ReactionCount) GetEmoji() string {
	if x != nil {
		return x.Emoji
	}
	return ""
}

func (x *ReactionCount) GetCount() uint32 {
	if x != nil {
		return x.Count
	}
	return 0
}

type ReactionSummary struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Counts        []*ReactionCount       `protobuf:"bytes,1,rep,name=counts,proto3" json:"counts,omitempty"`
	Version       uint64                 `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReactionSummary) Reset() {
	*x = ReactionSummary{}
	mi := &file_chatim_v1_core_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReactionSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReactionSummary) ProtoMessage() {}

func (x *ReactionSummary) ProtoReflect() protoreflect.Message {
	mi := &file_chatim_v1_core_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReactionSummary.ProtoReflect.Descriptor instead.
func (*ReactionSummary) Descriptor() ([]byte, []int) {
	return file_chatim_v1_core_proto_rawDescGZIP(), []int{3}
}

func (x *ReactionSummary) GetCounts() []*ReactionCount {
	if x != nil {
		return x.Counts
	}
	return nil
}

func (x *ReactionSummary) GetVersion() uint64 {
	if x != nil {
		return x.Version
	}
	return 0
}

type Pin struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ThreadRoot    uint64                 `protobuf:"varint,1,opt,name=thread_root,json=threadRoot,proto3" json:"thread_root,omitempty"`
	Seq           uint64                 `protobuf:"varint,2,opt,name=seq,proto3" json:"seq,omitempty"`
	By            string                 `protobuf:"bytes,3,opt,name=by,proto3" json:"by,omitempty"`
	PinnedAt      *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=pinned_at,json=pinnedAt,proto3" json:"pinned_at,omitempty"`
	PinVersion    uint64                 `protobuf:"varint,5,opt,name=pin_version,json=pinVersion,proto3" json:"pin_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Pin) Reset() {
	*x = Pin{}
	mi := &file_chatim_v1_core_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Pin) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pin) ProtoMessage() {}

func (x *Pin) ProtoReflect() protoreflect.Message {
	mi := &file_chatim_v1_core_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pin.ProtoReflect.Descriptor instead.
func (*Pin) Descriptor() ([]byte, []int) {
	return file_chatim_v1_core_proto_rawDescGZIP(), []int{4}
}

func (x *Pin) GetThreadRoot() uint64 {
	if x != nil {
		return x.ThreadRoot
	}
	return 0
}

func (x *Pin) GetSeq() uint64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *Pin) GetBy() string {
	if x != nil {
		return x.By
	}
	return ""
}

func (x *Pin) GetPinnedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.PinnedAt
	}
	return nil
}

func (x *Pin) GetPinVersion() uint64 {
	if x != nil {
		return x.PinVersion
	}
	return 0
}

type MessageVersion struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       uint32                 `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	Kind          EditKind               `protobuf:"varint,2,opt,name=kind,proto3,enum=chatim.v1.EditKind" json:"kind,omitempty"`
	Text          string                 `protobuf:"bytes,3,opt,name=text,proto3" json:"text,omitempty"`
	By            string                 `protobuf:"bytes,4,opt,name=by,proto3" json:"by,omitempty"`
	At            *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=at,proto3" json:"at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessageVersion) Reset() {
	*x = MessageVersion{}
	mi := &file_chatim_v1_core_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageVersion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageVersion) ProtoMessage() {}

func (x *MessageVersion) ProtoReflect() protoreflect.Message {
	mi := &file_chatim_v1_core_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageVersion.ProtoReflect.Descriptor instead.
func (*MessageVersion) Descriptor() ([]byte, []int) {
	return file_chatim_v1_core_proto_rawDescGZIP(), []int{5}
}

func (x *MessageVersion) GetVersion() uint32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *MessageVersion) GetKind() EditKind {
	if x != nil {
		return x.Kind
	}
	return EditKind_EDIT_KIND_UNSPECIFIED
}

func (x *MessageVersion) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *MessageVersion) GetBy() string {
	if x != nil {
		return x.By
	}
	return ""
}

func (x *MessageVersion) GetAt() *timestamppb.Timestamp {
	if x != nil {
		return x.At
	}
	return nil
}

type CreateRoomRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          RoomType               `protobuf:"varint,1,opt,name=type,proto3,enum=chatim.v1.RoomType" json:"type,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Members       []string               `protobuf:"bytes,3,rep,name=members,proto3" json:"members,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRoomRequest) Reset() {
	*x = CreateRoomRequest{}
	mi := &file_chatim_v1_core_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRoomRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRoomRequest) ProtoMessage() {}

func (x *CreateRoomRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chatim_v1_core_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRoomRequest.ProtoReflect.Descriptor instead.
func (*CreateRoomRequest) Descriptor() ([]byte, []int) {
	return file_chatim_v1_core_proto_rawDescGZIP(), []int{6}
}

func (x *CreateRoomRequest) GetType() RoomType {
	if x != nil {
		return x.Type
	}
	return RoomType_ROOM_TYPE_UNSPECIFIED
}

func (x *CreateRoomRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateRoomRequest) GetMembers() []string {
	if x != nil {
		return x.Members
	}
	return nil
}

type CreateRoomResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Room          *Room                  `protobuf:"bytes,1,opt,name=room,proto3" json:"room,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRoomResponse) Reset() {
	*x = CreateRoomResponse{}
	mi := &file_chatim_v1_core_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRoomResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRoomResponse) ProtoMessage() {}

func (x *CreateRoomResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chatim_v1_core_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRoomResponse.ProtoReflect.Descriptor instead.
func (*CreateRoomResponse) Descriptor() ([]byte, []int) {
	return file_chatim_v1_core_proto_rawDescGZIP(), []int{7}
}

func (x *CreateRoomResponse) GetRoom() *Room {
	if x != nil {
		return x.Room
	}
	return nil
}

type SendMessageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        string                 `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	ThreadRoot    uint64                 `protobuf:"varint,2,opt,name=thread_root,json=threadRoot,proto3" json:"thread_root,omitempty"`
	Cid           string                 `protobuf:"bytes,3,opt,name=cid,proto3" json:"cid,omitempty"`
	Text          string                 `protobuf:"bytes,4,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendMessageRequest) Reset() {
	*x = SendMessageRequest{}
	mi := &file_chatim_v1_core_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMessageRequest) ProtoMessage() {}

func (x *SendMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chatim_v1_core_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMessageRequest.ProtoReflect.Descriptor instead.
func (*SendMessageRequest) Descriptor() ([]byte, []int) {
	return file_chatim_v1_core_proto_rawDescGZIP(), []int{8}
}

func (x *SendMessageRequest) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *SendMessageRequest) GetThreadRoot() uint64 {
	if x != nil {
		return x.ThreadRoot
	}
	return 0
}

func (x *SendMessageRequest) GetCid() string {
	if x != nil {
		return x.Cid
	}
	return ""
}

func (x *SendMessageRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type SendMessageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Seq           uint64                 `protobuf:"varint,1,opt,name=seq,proto3" json:"seq,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendMessageResponse) Reset() {
	*x = SendMessageResponse{}
	mi := &file_chatim_v1_core_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMessageResponse) ProtoMessage() {}

func (x *SendMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chatim_v1_core_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMessageResponse.ProtoReflect.Descriptor instead.
func (*SendMessageResponse) Descriptor() ([]byte, []int) {
	return file_chatim_v1_core_proto_rawDescGZIP(), []int{9}
}

func (x *SendMessageResponse) GetSeq() uint64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *SendMessageResponse) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type GetHistoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        string                 `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	ThreadRoot    uint64                 `protobuf:"varint,2,opt,name=thread_root,json=threadRoot,proto3" json:"thread_root,omitempty"`
	Anchor        HistoryAnchor          `protobuf:"varint,3,opt,name=anchor,proto3,enum=chatim.v1.HistoryAnchor" json:"anchor,omitempty"`
	Seq           uint64                 `protobuf:"varint,4,opt,name=seq,proto3" json:"seq,omitempty"`
	Limit         int32                  `protobuf:"varint,5,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetHistoryRequest) Reset() {
	*x = GetHistoryRequest{}
	mi := &file_chatim_v1_core_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHistoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHistoryRequest) ProtoMessage() {}

func (x *GetHistoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chatim_v1_core_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHistoryRequest.ProtoReflect.Descriptor instead.
func (*GetHistoryRequest) Descriptor() ([]byte, []int) {
	return file_chatim_v1_core_proto_rawDescGZIP(), []int{10}
}

func (x *GetHistoryRequest) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *GetHistoryRequest) GetThreadRoot() uint64 {
	if x != nil {
		return x.ThreadRoot
	}
	return 0
}

func (x *GetHistoryRequest) GetAnchor() HistoryAnchor {
	if x != nil {
		return x.Anchor
	}
	return HistoryAnchor_HISTORY_ANCHOR_UNSPECIFIED
}

func (x *GetHistoryRequest) GetSeq() uint64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *GetHistoryRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type GetHistoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Messages      []*Message             `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetHistoryResponse) Reset() {
	*x = GetHistoryResponse{}
	mi := &file_chatim_v1_core_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHistoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHistoryResponse) ProtoMessage() {}

func (x *GetHistoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chatim_v1_core_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHistoryResponse.ProtoReflect.Descriptor instead.
func (*GetHistoryResponse) Descriptor() ([]byte, []int) {
	return file_chatim_v1_core_proto_rawDescGZIP(), []int{11}
}

func (x *GetHistoryResponse) GetMessages() []*Message {
	if x != nil {
		return x.Messages
	}
	return nil
}

type EditMessageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        string                 `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	ThreadRoot    uint64                 `protobuf:"varint,2,opt,name=thread_root,json=threadRoot,proto3" json:"thread_root,omitempty"`
	Seq           uint64                 `protobuf:"varint,3,opt,name=seq,proto3" json:"seq,omitempty"`
	BaseVersion   uint32                 `protobuf:"varint,4,opt,name=base_version,json=baseVersion,proto3" json:"base_version,omitempty"`
	Text          string                 `protobuf:"bytes,5,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EditMessageRequest) Reset() {
	*x = EditMessageRequest{}
	mi := &file_chatim_v1_core_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EditMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EditMessageRequest) ProtoMessage() {}

func (x *EditMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chatim_v1_core_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EditMessageRequest.ProtoReflect.Descriptor instead.
func (*EditMessageRequest) Descriptor() ([]byte, []int) {
	return file_chatim_v1_core_proto_rawDescGZIP(), []int{12}
}

func (x *EditMessageRequest) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *EditMessageRequest) GetThreadRoot() uint64 {
	if x != nil {
		return x.ThreadRoot
	}
	return 0
}

func (x *EditMessageRequest) GetSeq() uint64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *EditMessageRequest) GetBaseVersion() uint32 {
	if x != nil {
		return x.BaseVersion
	}
	return 0
}

func (x *EditMessageRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type EditMessageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       *Message               `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EditMessageResponse) Reset() {
	*x = EditMessageResponse{}
	mi := &file_chatim_v1_core_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EditMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EditMessageResponse) ProtoMessage() {}

func (x *EditMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chatim_v1_core_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EditMessageResponse.ProtoReflect.Descriptor instead.
func (*EditMessageResponse) Descriptor() ([]byte, []int) {
	return file_chatim_v1_core_proto_rawDescGZIP(), []int{13}
}

func (x *EditMessageResponse) GetMessage() *Message {
	if x != nil {
		return x.Message
	}
	return nil
}

type DeleteMessageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        string                 `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	ThreadRoot    uint64                 `protobuf:"varint,2,opt,name=thread_root,json=threadRoot,proto3" json:"thread_root,omitempty"`
	Seq           uint64                 `protobuf:"varint,3,opt,name=seq,proto3" json:"seq,omitempty"`
	BaseVersion   uint32                 `protobuf:"varint,4,opt,name=base_version,json=baseVersion,proto3" json:"base_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteMessageRequest) Reset() {
	*x = DeleteMessageRequest{}
	mi := &file_chatim_v1_core_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteMessageRequest) ProtoMessage() {}

func (x *DeleteMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chatim_v1_core_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteMessageRequest.ProtoReflect.Descriptor instead.
func (*DeleteMessageRequest) Descriptor() ([]byte, []int) {
	return file_chatim_v1_core_proto_rawDescGZIP(), []int{14}
}

func (x *DeleteMessageRequest) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *DeleteMessageRequest) GetThreadRoot() uint64 {
	if x != nil {
		return x.ThreadRoot
	}
	return 0
}

func (x *DeleteMessageRequest) GetSeq() uint64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *DeleteMessageRequest) GetBaseVersion() uint32 {
	if x != nil {
		return x.BaseVersion
	}
	return 0
}

type DeleteMessageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       *Message               `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteMessageResponse) Reset() {
	*x = DeleteMessageResponse{}
	mi := &file_chatim_v1_core_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteMessageResponse) ProtoMessage() {}

func (x *DeleteMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chatim_v1_core_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteMessageResponse.ProtoReflect.Descriptor instead.
func (*DeleteMessageResponse) Descriptor() ([]byte, []int) {
	return file_chatim_v1_core_proto_rawDescGZIP(), []int{15}
}

func (x *DeleteMessageResponse) GetMessage() *Message {
	if x != nil {
		return x.Message
	}
	return nil
}

type HideMessageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        string                 `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	ThreadRoot    uint64                 `protobuf:"varint,2,opt,name=thread_root,json=threadRoot,proto3" json:"thread_root,omitempty"`
	Seq           uint64                 `protobuf:"varint,3,opt,name=seq,proto3" json:"seq,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HideMessageRequest) Reset() {
	*x = HideMessageRequest{}
	mi := &file_chatim_v1_core_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HideMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HideMessageRequest) ProtoMessage() {}

func (x *HideMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chatim_v1_core_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HideMessageRequest.ProtoReflect.Descriptor instead.
func (*HideMessageRequest) Descriptor() ([]byte, []int) {
	return file_chatim_v1_core_proto_rawDescGZIP(), []int{16}
}

func (x *HideMessageRequest) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *HideMessageRequest) GetThreadRoot() uint64 {
	if x != nil {
		return x.ThreadRoot
	}
	return 0
}

func (x *HideMessageRequest) GetSeq() uint64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

type HideMessageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HideMessageResponse) Reset() {
	*x = HideMessageResponse{}
	mi := &file_chatim_v1_core_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HideMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HideMessageResponse) ProtoMessage() {}

func (x *HideMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chatim_v1_core_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HideMessageResponse.ProtoReflect.Descriptor instead.
func (*HideMessageResponse) Descriptor() ([]byte, []int) {
	return file_chatim_v1_core_proto_rawDescGZIP(), []int{17}
}

type ClearHistoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        string                 `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	UpToSeq       uint64                 `protobuf:"varint,2,opt,name=up_to_seq,json=upToSeq,proto3" json:"up_to_seq,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClearHistoryRequest) Reset() {
	*x = ClearHistoryRequest{}
	mi := &file_chatim_v1_core_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClearHistoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClearHistoryRequest) ProtoMessage() {}

func (x *ClearHistoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chatim_v1_core_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClearHistoryRequest.ProtoReflect.Descriptor instead.
func (*ClearHistoryRequest) Descriptor() ([]byte, []int) {
	return file_chatim_v1_core_proto_rawDescGZIP(), []int{18}
}

func (x *ClearHistoryRequest) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *ClearHistoryRequest) GetUpToSeq() uint64 {
	if x != nil {
		return x.UpToSeq
	}
	return 0
}

type ClearHistoryResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ClearedBeforeSeq uint64                 `protobuf:"varint,1,opt,name=cleared_before_seq,json=clearedBeforeSeq,proto3" json:"cleared_before_seq,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ClearHistoryResponse) Reset() {
	*x = ClearHistoryResponse{}
	mi := &file_chatim_v1_core_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClearHistoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClearHistoryResponse) ProtoMessage() {}

func (x *ClearHistoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chatim_v1_core_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClearHistoryResponse.ProtoReflect.Descriptor instead.
func (*ClearHistoryResponse) Descriptor() ([]byte, []int) {
	return file_chatim_v1_core_proto_rawDescGZIP(), []int{19}
}

func (x *ClearHistoryResponse) GetClearedBeforeSeq() uint64 {
	if x != nil {
		return x.ClearedBeforeSeq
	}
	return 0
}

type GetEditHistoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        string                 `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	ThreadRoot    uint64                 `protobuf:"varint,2,opt,name=thread_root,json=threadRoot,proto3" json:"thread_root,omitempty"`
	Seq           uint64                 `protobuf:"varint,3,opt,name=seq,proto3" json:"seq,omitempty"`
	AfterVersion  uint32                 `protobuf:"varint,4,opt,name=after_version,json=afterVersion,proto3" json:"after_version,omitempty"`
	Limit         uint32                 `protobuf:"varint,5,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEditHistoryRequest) Reset() {
	*x = GetEditHistoryRequest{}
	mi := &file_chatim_v1_core_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEditHistoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEditHistoryRequest) ProtoMessage() {}

func (x *GetEditHistoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chatim_v1_core_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEditHistoryRequest.ProtoReflect.Descriptor instead.
func (*GetEditHistoryRequest) Descriptor() ([]byte, []int) {
	return file_chatim_v1_core_proto_rawDescGZIP(), []int{20}
}

func (x *GetEditHistoryRequest) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *GetEditHistoryRequest) GetThreadRoot() uint64 {
	if x != nil {
		return x.ThreadRoot
	}
	return 0
}

func (x *GetEditHistoryRequest) GetSeq() uint64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *GetEditHistoryRequest) GetAfterVersion() uint32 {
	if x != nil {
		return x.AfterVersion
	}
	return 0
}

func (x *GetEditHistoryRequest) GetLimit() uint32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type GetEditHistoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Versions      []*MessageVersion      `protobuf:"bytes,1,rep,name=versions,proto3" json:"versions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEditHistoryResponse) Reset() {
	*x = GetEditHistoryResponse{}
	mi := &file_chatim_v1_core_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEditHistoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEditHistoryResponse) ProtoMessage() {}

func (x *GetEditHistoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chatim_v1_core_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEditHistoryResponse.ProtoReflect.Descriptor instead.
func (*GetEditHistoryResponse) Descriptor() ([]byte, []int) {
	return file_chatim_v1_core_proto_rawDescGZIP(), []int{21}
}

func (x *GetEditHistoryResponse) GetVersions() []*MessageVersion {
	if x != nil {
		return x.Versions
	}
	return nil
}

type ReactMessageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        string                 `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	ThreadRoot    uint64                 `protobuf:"varint,2,opt,name=thread_root,json=threadRoot,proto3" json:"thread_root,omitempty"`
	Seq           uint64                 `protobuf:"varint,3,opt,name=seq,proto3" json:"seq,omitempty"`
	Emoji         string                 `protobuf:"bytes,4,opt,name=emoji,proto3" json:"emoji,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReactMessageRequest) Reset() {
	*x = ReactMessageRequest{}
	mi := &file_chatim_v1_core_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReactMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReactMessageRequest) ProtoMessage() {}

func (x *ReactMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chatim_v1_core_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReactMessageRequest.ProtoReflect.Descriptor instead.
func (*ReactMessageRequest) Descriptor() ([]byte, []int) {
	return file_chatim_v1_core_proto_rawDescGZIP(), []int{22}
}

func (x *ReactMessageRequest) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *ReactMessageRequest) GetThreadRoot() uint64 {
	if x != nil {
		return x.ThreadRoot
	}
	return 0
}

func (x *ReactMessageRequest) GetSeq() uint64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *ReactMessageRequest) GetEmoji() string {
	if x != nil {
		return x.Emoji
	}
	return ""
}

type ReactMessageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Change        uint32                 `protobuf:"varint,1,opt,name=change,proto3" json:"change,omitempty"`
	Reactions     *ReactionSummary       `protobuf:"bytes,2,opt,name=reactions,proto3" json:"reactions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReactMessageResponse) Reset() {
	*x = ReactMessageResponse{}
	mi := &file_chatim_v1_core_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReactMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReactMessageResponse) ProtoMessage() {}

func (x *ReactMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chatim_v1_core_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReactMessageResponse.ProtoReflect.Descriptor instead.
func (*ReactMessageResponse) Descriptor() ([]byte, []int) {
	return file_chatim_v1_core_proto_rawDescGZIP(), []int{23}
}

func (x *ReactMessageResponse) GetChange() uint32 {
	if x != nil {
		return x.Change
	}
	return 0
}

func (x *ReactMessageResponse) GetReactions() *ReactionSummary {
	if x != nil {
		return x.Reactions
	}
	return nil
}

type PinMessageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        string                 `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	ThreadRoot    uint64                 `protobuf:"varint,2,opt,name=thread_root,json=threadRoot,proto3" json:"thread_root,omitempty"`
	Seq           uint64                 `protobuf:"varint,3,opt,name=seq,proto3" json:"seq,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PinMessageRequest) Reset() {
	*x = PinMessageRequest{}
	mi := &file_chatim_v1_core_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PinMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PinMessageRequest) ProtoMessage() {}

func (x *PinMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chatim_v1_core_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PinMessageRequest.ProtoReflect.Descriptor instead.
func (*PinMessageRequest) Descriptor() ([]byte, []int) {
	return file_chatim_v1_core_proto_rawDescGZIP(), []int{24}
}

func (x *PinMessageRequest) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *PinMessageRequest) GetThreadRoot() uint64 {
	if x != nil {
		return x.ThreadRoot
	}
	return 0
}

func (x *PinMessageRequest) GetSeq() uint64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

type PinMessageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PinVersion    uint64                 `protobuf:"varint,1,opt,name=pin_version,json=pinVersion,proto3" json:"pin_version,omitempty"`
	Pins          []*Pin                 `protobuf:"bytes,2,rep,name=pins,proto3" json:"pins,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PinMessageResponse) Reset() {
	*x = PinMessageResponse{}
	mi := &file_chatim_v1_core_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PinMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PinMessageResponse) ProtoMessage() {}

func (x *PinMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chatim_v1_core_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PinMessageResponse.ProtoReflect.Descriptor instead.
func (*PinMessageResponse) Descriptor() ([]byte, []int) {
	return file_chatim_v1_core_proto_rawDescGZIP(), []int{25}
}

func (x *PinMessageResponse) GetPinVersion() uint64 {
	if x != nil {
		return x.PinVersion
	}
	return 0
}

func (x *PinMessageResponse) GetPins() []*Pin {
	if x != nil {
		return x.Pins
	}
	return nil
}

type UnpinMessageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        string                 `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	ThreadRoot    uint64                 `protobuf:"varint,2,opt,name=thread_root,json=threadRoot,proto3" json:"thread_root,omitempty"`
	Seq           uint64                 `protobuf:"varint,3,opt,name=seq,proto3" json:"seq,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnpinMessageRequest) Reset() {
	*x = UnpinMessageRequest{}
	mi := &file_chatim_v1_core_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnpinMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnpinMessageRequest) ProtoMessage() {}

func (x *UnpinMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chatim_v1_core_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnpinMessageRequest.ProtoReflect.Descriptor instead.
func (*UnpinMessageRequest) Descriptor() ([]byte, []int) {
	return file_chatim_v1_core_proto_rawDescGZIP(), []int{26}
}

func (x *UnpinMessageRequest) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *UnpinMessageRequest) GetThreadRoot() uint64 {
	if x != nil {
		return x.ThreadRoot
	}
	return 0
}

func (x *UnpinMessageRequest) GetSeq() uint64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

type UnpinMessageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PinVersion    uint64                 `protobuf:"varint,1,opt,name=pin_version,json=pinVersion,proto3" json:"pin_version,omitempty"`
	Pins          []*Pin                 `protobuf:"bytes,2,rep,name=pins,proto3" json:"pins,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnpinMessageResponse) Reset() {
	*x = UnpinMessageResponse{}
	mi := &file_chatim_v1_core_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnpinMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnpinMessageResponse) ProtoMessage() {}

func (x *UnpinMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chatim_v1_core_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnpinMessageResponse.ProtoReflect.Descriptor instead.
func (*UnpinMessageResponse) Descriptor() ([]byte, []int) {
	return file_chatim_v1_core_proto_rawDescGZIP(), []int{27}
}

func (x *UnpinMessageResponse) GetPinVersion() uint64 {
	if x != nil {
		return x.PinVersion
	}
	return 0
}

func (x *UnpinMessageResponse) GetPins() []*Pin {
	if x != nil {
		return x.Pins
	}
	return nil
}

var File_chatim_v1_core_proto protoreflect.FileDescriptor

const file_chatim_v1_core_proto_rawDesc = "" +
	"\n" +
	"\x14chatim/v1/core.proto\x12\tchatim.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xe8\x01\n" +
	"\x04Room\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06tenant\x18\x02 \x01(\tR\x06tenant\x12'\n" +
	"\x04type\x18\x03 \x01(\x0e2\x13.chatim.v1.RoomTypeR\x04type\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"created_by\x18\x05 \x01(\tR\tcreatedBy\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12!\n" +
	"\fmember_count\x18\a \x01(\x05R\vmemberCount\"\xc4\x03\n" +
	"\aMessage\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\tR\x06roomId\x12\x1f\n" +
	"\vthread_root\x18\x02 \x01(\x04R\n" +
	"threadRoot\x12\x10\n" +
	"\x03seq\x18\x03 \x01(\x04R\x03seq\x12\x16\n" +
	"\x06sender\x18\x05 \x01(\tR\x06sender\x12*\n" +
	"\x04kind\x18\x06 \x01(\x0e2\x16.chatim.v1.MessageKindR\x04kind\x12\x12\n" +
	"\x04text\x18\a \x01(\tR\x04text\x12\x10\n" +
	"\x03cid\x18\b \x01(\tR\x03cid\x129\n" +
	"\n" +
	"created_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12\x18\n" +
	"\aversion\x18\n" +
	" \x01(\rR\aversion\x12\x18\n" +
	"\adeleted\x18\v \x01(\bR\adeleted\x127\n" +
	"\tedited_at\x18\f \x01(\v2\x1a.google.protobuf.TimestampR\beditedAt\x12\x16\n" +
	"\x06hidden\x18\r \x01(\bR\x06hidden\x128\n" +
	"\treactions\x18\x0e \x01(\v2\x1a.chatim.v1.ReactionSummaryR\treactionsJ\x04\b\x04\x10\x05R\x03pts\";\n" +
	"\rReactionCount\x12\x14\n" +
	"\x05emoji\x18\x01 \x01(\tR\x05emoji\x12\x14\n" +
	"\x05count\x18\x02 \x01(\rR\x05count\"]\n" +
	"\x0fReactionSummary\x120\n" +
	"\x06counts\x18\x01 \x03(\v2\x18.chatim.v1.ReactionCountR\x06counts\x12\x18\n" +
	"\aversion\x18\x02 \x01(\x04R\aversion\"\xa2\x01\n" +
	"\x03Pin\x12\x1f\n" +
	"\vthread_root\x18\x01 \x01(\x04R\n" +
	"threadRoot\x12\x10\n" +
	"\x03seq\x18\x02 \x01(\x04R\x03seq\x12\x0e\n" +
	"\x02by\x18\x03 \x01(\tR\x02by\x127\n" +
	"\tpinned_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\bpinnedAt\x12\x1f\n" +
	"\vpin_version\x18\x05 \x01(\x04R\n" +
	"pinVersion\"\xa3\x01\n" +
	"\x0eMessageVersion\x12\x18\n" +
	"\aversion\x18\x01 \x01(\rR\aversion\x12'\n" +
	"\x04kind\x18\x02 \x01(\x0e2\x13.chatim.v1.EditKindR\x04kind\x12\x12\n" +
	"\x04text\x18\x03 \x01(\tR\x04text\x12\x0e\n" +
	"\x02by\x18\x04 \x01(\tR\x02by\x12*\n" +
	"\x02at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\x02at\"j\n" +
	"\x11CreateRoomRequest\x12'\n" +
	"\x04type\x18\x01 \x01(\x0e2\x13.chatim.v1.RoomTypeR\x04type\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x18\n" +
	"\amembers\x18\x03 \x03(\tR\amembers\"9\n" +
	"\x12CreateRoomResponse\x12#\n" +
	"\x04room\x18\x01 \x01(\v2\x0f.chatim.v1.RoomR\x04room\"t\n" +
	"\x12SendMessageRequest\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\tR\x06roomId\x12\x1f\n" +
	"\vthread_root\x18\x02 \x01(\x04R\n" +
	"threadRoot\x12\x10\n" +
	"\x03cid\x18\x03 \x01(\tR\x03cid\x12\x12\n" +
	"\x04text\x18\x04 \x01(\tR\x04text\"m\n" +
	"\x13SendMessageResponse\x12\x10\n" +
	"\x03seq\x18\x01 \x01(\x04R\x03seq\x129\n" +
	"\n" +
	"created_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAtJ\x04\b\x02\x10\x03R\x03pts\"\xa7\x01\n" +
	"\x11GetHistoryRequest\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\tR\x06roomId\x12\x1f\n" +
	"\vthread_root\x18\x02 \x01(\x04R\n" +
	"threadRoot\x120\n" +
	"\x06anchor\x18\x03 \x01(\x0e2\x18.chatim.v1.HistoryAnchorR\x06anchor\x12\x10\n" +
	"\x03seq\x18\x04 \x01(\x04R\x03seq\x12\x14\n" +
	"\x05limit\x18\x05 \x01(\x05R\x05limit\"D\n" +
	"\x12GetHistoryResponse\x12.\n" +
	"\bmessages\x18\x01 \x03(\v2\x12.chatim.v1.MessageR\bmessages\"\x97\x01\n" +
	"\x12EditMessageRequest\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\tR\x06roomId\x12\x1f\n" +
	"\vthread_root\x18\x02 \x01(\x04R\n" +
	"threadRoot\x12\x10\n" +
	"\x03seq\x18\x03 \x01(\x04R\x03seq\x12!\n" +
	"\fbase_version\x18\x04 \x01(\rR\vbaseVersion\x12\x12\n" +
	"\x04text\x18\x05 \x01(\tR\x04text\"C\n" +
	"\x13EditMessageResponse\x12,\n" +
	"\amessage\x18\x01 \x01(\v2\x12.chatim.v1.MessageR\amessage\"\x85\x01\n" +
	"\x14DeleteMessageRequest\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\tR\x06roomId\x12\x1f\n" +
	"\vthread_root\x18\x02 \x01(\x04R\n" +
	"threadRoot\x12\x10\n" +
	"\x03seq\x18\x03 \x01(\x04R\x03seq\x12!\n" +
	"\fbase_version\x18\x04 \x01(\rR\vbaseVersion\"E\n" +
	"\x15DeleteMessageResponse\x12,\n" +
	"\amessage\x18\x01 \x01(\v2\x12.chatim.v1.MessageR\amessage\"`\n" +
	"\x12HideMessageRequest\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\tR\x06roomId\x12\x1f\n" +
	"\vthread_root\x18\x02 \x01(\x04R\n" +
	"threadRoot\x12\x10\n" +
	"\x03seq\x18\x03 \x01(\x04R\x03seq\"\x15\n" +
	"\x13HideMessageResponse\"J\n" +
	"\x13ClearHistoryRequest\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\tR\x06roomId\x12\x1a\n" +
	"\tup_to_seq\x18\x02 \x01(\x04R\aupToSeq\"D\n" +
	"\x14ClearHistoryResponse\x12,\n" +
	"\x12cleared_before_seq\x18\x01 \x01(\x04R\x10clearedBeforeSeq\"\x9e\x01\n" +
	"\x15GetEditHistoryRequest\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\tR\x06roomId\x12\x1f\n" +
	"\vthread_root\x18\x02 \x01(\x04R\n" +
	"threadRoot\x12\x10\n" +
	"\x03seq\x18\x03 \x01(\x04R\x03seq\x12#\n" +
	"\rafter_version\x18\x04 \x01(\rR\fafterVersion\x12\x14\n" +
	"\x05limit\x18\x05 \x01(\rR\x05limit\"O\n" +
	"\x16GetEditHistoryResponse\x125\n" +
	"\bversions\x18\x01 \x03(\v2\x19.chatim.v1.MessageVersionR\bversions\"w\n" +
	"\x13ReactMessageRequest\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\tR\x06roomId\x12\x1f\n" +
	"\vthread_root\x18\x02 \x01(\x04R\n" +
	"threadRoot\x12\x10\n" +
	"\x03seq\x18\x03 \x01(\x04R\x03seq\x12\x14\n" +
	"\x05emoji\x18\x04 \x01(\tR\x05emoji\"h\n" +
	"\x14ReactMessageResponse\x12\x16\n" +
	"\x06change\x18\x01 \x01(\rR\x06change\x128\n" +
	"\treactions\x18\x02 \x01(\v2\x1a.chatim.v1.ReactionSummaryR\treactions\"_\n" +
	"\x11PinMessageRequest\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\tR\x06roomId\x12\x1f\n" +
	"\vthread_root\x18\x02 \x01(\x04R\n" +
	"threadRoot\x12\x10\n" +
	"\x03seq\x18\x03 \x01(\x04R\x03seq\"Y\n" +
	"\x12PinMessageResponse\x12\x1f\n" +
	"\vpin_version\x18\x01 \x01(\x04R\n" +
	"pinVersion\x12\"\n" +
	"\x04pins\x18\x02 \x03(\v2\x0e.chatim.v1.PinR\x04pins\"a\n" +
	"\x13UnpinMessageRequest\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\tR\x06roomId\x12\x1f\n" +
	"\vthread_root\x18\x02 \x01(\x04R\n" +
	"threadRoot\x12\x10\n" +
	"\x03seq\x18\x03 \x01(\x04R\x03seq\"[\n" +
	"\x14UnpinMessageResponse\x12\x1f\n" +
	"\vpin_version\x18\x01 \x01(\x04R\n" +
	"pinVersion\x12\"\n" +
	"\x04pins\x18\x02 \x03(\v2\x0e.chatim.v1.PinR\x04pins*L\n" +
	"\bRoomType\x12\x19\n" +
	"\x15ROOM_TYPE_UNSPECIFIED\x10\x00\x12\x10\n" +
	"\fROOM_TYPE_DM\x10\x01\x12\x13\n" +
	"\x0fROOM_TYPE_GROUP\x10\x02*B\n" +
	"\vMessageKind\x12\x1c\n" +
	"\x18MESSAGE_KIND_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11MESSAGE_KIND_TEXT\x10\x01*\x9a\x01\n" +
	"\rHistoryAnchor\x12\x1e\n" +
	"\x1aHISTORY_ANCHOR_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15HISTORY_ANCHOR_LATEST\x10\x01\x12\x19\n" +
	"\x15HISTORY_ANCHOR_OLDEST\x10\x02\x12\x19\n" +
	"\x15HISTORY_ANCHOR_BEFORE\x10\x03\x12\x18\n" +
	"\x14HISTORY_ANCHOR_AFTER\x10\x04*g\n" +
	"\bEditKind\x12\x19\n" +
	"\x15EDIT_KIND_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12EDIT_KIND_ORIGINAL\x10\x01\x12\x12\n" +
	"\x0eEDIT_KIND_TEXT\x10\x02\x12\x14\n" +
	"\x10EDIT_KIND_DELETE\x10\x032\xf6\x06\n" +
	"\vCoreService\x12I\n" +
	"\n" +
	"CreateRoom\x12\x1c.chatim.v1.CreateRoomRequest\x1a\x1d.chatim.v1.CreateRoomResponse\x12L\n" +
	"\vSendMessage\x12\x1d.chatim.v1.SendMessageRequest\x1a\x1e.chatim.v1.SendMessageResponse\x12I\n" +
	"\n" +
	"GetHistory\x12\x1c.chatim.v1.GetHistoryRequest\x1a\x1d.chatim.v1.GetHistoryResponse\x12L\n" +
	"\vEditMessage\x12\x1d.chatim.v1.EditMessageRequest\x1a\x1e.chatim.v1.EditMessageResponse\x12R\n" +
	"\rDeleteMessage\x12\x1f.chatim.v1.DeleteMessageRequest\x1a .chatim.v1.DeleteMessageResponse\x12L\n" +
	"\vHideMessage\x12\x1d.chatim.v1.HideMessageRequest\x1a\x1e.chatim.v1.HideMessageResponse\x12O\n" +
	"\fClearHistory\x12\x1e.chatim.v1.ClearHistoryRequest\x1a\x1f.chatim.v1.ClearHistoryResponse\x12U\n" +
	"\x0eGetEditHistory\x12 .chatim.v1.GetEditHistoryRequest\x1a!.chatim.v1.GetEditHistoryResponse\x12O\n" +
	"\fReactMessage\x12\x1e.chatim.v1.ReactMessageRequest\x1a\x1f.chatim.v1.ReactMessageResponse\x12I\n" +
	"\n" +
	"PinMessage\x12\x1c.chatim.v1.PinMessageRequest\x1a\x1d.chatim.v1.PinMessageResponse\x12O\n" +
	"\fUnpinMessage\x12\x1e.chatim.v1.UnpinMessageRequest\x1a\x1f.chatim.v1.UnpinMessageResponseB\x9a\x01\n" +
	"\rcom.chatim.v1B\tCoreProtoP\x01Z9github.com/ivannguyendev/chatim/pkg/pb/chatim/v1;chatimv1\xa2\x02\x03CXX\xaa\x02\tChatim.V1\xca\x02\tChatim\\V1\xe2\x02\x15Chatim\\V1\\GPBMetadata\xea\x02\n" +
	"Chatim::V1b\x06proto3"

var (
	file_chatim_v1_core_proto_rawDescOnce sync.Once
	file_chatim_v1_core_proto_rawDescData []byte
)

func file_chatim_v1_core_proto_rawDescGZIP() []byte {
	file_chatim_v1_core_proto_rawDescOnce.Do(func() {
		file_chatim_v1_core_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_chatim_v1_core_proto_rawDesc), len(file_chatim_v1_core_proto_rawDesc)))
	})
	return file_chatim_v1_core_proto_rawDescData
}

var file_chatim_v1_core_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_chatim_v1_core_proto_msgTypes = make([]protoimpl.MessageInfo, 28)
var file_chatim_v1_core_proto_goTypes = []any{
	(RoomType)(0),                  // 0: chatim.v1.RoomType
	(MessageKind)(0),               // 1: chatim.v1.MessageKind
	(HistoryAnchor)(0),             // 2: chatim.v1.HistoryAnchor
	(EditKind)(0),                  // 3: chatim.v1.EditKind
	(*Room)(nil),                   // 4: chatim.v1.Room
	(*Message)(nil),                // 5: chatim.v1.Message
	(*ReactionCount)(nil),          // 6: chatim.v1.ReactionCount
	(*ReactionSummary)(nil),        // 7: chatim.v1.ReactionSummary
	(*Pin)(nil),                    // 8: chatim.v1.Pin
	(*MessageVersion)(nil),         // 9: chatim.v1.MessageVersion
	(*CreateRoomRequest)(nil),      // 10: chatim.v1.CreateRoomRequest
	(*CreateRoomResponse)(nil),     // 11: chatim.v1.CreateRoomResponse
	(*SendMessageRequest)(nil),     // 12: chatim.v1.SendMessageRequest
	(*SendMessageResponse)(nil),    // 13: chatim.v1.SendMessageResponse
	(*GetHistoryRequest)(nil),      // 14: chatim.v1.GetHistoryRequest
	(*GetHistoryResponse)(nil),     // 15: chatim.v1.GetHistoryResponse
	(*EditMessageRequest)(nil),     // 16: chatim.v1.EditMessageRequest
	(*EditMessageResponse)(nil),    // 17: chatim.v1.EditMessageResponse
	(*DeleteMessageRequest)(nil),   // 18: chatim.v1.DeleteMessageRequest
	(*DeleteMessageResponse)(nil),  // 19: chatim.v1.DeleteMessageResponse
	(*HideMessageRequest)(nil),     // 20: chatim.v1.HideMessageRequest
	(*HideMessageResponse)(nil),    // 21: chatim.v1.HideMessageResponse
	(*ClearHistoryRequest)(nil),    // 22: chatim.v1.ClearHistoryRequest
	(*ClearHistoryResponse)(nil),   // 23: chatim.v1.ClearHistoryResponse
	(*GetEditHistoryRequest)(nil),  // 24: chatim.v1.GetEditHistoryRequest
	(*GetEditHistoryResponse)(nil), // 25: chatim.v1.GetEditHistoryResponse
	(*ReactMessageRequest)(nil),    // 26: chatim.v1.ReactMessageRequest
	(*ReactMessageResponse)(nil),   // 27: chatim.v1.ReactMessageResponse
	(*PinMessageRequest)(nil),      // 28: chatim.v1.PinMessageRequest
	(*PinMessageResponse)(nil),     // 29: chatim.v1.PinMessageResponse
	(*UnpinMessageRequest)(nil),    // 30: chatim.v1.UnpinMessageRequest
	(*UnpinMessageResponse)(nil),   // 31: chatim.v1.UnpinMessageResponse
	(*timestamppb.Timestamp)(nil),  // 32: google.protobuf.Timestamp
}
var file_chatim_v1_core_proto_depIdxs = []int32{
	0,  // 0: chatim.v1.Room.type:type_name -> chatim.v1.RoomType
	32, // 1: chatim.v1.Room.created_at:type_name -> google.protobuf.Timestamp
	1,  // 2: chatim.v1.Message.kind:type_name -> chatim.v1.MessageKind
	32, // 3: chatim.v1.Message.created_at:type_name -> google.protobuf.Timestamp
	32, // 4: chatim.v1.Message.edited_at:type_name -> google.protobuf.Timestamp
	7,  // 5: chatim.v1.Message.reactions:type_name -> chatim.v1.ReactionSummary
	6,  // 6: chatim.v1.ReactionSummary.counts:type_name -> chatim.v1.ReactionCount
	32, // 7: chatim.v1.Pin.pinned_at:type_name -> google.protobuf.Timestamp
	3,  // 8: chatim.v1.MessageVersion.kind:type_name -> chatim.v1.EditKind
	32, // 9: chatim.v1.MessageVersion.at:type_name -> google.protobuf.Timestamp
	0,  // 10: chatim.v1.CreateRoomRequest.type:type_name -> chatim.v1.RoomType
	4,  // 11: chatim.v1.CreateRoomResponse.room:type_name -> chatim.v1.Room
	32, // 12: chatim.v1.SendMessageResponse.created_at:type_name -> google.protobuf.Timestamp
	2,  // 13: chatim.v1.GetHistoryRequest.anchor:type_name -> chatim.v1.HistoryAnchor
	5,  // 14: chatim.v1.GetHistoryResponse.messages:type_name -> chatim.v1.Message
	5,  // 15: chatim.v1.EditMessageResponse.message:type_name -> chatim.v1.Message
	5,  // 16: chatim.v1.DeleteMessageResponse.message:type_name -> chatim.v1.Message
	9,  // 17: chatim.v1.GetEditHistoryResponse.versions:type_name -> chatim.v1.MessageVersion
	7,  // 18: chatim.v1.ReactMessageResponse.reactions:type_name -> chatim.v1.ReactionSummary
	8,  // 19: chatim.v1.PinMessageResponse.pins:type_name -> chatim.v1.Pin
	8,  // 20: chatim.v1.UnpinMessageResponse.pins:type_name -> chatim.v1.Pin
	10, // 21: chatim.v1.CoreService.CreateRoom:input_type -> chatim.v1.CreateRoomRequest
	12, // 22: chatim.v1.CoreService.SendMessage:input_type -> chatim.v1.SendMessageRequest
	14, // 23: chatim.v1.CoreService.GetHistory:input_type -> chatim.v1.GetHistoryRequest
	16, // 24: chatim.v1.CoreService.EditMessage:input_type -> chatim.v1.EditMessageRequest
	18, // 25: chatim.v1.CoreService.DeleteMessage:input_type -> chatim.v1.DeleteMessageRequest
	20, // 26: chatim.v1.CoreService.HideMessage:input_type -> chatim.v1.HideMessageRequest
	22, // 27: chatim.v1.CoreService.ClearHistory:input_type -> chatim.v1.ClearHistoryRequest
	24, // 28: chatim.v1.CoreService.GetEditHistory:input_type -> chatim.v1.GetEditHistoryRequest
	26, // 29: chatim.v1.CoreService.ReactMessage:input_type -> chatim.v1.ReactMessageRequest
	28, // 30: chatim.v1.CoreService.PinMessage:input_type -> chatim.v1.PinMessageRequest
	30, // 31: chatim.v1.CoreService.UnpinMessage:input_type -> chatim.v1.UnpinMessageRequest
	11, // 32: chatim.v1.CoreService.CreateRoom:output_type -> chatim.v1.CreateRoomResponse
	13, // 33: chatim.v1.CoreService.SendMessage:output_type -> chatim.v1.SendMessageResponse
	15, // 34: chatim.v1.CoreService.GetHistory:output_type -> chatim.v1.GetHistoryResponse
	17, // 35: chatim.v1.CoreService.EditMessage:output_type -> chatim.v1.EditMessageResponse
	19, // 36: chatim.v1.CoreService.DeleteMessage:output_type -> chatim.v1.DeleteMessageResponse
	21, // 37: chatim.v1.CoreService.HideMessage:output_type -> chatim.v1.HideMessageResponse
	23, // 38: chatim.v1.CoreService.ClearHistory:output_type -> chatim.v1.ClearHistoryResponse
	25, // 39: chatim.v1.CoreService.GetEditHistory:output_type -> chatim.v1.GetEditHistoryResponse
	27, // 40: chatim.v1.CoreService.ReactMessage:output_type -> chatim.v1.ReactMessageResponse
	29, // 41: chatim.v1.CoreService.PinMessage:output_type -> chatim.v1.PinMessageResponse
	31, // 42: chatim.v1.CoreService.UnpinMessage:output_type -> chatim.v1.UnpinMessageResponse
	32, // [32:43] is the sub-list for method output_type
	21, // [21:32] is the sub-list for method input_type
	21, // [21:21] is the sub-list for extension type_name
	21, // [21:21] is the sub-list for extension extendee
	0,  // [0:21] is the sub-list for field type_name
}

func init() { file_chatim_v1_core_proto_init() }
func file_chatim_v1_core_proto_init() {
	if File_chatim_v1_core_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_chatim_v1_core_proto_rawDesc), len(file_chatim_v1_core_proto_rawDesc)),
			NumEnums:      4,
			NumMessages:   28,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_chatim_v1_core_proto_goTypes,
		DependencyIndexes: file_chatim_v1_core_proto_depIdxs,
		EnumInfos:         file_chatim_v1_core_proto_enumTypes,
		MessageInfos:      file_chatim_v1_core_proto_msgTypes,
	}.Build()
	File_chatim_v1_core_proto = out.File
	file_chatim_v1_core_proto_goTypes = nil
	file_chatim_v1_core_proto_depIdxs = nil
}
