// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: chatim/v1/core.proto

package chatimv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RoomType int32

const (
	RoomType_ROOM_TYPE_UNSPECIFIED RoomType = 0
	RoomType_ROOM_TYPE_DM          RoomType = 1
	RoomType_ROOM_TYPE_GROUP       RoomType = 2
)

// Enum value maps for RoomType.
var (
	RoomType_name = map[int32]string{
		0: "ROOM_TYPE_UNSPECIFIED",
		1: "ROOM_TYPE_DM",
		2: "ROOM_TYPE_GROUP",
	}
	RoomType_value = map[string]int32{
		"ROOM_TYPE_UNSPECIFIED": 0,
		"ROOM_TYPE_DM":          1,
		"ROOM_TYPE_GROUP":       2,
	}
)

func (x RoomType) Enum() *RoomType {
	p := new(RoomType)
	*p = x
	return p
}

func (x RoomType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RoomType) Descriptor() protoreflect.EnumDescriptor {
	return file_chatim_v1_core_proto_enumTypes[0].Descriptor()
}

func (RoomType) Type() protoreflect.EnumType {
	return &file_chatim_v1_core_proto_enumTypes[0]
}

func (x RoomType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RoomType.Descriptor instead.
func (RoomType) EnumDescriptor() ([]byte, []int) {
	return file_chatim_v1_core_proto_rawDescGZIP(), []int{0}
}

type MessageKind int32

const (
	MessageKind_MESSAGE_KIND_UNSPECIFIED MessageKind = 0
	MessageKind_MESSAGE_KIND_TEXT        MessageKind = 1
)

// Enum value maps for MessageKind.
var (
	MessageKind_name = map[int32]string{
		0: "MESSAGE_KIND_UNSPECIFIED",
		1: "MESSAGE_KIND_TEXT",
	}
	MessageKind_value = map[string]int32{
		"MESSAGE_KIND_UNSPECIFIED": 0,
		"MESSAGE_KIND_TEXT":        1,
	}
)

func (x MessageKind) Enum() *MessageKind {
	p := new(MessageKind)
	*p = x
	return p
}

func (x MessageKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MessageKind) Descriptor() protoreflect.EnumDescriptor {
	return file_chatim_v1_core_proto_enumTypes[1].Descriptor()
}

func (MessageKind) Type() protoreflect.EnumType {
	return &file_chatim_v1_core_proto_enumTypes[1]
}

func (x MessageKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MessageKind.Descriptor instead.
func (MessageKind) EnumDescriptor() ([]byte, []int) {
	return file_chatim_v1_core_proto_rawDescGZIP(), []int{1}
}

type HistoryAnchor int32

const (
	HistoryAnchor_HISTORY_ANCHOR_UNSPECIFIED HistoryAnchor = 0
	HistoryAnchor_HISTORY_ANCHOR_LATEST      HistoryAnchor = 1
	HistoryAnchor_HISTORY_ANCHOR_OLDEST      HistoryAnchor = 2
	HistoryAnchor_HISTORY_ANCHOR_BEFORE      HistoryAnchor = 3
	HistoryAnchor_HISTORY_ANCHOR_AFTER       HistoryAnchor = 4
)

// Enum value maps for HistoryAnchor.
var (
	HistoryAnchor_name = map[int32]string{
		0: "HISTORY_ANCHOR_UNSPECIFIED",
		1: "HISTORY_ANCHOR_LATEST",
		2: "HISTORY_ANCHOR_OLDEST",
		3: "HISTORY_ANCHOR_BEFORE",
		4: "HISTORY_ANCHOR_AFTER",
	}
	HistoryAnchor_value = map[string]int32{
		"HISTORY_ANCHOR_UNSPECIFIED": 0,
		"HISTORY_ANCHOR_LATEST":      1,
		"HISTORY_ANCHOR_OLDEST":      2,
		"HISTORY_ANCHOR_BEFORE":      3,
		"HISTORY_ANCHOR_AFTER":       4,
	}
)

func (x HistoryAnchor) Enum() *HistoryAnchor {
	p := new(HistoryAnchor)
	*p = x
	return p
}

func (x HistoryAnchor) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (HistoryAnchor) Descriptor() protoreflect.EnumDescriptor {
	return file_chatim_v1_core_proto_enumTypes[2].Descriptor()
}

func (HistoryAnchor) Type() protoreflect.EnumType {
	return &file_chatim_v1_core_proto_enumTypes[2]
}

func (x HistoryAnchor) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use HistoryAnchor.Descriptor instead.
func (HistoryAnchor) EnumDescriptor() ([]byte, []int) {
	return file_chatim_v1_core_proto_rawDescGZIP(), []int{2}
}

type Room struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Tenant        string                 `protobuf:"bytes,2,opt,name=tenant,proto3" json:"tenant,omitempty"`
	Type          RoomType               `protobuf:"varint,3,opt,name=type,proto3,enum=chatim.v1.RoomType" json:"type,omitempty"`
	Name          string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	CreatedBy     string                 `protobuf:"bytes,5,opt,name=created_by,json=createdBy,proto3" json:"created_by,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	MemberCount   int32                  `protobuf:"varint,7,opt,name=member_count,json=memberCount,proto3" json:"member_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Room) Reset() {
	*x = Room{}
	mi := &file_chatim_v1_core_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Room) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Room) ProtoMessage() {}

func (x *Room) ProtoReflect() protoreflect.Message {
	mi := &file_chatim_v1_core_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Room.ProtoReflect.Descriptor instead.
func (*Room) Descriptor() ([]byte, []int) {
	return file_chatim_v1_core_proto_rawDescGZIP(), []int{0}
}

func (x *Room) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Room) GetTenant() string {
	if x != nil {
		return x.Tenant
	}
	return ""
}

func (x *Room) GetType() RoomType {
	if x != nil {
		return x.Type
	}
	return RoomType_ROOM_TYPE_UNSPECIFIED
}

func (x *Room) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Room) GetCreatedBy() string {
	if x != nil {
		return x.CreatedBy
	}
	return ""
}

func (x *Room) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Room) GetMemberCount() int32 {
	if x != nil {
		return x.MemberCount
	}
	return 0
}

type Message struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        string                 `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	ThreadRoot    uint64                 `protobuf:"varint,2,opt,name=thread_root,json=threadRoot,proto3" json:"thread_root,omitempty"`
	Seq           uint64                 `protobuf:"varint,3,opt,name=seq,proto3" json:"seq,omitempty"`
	Pts           uint64                 `protobuf:"varint,4,opt,name=pts,proto3" json:"pts,omitempty"`
	Sender        string                 `protobuf:"bytes,5,opt,name=sender,proto3" json:"sender,omitempty"`
	Kind          MessageKind            `protobuf:"varint,6,opt,name=kind,proto3,enum=chatim.v1.MessageKind" json:"kind,omitempty"`
	Text          string                 `protobuf:"bytes,7,opt,name=text,proto3" json:"text,omitempty"`
	Cid           string                 `protobuf:"bytes,8,opt,name=cid,proto3" json:"cid,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_chatim_v1_core_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_chatim_v1_core_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_chatim_v1_core_proto_rawDescGZIP(), []int{1}
}

func (x *Message) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *Message) GetThreadRoot() uint64 {
	if x != nil {
		return x.ThreadRoot
	}
	return 0
}

func (x *Message) GetSeq() uint64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *Message) GetPts() uint64 {
	if x != nil {
		return x.Pts
	}
	return 0
}

func (x *Message) GetSender() string {
	if x != nil {
		return x.Sender
	}
	return ""
}

func (x *Message) GetKind() MessageKind {
	if x != nil {
		return x.Kind
	}
	return MessageKind_MESSAGE_KIND_UNSPECIFIED
}

func (x *Message) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *Message) GetCid() string {
	if x != nil {
		return x.Cid
	}
	return ""
}

func (x *Message) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type CreateRoomRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          RoomType               `protobuf:"varint,1,opt,name=type,proto3,enum=chatim.v1.RoomType" json:"type,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Members       []string               `protobuf:"bytes,3,rep,name=members,proto3" json:"members,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRoomRequest) Reset() {
	*x = CreateRoomRequest{}
	mi := &file_chatim_v1_core_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRoomRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRoomRequest) ProtoMessage() {}

func (x *CreateRoomRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chatim_v1_core_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRoomRequest.ProtoReflect.Descriptor instead.
func (*CreateRoomRequest) Descriptor() ([]byte, []int) {
	return file_chatim_v1_core_proto_rawDescGZIP(), []int{2}
}

func (x *CreateRoomRequest) GetType() RoomType {
	if x != nil {
		return x.Type
	}
	return RoomType_ROOM_TYPE_UNSPECIFIED
}

func (x *CreateRoomRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateRoomRequest) GetMembers() []string {
	if x != nil {
		return x.Members
	}
	return nil
}

type CreateRoomResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Room          *Room                  `protobuf:"bytes,1,opt,name=room,proto3" json:"room,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRoomResponse) Reset() {
	*x = CreateRoomResponse{}
	mi := &file_chatim_v1_core_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRoomResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRoomResponse) ProtoMessage() {}

func (x *CreateRoomResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chatim_v1_core_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRoomResponse.ProtoReflect.Descriptor instead.
func (*CreateRoomResponse) Descriptor() ([]byte, []int) {
	return file_chatim_v1_core_proto_rawDescGZIP(), []int{3}
}

func (x *CreateRoomResponse) GetRoom() *Room {
	if x != nil {
		return x.Room
	}
	return nil
}

type SendMessageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        string                 `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	ThreadRoot    uint64                 `protobuf:"varint,2,opt,name=thread_root,json=threadRoot,proto3" json:"thread_root,omitempty"`
	Cid           string                 `protobuf:"bytes,3,opt,name=cid,proto3" json:"cid,omitempty"`
	Text          string                 `protobuf:"bytes,4,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendMessageRequest) Reset() {
	*x = SendMessageRequest{}
	mi := &file_chatim_v1_core_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMessageRequest) ProtoMessage() {}

func (x *SendMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chatim_v1_core_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMessageRequest.ProtoReflect.Descriptor instead.
func (*SendMessageRequest) Descriptor() ([]byte, []int) {
	return file_chatim_v1_core_proto_rawDescGZIP(), []int{4}
}

func (x *SendMessageRequest) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *SendMessageRequest) GetThreadRoot() uint64 {
	if x != nil {
		return x.ThreadRoot
	}
	return 0
}

func (x *SendMessageRequest) GetCid() string {
	if x != nil {
		return x.Cid
	}
	return ""
}

func (x *SendMessageRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type SendMessageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Seq           uint64                 `protobuf:"varint,1,opt,name=seq,proto3" json:"seq,omitempty"`
	Pts           uint64                 `protobuf:"varint,2,opt,name=pts,proto3" json:"pts,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendMessageResponse) Reset() {
	*x = SendMessageResponse{}
	mi := &file_chatim_v1_core_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMessageResponse) ProtoMessage() {}

func (x *SendMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chatim_v1_core_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMessageResponse.ProtoReflect.Descriptor instead.
func (*SendMessageResponse) Descriptor() ([]byte, []int) {
	return file_chatim_v1_core_proto_rawDescGZIP(), []int{5}
}

func (x *SendMessageResponse) GetSeq() uint64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *SendMessageResponse) GetPts() uint64 {
	if x != nil {
		return x.Pts
	}
	return 0
}

func (x *SendMessageResponse) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type GetHistoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        string                 `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	ThreadRoot    uint64                 `protobuf:"varint,2,opt,name=thread_root,json=threadRoot,proto3" json:"thread_root,omitempty"`
	Anchor        HistoryAnchor          `protobuf:"varint,3,opt,name=anchor,proto3,enum=chatim.v1.HistoryAnchor" json:"anchor,omitempty"`
	Seq           uint64                 `protobuf:"varint,4,opt,name=seq,proto3" json:"seq,omitempty"`
	Limit         int32                  `protobuf:"varint,5,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetHistoryRequest) Reset() {
	*x = GetHistoryRequest{}
	mi := &file_chatim_v1_core_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHistoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHistoryRequest) ProtoMessage() {}

func (x *GetHistoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chatim_v1_core_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHistoryRequest.ProtoReflect.Descriptor instead.
func (*GetHistoryRequest) Descriptor() ([]byte, []int) {
	return file_chatim_v1_core_proto_rawDescGZIP(), []int{6}
}

func (x *GetHistoryRequest) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *GetHistoryRequest) GetThreadRoot() uint64 {
	if x != nil {
		return x.ThreadRoot
	}
	return 0
}

func (x *GetHistoryRequest) GetAnchor() HistoryAnchor {
	if x != nil {
		return x.Anchor
	}
	return HistoryAnchor_HISTORY_ANCHOR_UNSPECIFIED
}

func (x *GetHistoryRequest) GetSeq() uint64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *GetHistoryRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type GetHistoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Messages      []*Message             `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetHistoryResponse) Reset() {
	*x = GetHistoryResponse{}
	mi := &file_chatim_v1_core_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHistoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHistoryResponse) ProtoMessage() {}

func (x *GetHistoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chatim_v1_core_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHistoryResponse.ProtoReflect.Descriptor instead.
func (*GetHistoryResponse) Descriptor() ([]byte, []int) {
	return file_chatim_v1_core_proto_rawDescGZIP(), []int{7}
}

func (x *GetHistoryResponse) GetMessages() []*Message {
	if x != nil {
		return x.Messages
	}
	return nil
}

var File_chatim_v1_core_proto protoreflect.FileDescriptor

const file_chatim_v1_core_proto_rawDesc = "" +
	"\n" +
	"\x14chatim/v1/core.proto\x12\tchatim.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xe8\x01\n" +
	"\x04Room\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06tenant\x18\x02 \x01(\tR\x06tenant\x12'\n" +
	"\x04type\x18\x03 \x01(\x0e2\x13.chatim.v1.RoomTypeR\x04type\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"created_by\x18\x05 \x01(\tR\tcreatedBy\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12!\n" +
	"\fmember_count\x18\a \x01(\x05R\vmemberCount\"\x8c\x02\n" +
	"\aMessage\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\tR\x06roomId\x12\x1f\n" +
	"\vthread_root\x18\x02 \x01(\x04R\n" +
	"threadRoot\x12\x10\n" +
	"\x03seq\x18\x03 \x01(\x04R\x03seq\x12\x10\n" +
	"\x03pts\x18\x04 \x01(\x04R\x03pts\x12\x16\n" +
	"\x06sender\x18\x05 \x01(\tR\x06sender\x12*\n" +
	"\x04kind\x18\x06 \x01(\x0e2\x16.chatim.v1.MessageKindR\x04kind\x12\x12\n" +
	"\x04text\x18\a \x01(\tR\x04text\x12\x10\n" +
	"\x03cid\x18\b \x01(\tR\x03cid\x129\n" +
	"\n" +
	"created_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"j\n" +
	"\x11CreateRoomRequest\x12'\n" +
	"\x04type\x18\x01 \x01(\x0e2\x13.chatim.v1.RoomTypeR\x04type\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x18\n" +
	"\amembers\x18\x03 \x03(\tR\amembers\"9\n" +
	"\x12CreateRoomResponse\x12#\n" +
	"\x04room\x18\x01 \x01(\v2\x0f.chatim.v1.RoomR\x04room\"t\n" +
	"\x12SendMessageRequest\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\tR\x06roomId\x12\x1f\n" +
	"\vthread_root\x18\x02 \x01(\x04R\n" +
	"threadRoot\x12\x10\n" +
	"\x03cid\x18\x03 \x01(\tR\x03cid\x12\x12\n" +
	"\x04text\x18\x04 \x01(\tR\x04text\"t\n" +
	"\x13SendMessageResponse\x12\x10\n" +
	"\x03seq\x18\x01 \x01(\x04R\x03seq\x12\x10\n" +
	"\x03pts\x18\x02 \x01(\x04R\x03pts\x129\n" +
	"\n" +
	"created_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"\xa7\x01\n" +
	"\x11GetHistoryRequest\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\tR\x06roomId\x12\x1f\n" +
	"\vthread_root\x18\x02 \x01(\x04R\n" +
	"threadRoot\x120\n" +
	"\x06anchor\x18\x03 \x01(\x0e2\x18.chatim.v1.HistoryAnchorR\x06anchor\x12\x10\n" +
	"\x03seq\x18\x04 \x01(\x04R\x03seq\x12\x14\n" +
	"\x05limit\x18\x05 \x01(\x05R\x05limit\"D\n" +
	"\x12GetHistoryResponse\x12.\n" +
	"\bmessages\x18\x01 \x03(\v2\x12.chatim.v1.MessageR\bmessages*L\n" +
	"\bRoomType\x12\x19\n" +
	"\x15ROOM_TYPE_UNSPECIFIED\x10\x00\x12\x10\n" +
	"\fROOM_TYPE_DM\x10\x01\x12\x13\n" +
	"\x0fROOM_TYPE_GROUP\x10\x02*B\n" +
	"\vMessageKind\x12\x1c\n" +
	"\x18MESSAGE_KIND_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11MESSAGE_KIND_TEXT\x10\x01*\x9a\x01\n" +
	"\rHistoryAnchor\x12\x1e\n" +
	"\x1aHISTORY_ANCHOR_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15HISTORY_ANCHOR_LATEST\x10\x01\x12\x19\n" +
	"\x15HISTORY_ANCHOR_OLDEST\x10\x02\x12\x19\n" +
	"\x15HISTORY_ANCHOR_BEFORE\x10\x03\x12\x18\n" +
	"\x14HISTORY_ANCHOR_AFTER\x10\x042\xf1\x01\n" +
	"\vCoreService\x12I\n" +
	"\n" +
	"CreateRoom\x12\x1c.chatim.v1.CreateRoomRequest\x1a\x1d.chatim.v1.CreateRoomResponse\x12L\n" +
	"\vSendMessage\x12\x1d.chatim.v1.SendMessageRequest\x1a\x1e.chatim.v1.SendMessageResponse\x12I\n" +
	"\n" +
	"GetHistory\x12\x1c.chatim.v1.GetHistoryRequest\x1a\x1d.chatim.v1.GetHistoryResponseB\x9a\x01\n" +
	"\rcom.chatim.v1B\tCoreProtoP\x01Z9github.com/ivannguyendev/chatim/pkg/pb/chatim/v1;chatimv1\xa2\x02\x03CXX\xaa\x02\tChatim.V1\xca\x02\tChatim\\V1\xe2\x02\x15Chatim\\V1\\GPBMetadata\xea\x02\n" +
	"Chatim::V1b\x06proto3"

var (
	file_chatim_v1_core_proto_rawDescOnce sync.Once
	file_chatim_v1_core_proto_rawDescData []byte
)

func file_chatim_v1_core_proto_rawDescGZIP() []byte {
	file_chatim_v1_core_proto_rawDescOnce.Do(func() {
		file_chatim_v1_core_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_chatim_v1_core_proto_rawDesc), len(file_chatim_v1_core_proto_rawDesc)))
	})
	return file_chatim_v1_core_proto_rawDescData
}

var file_chatim_v1_core_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_chatim_v1_core_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_chatim_v1_core_proto_goTypes = []any{
	(RoomType)(0),                 // 0: chatim.v1.RoomType
	(MessageKind)(0),              // 1: chatim.v1.MessageKind
	(HistoryAnchor)(0),            // 2: chatim.v1.HistoryAnchor
	(*Room)(nil),                  // 3: chatim.v1.Room
	(*Message)(nil),               // 4: chatim.v1.Message
	(*CreateRoomRequest)(nil),     // 5: chatim.v1.CreateRoomRequest
	(*CreateRoomResponse)(nil),    // 6: chatim.v1.CreateRoomResponse
	(*SendMessageRequest)(nil),    // 7: chatim.v1.SendMessageRequest
	(*SendMessageResponse)(nil),   // 8: chatim.v1.SendMessageResponse
	(*GetHistoryRequest)(nil),     // 9: chatim.v1.GetHistoryRequest
	(*GetHistoryResponse)(nil),    // 10: chatim.v1.GetHistoryResponse
	(*timestamppb.Timestamp)(nil), // 11: google.protobuf.Timestamp
}
var file_chatim_v1_core_proto_depIdxs = []int32{
	0,  // 0: chatim.v1.Room.type:type_name -> chatim.v1.RoomType
	11, // 1: chatim.v1.Room.created_at:type_name -> google.protobuf.Timestamp
	1,  // 2: chatim.v1.Message.kind:type_name -> chatim.v1.MessageKind
	11, // 3: chatim.v1.Message.created_at:type_name -> google.protobuf.Timestamp
	0,  // 4: chatim.v1.CreateRoomRequest.type:type_name -> chatim.v1.RoomType
	3,  // 5: chatim.v1.CreateRoomResponse.room:type_name -> chatim.v1.Room
	11, // 6: chatim.v1.SendMessageResponse.created_at:type_name -> google.protobuf.Timestamp
	2,  // 7: chatim.v1.GetHistoryRequest.anchor:type_name -> chatim.v1.HistoryAnchor
	4,  // 8: chatim.v1.GetHistoryResponse.messages:type_name -> chatim.v1.Message
	5,  // 9: chatim.v1.CoreService.CreateRoom:input_type -> chatim.v1.CreateRoomRequest
	7,  // 10: chatim.v1.CoreService.SendMessage:input_type -> chatim.v1.SendMessageRequest
	9,  // 11: chatim.v1.CoreService.GetHistory:input_type -> chatim.v1.GetHistoryRequest
	6,  // 12: chatim.v1.CoreService.CreateRoom:output_type -> chatim.v1.CreateRoomResponse
	8,  // 13: chatim.v1.CoreService.SendMessage:output_type -> chatim.v1.SendMessageResponse
	10, // 14: chatim.v1.CoreService.GetHistory:output_type -> chatim.v1.GetHistoryResponse
	12, // [12:15] is the sub-list for method output_type
	9,  // [9:12] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_chatim_v1_core_proto_init() }
func file_chatim_v1_core_proto_init() {
	if File_chatim_v1_core_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_chatim_v1_core_proto_rawDesc), len(file_chatim_v1_core_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_chatim_v1_core_proto_goTypes,
		DependencyIndexes: file_chatim_v1_core_proto_depIdxs,
		EnumInfos:         file_chatim_v1_core_proto_enumTypes,
		MessageInfos:      file_chatim_v1_core_proto_msgTypes,
	}.Build()
	File_chatim_v1_core_proto = out.File
	file_chatim_v1_core_proto_goTypes = nil
	file_chatim_v1_core_proto_depIdxs = nil
}
