// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: chatim/v1/members.proto

package chatimv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MemberRole int32

const (
	MemberRole_MEMBER_ROLE_UNSPECIFIED MemberRole = 0
	MemberRole_MEMBER_ROLE_OWNER       MemberRole = 1
	MemberRole_MEMBER_ROLE_ADMIN       MemberRole = 2
	MemberRole_MEMBER_ROLE_MEMBER      MemberRole = 3
)

// Enum value maps for MemberRole.
var (
	MemberRole_name = map[int32]string{
		0: "MEMBER_ROLE_UNSPECIFIED",
		1: "MEMBER_ROLE_OWNER",
		2: "MEMBER_ROLE_ADMIN",
		3: "MEMBER_ROLE_MEMBER",
	}
	MemberRole_value = map[string]int32{
		"MEMBER_ROLE_UNSPECIFIED": 0,
		"MEMBER_ROLE_OWNER":       1,
		"MEMBER_ROLE_ADMIN":       2,
		"MEMBER_ROLE_MEMBER":      3,
	}
)

func (x MemberRole) Enum() *MemberRole {
	p := new(MemberRole)
	*p = x
	return p
}

func (x MemberRole) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MemberRole) Descriptor() protoreflect.EnumDescriptor {
	return file_chatim_v1_members_proto_enumTypes[0].Descriptor()
}

func (MemberRole) Type() protoreflect.EnumType {
	return &file_chatim_v1_members_proto_enumTypes[0]
}

func (x MemberRole) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MemberRole.Descriptor instead.
func (MemberRole) EnumDescriptor() ([]byte, []int) {
	return file_chatim_v1_members_proto_rawDescGZIP(), []int{0}
}

type MemberRemovedReason int32

const (
	MemberRemovedReason_MEMBER_REMOVED_REASON_UNSPECIFIED MemberRemovedReason = 0
	MemberRemovedReason_MEMBER_REMOVED_REASON_REMOVED     MemberRemovedReason = 1
	MemberRemovedReason_MEMBER_REMOVED_REASON_LEFT        MemberRemovedReason = 2
)

// Enum value maps for MemberRemovedReason.
var (
	MemberRemovedReason_name = map[int32]string{
		0: "MEMBER_REMOVED_REASON_UNSPECIFIED",
		1: "MEMBER_REMOVED_REASON_REMOVED",
		2: "MEMBER_REMOVED_REASON_LEFT",
	}
	MemberRemovedReason_value = map[string]int32{
		"MEMBER_REMOVED_REASON_UNSPECIFIED": 0,
		"MEMBER_REMOVED_REASON_REMOVED":     1,
		"MEMBER_REMOVED_REASON_LEFT":        2,
	}
)

func (x MemberRemovedReason) Enum() *MemberRemovedReason {
	p := new(MemberRemovedReason)
	*p = x
	return p
}

func (x MemberRemovedReason) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MemberRemovedReason) Descriptor() protoreflect.EnumDescriptor {
	return file_chatim_v1_members_proto_enumTypes[1].Descriptor()
}

func (MemberRemovedReason) Type() protoreflect.EnumType {
	return &file_chatim_v1_members_proto_enumTypes[1]
}

func (x MemberRemovedReason) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MemberRemovedReason.Descriptor instead.
func (MemberRemovedReason) EnumDescriptor() ([]byte, []int) {
	return file_chatim_v1_members_proto_rawDescGZIP(), []int{1}
}

type AddedMember struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          string                 `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	Ver           uint32                 `protobuf:"varint,2,opt,name=ver,proto3" json:"ver,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddedMember) Reset() {
	*x = AddedMember{}
	mi := &file_chatim_v1_members_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddedMember) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddedMember) ProtoMessage() {}

func (x *AddedMember) ProtoReflect() protoreflect.Message {
	mi := &file_chatim_v1_members_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddedMember.ProtoReflect.Descriptor instead.
func (*AddedMember) Descriptor() ([]byte, []int) {
	return file_chatim_v1_members_proto_rawDescGZIP(), []int{0}
}

func (x *AddedMember) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

func (x *AddedMember) GetVer() uint32 {
	if x != nil {
		return x.Ver
	}
	return 0
}

type AddMembersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        string                 `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	Users         []string               `protobuf:"bytes,2,rep,name=users,proto3" json:"users,omitempty"`
	RequestId     string                 `protobuf:"bytes,3,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddMembersRequest) Reset() {
	*x = AddMembersRequest{}
	mi := &file_chatim_v1_members_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddMembersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddMembersRequest) ProtoMessage() {}

func (x *AddMembersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chatim_v1_members_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddMembersRequest.ProtoReflect.Descriptor instead.
func (*AddMembersRequest) Descriptor() ([]byte, []int) {
	return file_chatim_v1_members_proto_rawDescGZIP(), []int{1}
}

func (x *AddMembersRequest) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *AddMembersRequest) GetUsers() []string {
	if x != nil {
		return x.Users
	}
	return nil
}

func (x *AddMembersRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

type AddMembersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Added         []*AddedMember         `protobuf:"bytes,1,rep,name=added,proto3" json:"added,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddMembersResponse) Reset() {
	*x = AddMembersResponse{}
	mi := &file_chatim_v1_members_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddMembersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddMembersResponse) ProtoMessage() {}

func (x *AddMembersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chatim_v1_members_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddMembersResponse.ProtoReflect.Descriptor instead.
func (*AddMembersResponse) Descriptor() ([]byte, []int) {
	return file_chatim_v1_members_proto_rawDescGZIP(), []int{2}
}

func (x *AddMembersResponse) GetAdded() []*AddedMember {
	if x != nil {
		return x.Added
	}
	return nil
}

type RemoveMemberRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        string                 `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	User          string                 `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveMemberRequest) Reset() {
	*x = RemoveMemberRequest{}
	mi := &file_chatim_v1_members_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveMemberRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveMemberRequest) ProtoMessage() {}

func (x *RemoveMemberRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chatim_v1_members_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveMemberRequest.ProtoReflect.Descriptor instead.
func (*RemoveMemberRequest) Descriptor() ([]byte, []int) {
	return file_chatim_v1_members_proto_rawDescGZIP(), []int{3}
}

func (x *RemoveMemberRequest) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *RemoveMemberRequest) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

type RemoveMemberResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Changed       bool                   `protobuf:"varint,1,opt,name=changed,proto3" json:"changed,omitempty"`
	Ver           uint32                 `protobuf:"varint,2,opt,name=ver,proto3" json:"ver,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveMemberResponse) Reset() {
	*x = RemoveMemberResponse{}
	mi := &file_chatim_v1_members_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveMemberResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveMemberResponse) ProtoMessage() {}

func (x *RemoveMemberResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chatim_v1_members_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveMemberResponse.ProtoReflect.Descriptor instead.
func (*RemoveMemberResponse) Descriptor() ([]byte, []int) {
	return file_chatim_v1_members_proto_rawDescGZIP(), []int{4}
}

func (x *RemoveMemberResponse) GetChanged() bool {
	if x != nil {
		return x.Changed
	}
	return false
}

func (x *RemoveMemberResponse) GetVer() uint32 {
	if x != nil {
		return x.Ver
	}
	return 0
}

type LeaveRoomRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        string                 `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeaveRoomRequest) Reset() {
	*x = LeaveRoomRequest{}
	mi := &file_chatim_v1_members_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaveRoomRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaveRoomRequest) ProtoMessage() {}

func (x *LeaveRoomRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chatim_v1_members_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaveRoomRequest.ProtoReflect.Descriptor instead.
func (*LeaveRoomRequest) Descriptor() ([]byte, []int) {
	return file_chatim_v1_members_proto_rawDescGZIP(), []int{5}
}

func (x *LeaveRoomRequest) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

type LeaveRoomResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Changed       bool                   `protobuf:"varint,1,opt,name=changed,proto3" json:"changed,omitempty"`
	Ver           uint32                 `protobuf:"varint,2,opt,name=ver,proto3" json:"ver,omitempty"`
	NewOwner      string                 `protobuf:"bytes,3,opt,name=new_owner,json=newOwner,proto3" json:"new_owner,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeaveRoomResponse) Reset() {
	*x = LeaveRoomResponse{}
	mi := &file_chatim_v1_members_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaveRoomResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaveRoomResponse) ProtoMessage() {}

func (x *LeaveRoomResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chatim_v1_members_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaveRoomResponse.ProtoReflect.Descriptor instead.
func (*LeaveRoomResponse) Descriptor() ([]byte, []int) {
	return file_chatim_v1_members_proto_rawDescGZIP(), []int{6}
}

func (x *LeaveRoomResponse) GetChanged() bool {
	if x != nil {
		return x.Changed
	}
	return false
}

func (x *LeaveRoomResponse) GetVer() uint32 {
	if x != nil {
		return x.Ver
	}
	return 0
}

func (x *LeaveRoomResponse) GetNewOwner() string {
	if x != nil {
		return x.NewOwner
	}
	return ""
}

type ChangeMemberRoleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        string                 `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	User          string                 `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	Role          MemberRole             `protobuf:"varint,3,opt,name=role,proto3,enum=chatim.v1.MemberRole" json:"role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChangeMemberRoleRequest) Reset() {
	*x = ChangeMemberRoleRequest{}
	mi := &file_chatim_v1_members_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChangeMemberRoleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangeMemberRoleRequest) ProtoMessage() {}

func (x *ChangeMemberRoleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chatim_v1_members_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangeMemberRoleRequest.ProtoReflect.Descriptor instead.
func (*ChangeMemberRoleRequest) Descriptor() ([]byte, []int) {
	return file_chatim_v1_members_proto_rawDescGZIP(), []int{7}
}

func (x *ChangeMemberRoleRequest) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *ChangeMemberRoleRequest) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

func (x *ChangeMemberRoleRequest) GetRole() MemberRole {
	if x != nil {
		return x.Role
	}
	return MemberRole_MEMBER_ROLE_UNSPECIFIED
}

type ChangeMemberRoleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Changed       bool                   `protobuf:"varint,1,opt,name=changed,proto3" json:"changed,omitempty"`
	Ver           uint32                 `protobuf:"varint,2,opt,name=ver,proto3" json:"ver,omitempty"`
	PreviousRole  MemberRole             `protobuf:"varint,3,opt,name=previous_role,json=previousRole,proto3,enum=chatim.v1.MemberRole" json:"previous_role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChangeMemberRoleResponse) Reset() {
	*x = ChangeMemberRoleResponse{}
	mi := &file_chatim_v1_members_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChangeMemberRoleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangeMemberRoleResponse) ProtoMessage() {}

func (x *ChangeMemberRoleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chatim_v1_members_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangeMemberRoleResponse.ProtoReflect.Descriptor instead.
func (*ChangeMemberRoleResponse) Descriptor() ([]byte, []int) {
	return file_chatim_v1_members_proto_rawDescGZIP(), []int{8}
}

func (x *ChangeMemberRoleResponse) GetChanged() bool {
	if x != nil {
		return x.Changed
	}
	return false
}

func (x *ChangeMemberRoleResponse) GetVer() uint32 {
	if x != nil {
		return x.Ver
	}
	return 0
}

func (x *ChangeMemberRoleResponse) GetPreviousRole() MemberRole {
	if x != nil {
		return x.PreviousRole
	}
	return MemberRole_MEMBER_ROLE_UNSPECIFIED
}

type SetMemberPriorityRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        string                 `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	User          string                 `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	Priority      int32                  `protobuf:"varint,3,opt,name=priority,proto3" json:"priority,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetMemberPriorityRequest) Reset() {
	*x = SetMemberPriorityRequest{}
	mi := &file_chatim_v1_members_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetMemberPriorityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetMemberPriorityRequest) ProtoMessage() {}

func (x *SetMemberPriorityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chatim_v1_members_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetMemberPriorityRequest.ProtoReflect.Descriptor instead.
func (*SetMemberPriorityRequest) Descriptor() ([]byte, []int) {
	return file_chatim_v1_members_proto_rawDescGZIP(), []int{9}
}

func (x *SetMemberPriorityRequest) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *SetMemberPriorityRequest) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

func (x *SetMemberPriorityRequest) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

type SetMemberPriorityResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Changed          bool                   `protobuf:"varint,1,opt,name=changed,proto3" json:"changed,omitempty"`
	Ver              uint32                 `protobuf:"varint,2,opt,name=ver,proto3" json:"ver,omitempty"`
	PreviousPriority int32                  `protobuf:"varint,3,opt,name=previous_priority,json=previousPriority,proto3" json:"previous_priority,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *SetMemberPriorityResponse) Reset() {
	*x = SetMemberPriorityResponse{}
	mi := &file_chatim_v1_members_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetMemberPriorityResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetMemberPriorityResponse) ProtoMessage() {}

func (x *SetMemberPriorityResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chatim_v1_members_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetMemberPriorityResponse.ProtoReflect.Descriptor instead.
func (*SetMemberPriorityResponse) Descriptor() ([]byte, []int) {
	return file_chatim_v1_members_proto_rawDescGZIP(), []int{10}
}

func (x *SetMemberPriorityResponse) GetChanged() bool {
	if x != nil {
		return x.Changed
	}
	return false
}

func (x *SetMemberPriorityResponse) GetVer() uint32 {
	if x != nil {
		return x.Ver
	}
	return 0
}

func (x *SetMemberPriorityResponse) GetPreviousPriority() int32 {
	if x != nil {
		return x.PreviousPriority
	}
	return 0
}

type MarkReadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        string                 `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	Seq           uint64                 `protobuf:"varint,2,opt,name=seq,proto3" json:"seq,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MarkReadRequest) Reset() {
	*x = MarkReadRequest{}
	mi := &file_chatim_v1_members_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarkReadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarkReadRequest) ProtoMessage() {}

func (x *MarkReadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chatim_v1_members_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarkReadRequest.ProtoReflect.Descriptor instead.
func (*MarkReadRequest) Descriptor() ([]byte, []int) {
	return file_chatim_v1_members_proto_rawDescGZIP(), []int{11}
}

func (x *MarkReadRequest) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *MarkReadRequest) GetSeq() uint64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

type MarkReadResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReadSeq       uint64                 `protobuf:"varint,1,opt,name=read_seq,json=readSeq,proto3" json:"read_seq,omitempty"`
	ReadVer       uint64                 `protobuf:"varint,2,opt,name=read_ver,json=readVer,proto3" json:"read_ver,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MarkReadResponse) Reset() {
	*x = MarkReadResponse{}
	mi := &file_chatim_v1_members_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarkReadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarkReadResponse) ProtoMessage() {}

func (x *MarkReadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chatim_v1_members_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarkReadResponse.ProtoReflect.Descriptor instead.
func (*MarkReadResponse) Descriptor() ([]byte, []int) {
	return file_chatim_v1_members_proto_rawDescGZIP(), []int{12}
}

func (x *MarkReadResponse) GetReadSeq() uint64 {
	if x != nil {
		return x.ReadSeq
	}
	return 0
}

func (x *MarkReadResponse) GetReadVer() uint64 {
	if x != nil {
		return x.ReadVer
	}
	return 0
}

type MarkUnreadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        string                 `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	Seq           uint64                 `protobuf:"varint,2,opt,name=seq,proto3" json:"seq,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MarkUnreadRequest) Reset() {
	*x = MarkUnreadRequest{}
	mi := &file_chatim_v1_members_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarkUnreadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarkUnreadRequest) ProtoMessage() {}

func (x *MarkUnreadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chatim_v1_members_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarkUnreadRequest.ProtoReflect.Descriptor instead.
func (*MarkUnreadRequest) Descriptor() ([]byte, []int) {
	return file_chatim_v1_members_proto_rawDescGZIP(), []int{13}
}

func (x *MarkUnreadRequest) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *MarkUnreadRequest) GetSeq() uint64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

type MarkUnreadResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReadSeq       uint64                 `protobuf:"varint,1,opt,name=read_seq,json=readSeq,proto3" json:"read_seq,omitempty"`
	ReadVer       uint64                 `protobuf:"varint,2,opt,name=read_ver,json=readVer,proto3" json:"read_ver,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MarkUnreadResponse) Reset() {
	*x = MarkUnreadResponse{}
	mi := &file_chatim_v1_members_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarkUnreadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarkUnreadResponse) ProtoMessage() {}

func (x *MarkUnreadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chatim_v1_members_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarkUnreadResponse.ProtoReflect.Descriptor instead.
func (*MarkUnreadResponse) Descriptor() ([]byte, []int) {
	return file_chatim_v1_members_proto_rawDescGZIP(), []int{14}
}

func (x *MarkUnreadResponse) GetReadSeq() uint64 {
	if x != nil {
		return x.ReadSeq
	}
	return 0
}

func (x *MarkUnreadResponse) GetReadVer() uint64 {
	if x != nil {
		return x.ReadVer
	}
	return 0
}

type MemberAdded struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          string                 `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	Role          MemberRole             `protobuf:"varint,2,opt,name=role,proto3,enum=chatim.v1.MemberRole" json:"role,omitempty"`
	JoinedAt      *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=joined_at,json=joinedAt,proto3" json:"joined_at,omitempty"`
	Ver           uint32                 `protobuf:"varint,4,opt,name=ver,proto3" json:"ver,omitempty"`
	RequestId     string                 `protobuf:"bytes,5,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	ReadSeq       uint64                 `protobuf:"varint,6,opt,name=read_seq,json=readSeq,proto3" json:"read_seq,omitempty"`
	ReadVer       uint64                 `protobuf:"varint,7,opt,name=read_ver,json=readVer,proto3" json:"read_ver,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MemberAdded) Reset() {
	*x = MemberAdded{}
	mi := &file_chatim_v1_members_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MemberAdded) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MemberAdded) ProtoMessage() {}

func (x *MemberAdded) ProtoReflect() protoreflect.Message {
	mi := &file_chatim_v1_members_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MemberAdded.ProtoReflect.Descriptor instead.
func (*MemberAdded) Descriptor() ([]byte, []int) {
	return file_chatim_v1_members_proto_rawDescGZIP(), []int{15}
}

func (x *MemberAdded) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

func (x *MemberAdded) GetRole() MemberRole {
	if x != nil {
		return x.Role
	}
	return MemberRole_MEMBER_ROLE_UNSPECIFIED
}

func (x *MemberAdded) GetJoinedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.JoinedAt
	}
	return nil
}

func (x *MemberAdded) GetVer() uint32 {
	if x != nil {
		return x.Ver
	}
	return 0
}

func (x *MemberAdded) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *MemberAdded) GetReadSeq() uint64 {
	if x != nil {
		return x.ReadSeq
	}
	return 0
}

func (x *MemberAdded) GetReadVer() uint64 {
	if x != nil {
		return x.ReadVer
	}
	return 0
}

type MemberRemoved struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          string                 `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	Reason        MemberRemovedReason    `protobuf:"varint,2,opt,name=reason,proto3,enum=chatim.v1.MemberRemovedReason" json:"reason,omitempty"`
	PreviousRole  MemberRole             `protobuf:"varint,3,opt,name=previous_role,json=previousRole,proto3,enum=chatim.v1.MemberRole" json:"previous_role,omitempty"`
	Ver           uint32                 `protobuf:"varint,4,opt,name=ver,proto3" json:"ver,omitempty"`
	RequestId     string                 `protobuf:"bytes,5,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MemberRemoved) Reset() {
	*x = MemberRemoved{}
	mi := &file_chatim_v1_members_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MemberRemoved) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MemberRemoved) ProtoMessage() {}

func (x *MemberRemoved) ProtoReflect() protoreflect.Message {
	mi := &file_chatim_v1_members_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MemberRemoved.ProtoReflect.Descriptor instead.
func (*MemberRemoved) Descriptor() ([]byte, []int) {
	return file_chatim_v1_members_proto_rawDescGZIP(), []int{16}
}

func (x *MemberRemoved) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

func (x *MemberRemoved) GetReason() MemberRemovedReason {
	if x != nil {
		return x.Reason
	}
	return MemberRemovedReason_MEMBER_REMOVED_REASON_UNSPECIFIED
}

func (x *MemberRemoved) GetPreviousRole() MemberRole {
	if x != nil {
		return x.PreviousRole
	}
	return MemberRole_MEMBER_ROLE_UNSPECIFIED
}

func (x *MemberRemoved) GetVer() uint32 {
	if x != nil {
		return x.Ver
	}
	return 0
}

func (x *MemberRemoved) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

type MemberRoleChanged struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          string                 `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	Role          MemberRole             `protobuf:"varint,2,opt,name=role,proto3,enum=chatim.v1.MemberRole" json:"role,omitempty"`
	PreviousRole  MemberRole             `protobuf:"varint,3,opt,name=previous_role,json=previousRole,proto3,enum=chatim.v1.MemberRole" json:"previous_role,omitempty"`
	Ver           uint32                 `protobuf:"varint,4,opt,name=ver,proto3" json:"ver,omitempty"`
	RequestId     string                 `protobuf:"bytes,5,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MemberRoleChanged) Reset() {
	*x = MemberRoleChanged{}
	mi := &file_chatim_v1_members_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MemberRoleChanged) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MemberRoleChanged) ProtoMessage() {}

func (x *MemberRoleChanged) ProtoReflect() protoreflect.Message {
	mi := &file_chatim_v1_members_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MemberRoleChanged.ProtoReflect.Descriptor instead.
func (*MemberRoleChanged) Descriptor() ([]byte, []int) {
	return file_chatim_v1_members_proto_rawDescGZIP(), []int{17}
}

func (x *MemberRoleChanged) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

func (x *MemberRoleChanged) GetRole() MemberRole {
	if x != nil {
		return x.Role
	}
	return MemberRole_MEMBER_ROLE_UNSPECIFIED
}

func (x *MemberRoleChanged) GetPreviousRole() MemberRole {
	if x != nil {
		return x.PreviousRole
	}
	return MemberRole_MEMBER_ROLE_UNSPECIFIED
}

func (x *MemberRoleChanged) GetVer() uint32 {
	if x != nil {
		return x.Ver
	}
	return 0
}

func (x *MemberRoleChanged) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

type MemberPriorityChanged struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	User             string                 `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	Priority         int32                  `protobuf:"varint,2,opt,name=priority,proto3" json:"priority,omitempty"`
	PreviousPriority int32                  `protobuf:"varint,3,opt,name=previous_priority,json=previousPriority,proto3" json:"previous_priority,omitempty"`
	Ver              uint32                 `protobuf:"varint,4,opt,name=ver,proto3" json:"ver,omitempty"`
	RequestId        string                 `protobuf:"bytes,5,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *MemberPriorityChanged) Reset() {
	*x = MemberPriorityChanged{}
	mi := &file_chatim_v1_members_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MemberPriorityChanged) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MemberPriorityChanged) ProtoMessage() {}

func (x *MemberPriorityChanged) ProtoReflect() protoreflect.Message {
	mi := &file_chatim_v1_members_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MemberPriorityChanged.ProtoReflect.Descriptor instead.
func (*MemberPriorityChanged) Descriptor() ([]byte, []int) {
	return file_chatim_v1_members_proto_rawDescGZIP(), []int{18}
}

func (x *MemberPriorityChanged) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

func (x *MemberPriorityChanged) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

func (x *MemberPriorityChanged) GetPreviousPriority() int32 {
	if x != nil {
		return x.PreviousPriority
	}
	return 0
}

func (x *MemberPriorityChanged) GetVer() uint32 {
	if x != nil {
		return x.Ver
	}
	return 0
}

func (x *MemberPriorityChanged) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

type MemberCountChanged struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	MemberCount    int32                  `protobuf:"varint,1,opt,name=member_count,json=memberCount,proto3" json:"member_count,omitempty"`
	MemberCountVer uint64                 `protobuf:"varint,2,opt,name=member_count_ver,json=memberCountVer,proto3" json:"member_count_ver,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *MemberCountChanged) Reset() {
	*x = MemberCountChanged{}
	mi := &file_chatim_v1_members_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MemberCountChanged) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MemberCountChanged) ProtoMessage() {}

func (x *MemberCountChanged) ProtoReflect() protoreflect.Message {
	mi := &file_chatim_v1_members_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MemberCountChanged.ProtoReflect.Descriptor instead.
func (*MemberCountChanged) Descriptor() ([]byte, []int) {
	return file_chatim_v1_members_proto_rawDescGZIP(), []int{19}
}

func (x *MemberCountChanged) GetMemberCount() int32 {
	if x != nil {
		return x.MemberCount
	}
	return 0
}

func (x *MemberCountChanged) GetMemberCountVer() uint64 {
	if x != nil {
		return x.MemberCountVer
	}
	return 0
}

type ReadUpdated struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          string                 `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	ReadSeq       uint64                 `protobuf:"varint,2,opt,name=read_seq,json=readSeq,proto3" json:"read_seq,omitempty"`
	ReadVer       uint64                 `protobuf:"varint,3,opt,name=read_ver,json=readVer,proto3" json:"read_ver,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadUpdated) Reset() {
	*x = ReadUpdated{}
	mi := &file_chatim_v1_members_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadUpdated) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadUpdated) ProtoMessage() {}

func (x *ReadUpdated) ProtoReflect() protoreflect.Message {
	mi := &file_chatim_v1_members_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadUpdated.ProtoReflect.Descriptor instead.
func (*ReadUpdated) Descriptor() ([]byte, []int) {
	return file_chatim_v1_members_proto_rawDescGZIP(), []int{20}
}

func (x *ReadUpdated) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

func (x *ReadUpdated) GetReadSeq() uint64 {
	if x != nil {
		return x.ReadSeq
	}
	return 0
}

func (x *ReadUpdated) GetReadVer() uint64 {
	if x != nil {
		return x.ReadVer
	}
	return 0
}

type MessageHidden struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          string                 `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	ThreadRoot    uint64                 `protobuf:"varint,2,opt,name=thread_root,json=threadRoot,proto3" json:"thread_root,omitempty"`
	Seq           uint64                 `protobuf:"varint,3,opt,name=seq,proto3" json:"seq,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessageHidden) Reset() {
	*x = MessageHidden{}
	mi := &file_chatim_v1_members_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageHidden) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageHidden) ProtoMessage() {}

func (x *MessageHidden) ProtoReflect() protoreflect.Message {
	mi := &file_chatim_v1_members_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageHidden.ProtoReflect.Descriptor instead.
func (*MessageHidden) Descriptor() ([]byte, []int) {
	return file_chatim_v1_members_proto_rawDescGZIP(), []int{21}
}

func (x *MessageHidden) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

func (x *MessageHidden) GetThreadRoot() uint64 {
	if x != nil {
		return x.ThreadRoot
	}
	return 0
}

func (x *MessageHidden) GetSeq() uint64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

type BookmarkChanged struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ThreadRoot    uint64                 `protobuf:"varint,1,opt,name=thread_root,json=threadRoot,proto3" json:"thread_root,omitempty"`
	Seq           uint64                 `protobuf:"varint,2,opt,name=seq,proto3" json:"seq,omitempty"`
	User          string                 `protobuf:"bytes,3,opt,name=user,proto3" json:"user,omitempty"`
	On            bool                   `protobuf:"varint,4,opt,name=on,proto3" json:"on,omitempty"`
	Ver           uint32                 `protobuf:"varint,5,opt,name=ver,proto3" json:"ver,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BookmarkChanged) Reset() {
	*x = BookmarkChanged{}
	mi := &file_chatim_v1_members_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BookmarkChanged) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BookmarkChanged) ProtoMessage() {}

func (x *BookmarkChanged) ProtoReflect() protoreflect.Message {
	mi := &file_chatim_v1_members_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BookmarkChanged.ProtoReflect.Descriptor instead.
func (*BookmarkChanged) Descriptor() ([]byte, []int) {
	return file_chatim_v1_members_proto_rawDescGZIP(), []int{22}
}

func (x *BookmarkChanged) GetThreadRoot() uint64 {
	if x != nil {
		return x.ThreadRoot
	}
	return 0
}

func (x *BookmarkChanged) GetSeq() uint64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *BookmarkChanged) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

func (x *BookmarkChanged) GetOn() bool {
	if x != nil {
		return x.On
	}
	return false
}

func (x *BookmarkChanged) GetVer() uint32 {
	if x != nil {
		return x.Ver
	}
	return 0
}

type HistoryCleared struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          string                 `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	ClearedAt     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=cleared_at,json=clearedAt,proto3" json:"cleared_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HistoryCleared) Reset() {
	*x = HistoryCleared{}
	mi := &file_chatim_v1_members_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HistoryCleared) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HistoryCleared) ProtoMessage() {}

func (x *HistoryCleared) ProtoReflect() protoreflect.Message {
	mi := &file_chatim_v1_members_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HistoryCleared.ProtoReflect.Descriptor instead.
func (*HistoryCleared) Descriptor() ([]byte, []int) {
	return file_chatim_v1_members_proto_rawDescGZIP(), []int{23}
}

func (x *HistoryCleared) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

func (x *HistoryCleared) GetClearedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ClearedAt
	}
	return nil
}

var File_chatim_v1_members_proto protoreflect.FileDescriptor

const file_chatim_v1_members_proto_rawDesc = "" +
	"\n" +
	"\x17chatim/v1/members.proto\x12\tchatim.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"3\n" +
	"\vAddedMember\x12\x12\n" +
	"\x04user\x18\x01 \x01(\tR\x04user\x12\x10\n" +
	"\x03ver\x18\x02 \x01(\rR\x03ver\"a\n" +
	"\x11AddMembersRequest\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\tR\x06roomId\x12\x14\n" +
	"\x05users\x18\x02 \x03(\tR\x05users\x12\x1d\n" +
	"\n" +
	"request_id\x18\x03 \x01(\tR\trequestId\"B\n" +
	"\x12AddMembersResponse\x12,\n" +
	"\x05added\x18\x01 \x03(\v2\x16.chatim.v1.AddedMemberR\x05added\"B\n" +
	"\x13RemoveMemberRequest\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\tR\x06roomId\x12\x12\n" +
	"\x04user\x18\x02 \x01(\tR\x04user\"B\n" +
	"\x14RemoveMemberResponse\x12\x18\n" +
	"\achanged\x18\x01 \x01(\bR\achanged\x12\x10\n" +
	"\x03ver\x18\x02 \x01(\rR\x03ver\"+\n" +
	"\x10LeaveRoomRequest\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\tR\x06roomId\"\\\n" +
	"\x11LeaveRoomResponse\x12\x18\n" +
	"\achanged\x18\x01 \x01(\bR\achanged\x12\x10\n" +
	"\x03ver\x18\x02 \x01(\rR\x03ver\x12\x1b\n" +
	"\tnew_owner\x18\x03 \x01(\tR\bnewOwner\"q\n" +
	"\x17ChangeMemberRoleRequest\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\tR\x06roomId\x12\x12\n" +
	"\x04user\x18\x02 \x01(\tR\x04user\x12)\n" +
	"\x04role\x18\x03 \x01(\x0e2\x15.chatim.v1.MemberRoleR\x04role\"\x82\x01\n" +
	"\x18ChangeMemberRoleResponse\x12\x18\n" +
	"\achanged\x18\x01 \x01(\bR\achanged\x12\x10\n" +
	"\x03ver\x18\x02 \x01(\rR\x03ver\x12:\n" +
	"\rprevious_role\x18\x03 \x01(\x0e2\x15.chatim.v1.MemberRoleR\fpreviousRole\"c\n" +
	"\x18SetMemberPriorityRequest\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\tR\x06roomId\x12\x12\n" +
	"\x04user\x18\x02 \x01(\tR\x04user\x12\x1a\n" +
	"\bpriority\x18\x03 \x01(\x05R\bpriority\"t\n" +
	"\x19SetMemberPriorityResponse\x12\x18\n" +
	"\achanged\x18\x01 \x01(\bR\achanged\x12\x10\n" +
	"\x03ver\x18\x02 \x01(\rR\x03ver\x12+\n" +
	"\x11previous_priority\x18\x03 \x01(\x05R\x10previousPriority\"<\n" +
	"\x0fMarkReadRequest\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\tR\x06roomId\x12\x10\n" +
	"\x03seq\x18\x02 \x01(\x04R\x03seq\"H\n" +
	"\x10MarkReadResponse\x12\x19\n" +
	"\bread_seq\x18\x01 \x01(\x04R\areadSeq\x12\x19\n" +
	"\bread_ver\x18\x02 \x01(\x04R\areadVer\">\n" +
	"\x11MarkUnreadRequest\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\tR\x06roomId\x12\x10\n" +
	"\x03seq\x18\x02 \x01(\x04R\x03seq\"J\n" +
	"\x12MarkUnreadResponse\x12\x19\n" +
	"\bread_seq\x18\x01 \x01(\x04R\areadSeq\x12\x19\n" +
	"\bread_ver\x18\x02 \x01(\x04R\areadVer\"\xec\x01\n" +
	"\vMemberAdded\x12\x12\n" +
	"\x04user\x18\x01 \x01(\tR\x04user\x12)\n" +
	"\x04role\x18\x02 \x01(\x0e2\x15.chatim.v1.MemberRoleR\x04role\x127\n" +
	"\tjoined_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\bjoinedAt\x12\x10\n" +
	"\x03ver\x18\x04 \x01(\rR\x03ver\x12\x1d\n" +
	"\n" +
	"request_id\x18\x05 \x01(\tR\trequestId\x12\x19\n" +
	"\bread_seq\x18\x06 \x01(\x04R\areadSeq\x12\x19\n" +
	"\bread_ver\x18\a \x01(\x04R\areadVer\"\xc8\x01\n" +
	"\rMemberRemoved\x12\x12\n" +
	"\x04user\x18\x01 \x01(\tR\x04user\x126\n" +
	"\x06reason\x18\x02 \x01(\x0e2\x1e.chatim.v1.MemberRemovedReasonR\x06reason\x12:\n" +
	"\rprevious_role\x18\x03 \x01(\x0e2\x15.chatim.v1.MemberRoleR\fpreviousRole\x12\x10\n" +
	"\x03ver\x18\x04 \x01(\rR\x03ver\x12\x1d\n" +
	"\n" +
	"request_id\x18\x05 \x01(\tR\trequestId\"\xbf\x01\n" +
	"\x11MemberRoleChanged\x12\x12\n" +
	"\x04user\x18\x01 \x01(\tR\x04user\x12)\n" +
	"\x04role\x18\x02 \x01(\x0e2\x15.chatim.v1.MemberRoleR\x04role\x12:\n" +
	"\rprevious_role\x18\x03 \x01(\x0e2\x15.chatim.v1.MemberRoleR\fpreviousRole\x12\x10\n" +
	"\x03ver\x18\x04 \x01(\rR\x03ver\x12\x1d\n" +
	"\n" +
	"request_id\x18\x05 \x01(\tR\trequestId\"\xa5\x01\n" +
	"\x15MemberPriorityChanged\x12\x12\n" +
	"\x04user\x18\x01 \x01(\tR\x04user\x12\x1a\n" +
	"\bpriority\x18\x02 \x01(\x05R\bpriority\x12+\n" +
	"\x11previous_priority\x18\x03 \x01(\x05R\x10previousPriority\x12\x10\n" +
	"\x03ver\x18\x04 \x01(\rR\x03ver\x12\x1d\n" +
	"\n" +
	"request_id\x18\x05 \x01(\tR\trequestId\"a\n" +
	"\x12MemberCountChanged\x12!\n" +
	"\fmember_count\x18\x01 \x01(\x05R\vmemberCount\x12(\n" +
	"\x10member_count_ver\x18\x02 \x01(\x04R\x0ememberCountVer\"W\n" +
	"\vReadUpdated\x12\x12\n" +
	"\x04user\x18\x01 \x01(\tR\x04user\x12\x19\n" +
	"\bread_seq\x18\x02 \x01(\x04R\areadSeq\x12\x19\n" +
	"\bread_ver\x18\x03 \x01(\x04R\areadVer\"V\n" +
	"\rMessageHidden\x12\x12\n" +
	"\x04user\x18\x01 \x01(\tR\x04user\x12\x1f\n" +
	"\vthread_root\x18\x02 \x01(\x04R\n" +
	"threadRoot\x12\x10\n" +
	"\x03seq\x18\x03 \x01(\x04R\x03seq\"z\n" +
	"\x0fBookmarkChanged\x12\x1f\n" +
	"\vthread_root\x18\x01 \x01(\x04R\n" +
	"threadRoot\x12\x10\n" +
	"\x03seq\x18\x02 \x01(\x04R\x03seq\x12\x12\n" +
	"\x04user\x18\x03 \x01(\tR\x04user\x12\x0e\n" +
	"\x02on\x18\x04 \x01(\bR\x02on\x12\x10\n" +
	"\x03ver\x18\x05 \x01(\rR\x03ver\"_\n" +
	"\x0eHistoryCleared\x12\x12\n" +
	"\x04user\x18\x01 \x01(\tR\x04user\x129\n" +
	"\n" +
	"cleared_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tclearedAt*o\n" +
	"\n" +
	"MemberRole\x12\x1b\n" +
	"\x17MEMBER_ROLE_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11MEMBER_ROLE_OWNER\x10\x01\x12\x15\n" +
	"\x11MEMBER_ROLE_ADMIN\x10\x02\x12\x16\n" +
	"\x12MEMBER_ROLE_MEMBER\x10\x03*\x7f\n" +
	"\x13MemberRemovedReason\x12%\n" +
	"!MEMBER_REMOVED_REASON_UNSPECIFIED\x10\x00\x12!\n" +
	"\x1dMEMBER_REMOVED_REASON_REMOVED\x10\x01\x12\x1e\n" +
	"\x1aMEMBER_REMOVED_REASON_LEFT\x10\x02B\x9d\x01\n" +
	"\rcom.chatim.v1B\fMembersProtoP\x01Z9github.com/ivannguyendev/chatim/pkg/pb/chatim/v1;chatimv1\xa2\x02\x03CXX\xaa\x02\tChatim.V1\xca\x02\tChatim\\V1\xe2\x02\x15Chatim\\V1\\GPBMetadata\xea\x02\n" +
	"Chatim::V1b\x06proto3"

var (
	file_chatim_v1_members_proto_rawDescOnce sync.Once
	file_chatim_v1_members_proto_rawDescData []byte
)

func file_chatim_v1_members_proto_rawDescGZIP() []byte {
	file_chatim_v1_members_proto_rawDescOnce.Do(func() {
		file_chatim_v1_members_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_chatim_v1_members_proto_rawDesc), len(file_chatim_v1_members_proto_rawDesc)))
	})
	return file_chatim_v1_members_proto_rawDescData
}

var file_chatim_v1_members_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_chatim_v1_members_proto_msgTypes = make([]protoimpl.MessageInfo, 24)
var file_chatim_v1_members_proto_goTypes = []any{
	(MemberRole)(0),                   // 0: chatim.v1.MemberRole
	(MemberRemovedReason)(0),          // 1: chatim.v1.MemberRemovedReason
	(*AddedMember)(nil),               // 2: chatim.v1.AddedMember
	(*AddMembersRequest)(nil),         // 3: chatim.v1.AddMembersRequest
	(*AddMembersResponse)(nil),        // 4: chatim.v1.AddMembersResponse
	(*RemoveMemberRequest)(nil),       // 5: chatim.v1.RemoveMemberRequest
	(*RemoveMemberResponse)(nil),      // 6: chatim.v1.RemoveMemberResponse
	(*LeaveRoomRequest)(nil),          // 7: chatim.v1.LeaveRoomRequest
	(*LeaveRoomResponse)(nil),         // 8: chatim.v1.LeaveRoomResponse
	(*ChangeMemberRoleRequest)(nil),   // 9: chatim.v1.ChangeMemberRoleRequest
	(*ChangeMemberRoleResponse)(nil),  // 10: chatim.v1.ChangeMemberRoleResponse
	(*SetMemberPriorityRequest)(nil),  // 11: chatim.v1.SetMemberPriorityRequest
	(*SetMemberPriorityResponse)(nil), // 12: chatim.v1.SetMemberPriorityResponse
	(*MarkReadRequest)(nil),           // 13: chatim.v1.MarkReadRequest
	(*MarkReadResponse)(nil),          // 14: chatim.v1.MarkReadResponse
	(*MarkUnreadRequest)(nil),         // 15: chatim.v1.MarkUnreadRequest
	(*MarkUnreadResponse)(nil),        // 16: chatim.v1.MarkUnreadResponse
	(*MemberAdded)(nil),               // 17: chatim.v1.MemberAdded
	(*MemberRemoved)(nil),             // 18: chatim.v1.MemberRemoved
	(*MemberRoleChanged)(nil),         // 19: chatim.v1.MemberRoleChanged
	(*MemberPriorityChanged)(nil),     // 20: chatim.v1.MemberPriorityChanged
	(*MemberCountChanged)(nil),        // 21: chatim.v1.MemberCountChanged
	(*ReadUpdated)(nil),               // 22: chatim.v1.ReadUpdated
	(*MessageHidden)(nil),             // 23: chatim.v1.MessageHidden
	(*BookmarkChanged)(nil),           // 24: chatim.v1.BookmarkChanged
	(*HistoryCleared)(nil),            // 25: chatim.v1.HistoryCleared
	(*timestamppb.Timestamp)(nil),     // 26: google.protobuf.Timestamp
}
var file_chatim_v1_members_proto_depIdxs = []int32{
	2,  // 0: chatim.v1.AddMembersResponse.added:type_name -> chatim.v1.AddedMember
	0,  // 1: chatim.v1.ChangeMemberRoleRequest.role:type_name -> chatim.v1.MemberRole
	0,  // 2: chatim.v1.ChangeMemberRoleResponse.previous_role:type_name -> chatim.v1.MemberRole
	0,  // 3: chatim.v1.MemberAdded.role:type_name -> chatim.v1.MemberRole
	26, // 4: chatim.v1.MemberAdded.joined_at:type_name -> google.protobuf.Timestamp
	1,  // 5: chatim.v1.MemberRemoved.reason:type_name -> chatim.v1.MemberRemovedReason
	0,  // 6: chatim.v1.MemberRemoved.previous_role:type_name -> chatim.v1.MemberRole
	0,  // 7: chatim.v1.MemberRoleChanged.role:type_name -> chatim.v1.MemberRole
	0,  // 8: chatim.v1.MemberRoleChanged.previous_role:type_name -> chatim.v1.MemberRole
	26, // 9: chatim.v1.HistoryCleared.cleared_at:type_name -> google.protobuf.Timestamp
	10, // [10:10] is the sub-list for method output_type
	10, // [10:10] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_chatim_v1_members_proto_init() }
func file_chatim_v1_members_proto_init() {
	if File_chatim_v1_members_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_chatim_v1_members_proto_rawDesc), len(file_chatim_v1_members_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   24,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_chatim_v1_members_proto_goTypes,
		DependencyIndexes: file_chatim_v1_members_proto_depIdxs,
		EnumInfos:         file_chatim_v1_members_proto_enumTypes,
		MessageInfos:      file_chatim_v1_members_proto_msgTypes,
	}.Build()
	File_chatim_v1_members_proto = out.File
	file_chatim_v1_members_proto_goTypes = nil
	file_chatim_v1_members_proto_depIdxs = nil
}
