// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: chatim/v1/message_links.proto

package chatimv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MentionKind int32

const (
	MentionKind_MENTION_KIND_UNSPECIFIED MentionKind = 0
	MentionKind_MENTION_KIND_USER        MentionKind = 1
	MentionKind_MENTION_KIND_GROUP       MentionKind = 2
)

// Enum value maps for MentionKind.
var (
	MentionKind_name = map[int32]string{
		0: "MENTION_KIND_UNSPECIFIED",
		1: "MENTION_KIND_USER",
		2: "MENTION_KIND_GROUP",
	}
	MentionKind_value = map[string]int32{
		"MENTION_KIND_UNSPECIFIED": 0,
		"MENTION_KIND_USER":        1,
		"MENTION_KIND_GROUP":       2,
	}
)

func (x MentionKind) Enum() *MentionKind {
	p := new(MentionKind)
	*p = x
	return p
}

func (x MentionKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MentionKind) Descriptor() protoreflect.EnumDescriptor {
	return file_chatim_v1_message_links_proto_enumTypes[0].Descriptor()
}

func (MentionKind) Type() protoreflect.EnumType {
	return &file_chatim_v1_message_links_proto_enumTypes[0]
}

func (x MentionKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MentionKind.Descriptor instead.
func (MentionKind) EnumDescriptor() ([]byte, []int) {
	return file_chatim_v1_message_links_proto_rawDescGZIP(), []int{0}
}

type ReplyRef struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ThreadRoot    uint64                 `protobuf:"varint,1,opt,name=thread_root,json=threadRoot,proto3" json:"thread_root,omitempty"`
	Seq           uint64                 `protobuf:"varint,2,opt,name=seq,proto3" json:"seq,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReplyRef) Reset() {
	*x = ReplyRef{}
	mi := &file_chatim_v1_message_links_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplyRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplyRef) ProtoMessage() {}

func (x *ReplyRef) ProtoReflect() protoreflect.Message {
	mi := &file_chatim_v1_message_links_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplyRef.ProtoReflect.Descriptor instead.
func (*ReplyRef) Descriptor() ([]byte, []int) {
	return file_chatim_v1_message_links_proto_rawDescGZIP(), []int{0}
}

func (x *ReplyRef) GetThreadRoot() uint64 {
	if x != nil {
		return x.ThreadRoot
	}
	return 0
}

func (x *ReplyRef) GetSeq() uint64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

type ForwardRef struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        string                 `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	ThreadRoot    uint64                 `protobuf:"varint,2,opt,name=thread_root,json=threadRoot,proto3" json:"thread_root,omitempty"`
	Seq           uint64                 `protobuf:"varint,3,opt,name=seq,proto3" json:"seq,omitempty"`
	Author        string                 `protobuf:"bytes,4,opt,name=author,proto3" json:"author,omitempty"`
	SentAt        *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=sent_at,json=sentAt,proto3" json:"sent_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ForwardRef) Reset() {
	*x = ForwardRef{}
	mi := &file_chatim_v1_message_links_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ForwardRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForwardRef) ProtoMessage() {}

func (x *ForwardRef) ProtoReflect() protoreflect.Message {
	mi := &file_chatim_v1_message_links_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForwardRef.ProtoReflect.Descriptor instead.
func (*ForwardRef) Descriptor() ([]byte, []int) {
	return file_chatim_v1_message_links_proto_rawDescGZIP(), []int{1}
}

func (x *ForwardRef) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *ForwardRef) GetThreadRoot() uint64 {
	if x != nil {
		return x.ThreadRoot
	}
	return 0
}

func (x *ForwardRef) GetSeq() uint64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *ForwardRef) GetAuthor() string {
	if x != nil {
		return x.Author
	}
	return ""
}

func (x *ForwardRef) GetSentAt() *timestamppb.Timestamp {
	if x != nil {
		return x.SentAt
	}
	return nil
}

type MentionTarget struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Kind          MentionKind            `protobuf:"varint,1,opt,name=kind,proto3,enum=chatim.v1.MentionKind" json:"kind,omitempty"`
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MentionTarget) Reset() {
	*x = MentionTarget{}
	mi := &file_chatim_v1_message_links_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MentionTarget) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MentionTarget) ProtoMessage() {}

func (x *MentionTarget) ProtoReflect() protoreflect.Message {
	mi := &file_chatim_v1_message_links_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MentionTarget.ProtoReflect.Descriptor instead.
func (*MentionTarget) Descriptor() ([]byte, []int) {
	return file_chatim_v1_message_links_proto_rawDescGZIP(), []int{2}
}

func (x *MentionTarget) GetKind() MentionKind {
	if x != nil {
		return x.Kind
	}
	return MentionKind_MENTION_KIND_UNSPECIFIED
}

func (x *MentionTarget) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type MentionSet struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Targets       []*MentionTarget       `protobuf:"bytes,1,rep,name=targets,proto3" json:"targets,omitempty"`
	All           bool                   `protobuf:"varint,2,opt,name=all,proto3" json:"all,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MentionSet) Reset() {
	*x = MentionSet{}
	mi := &file_chatim_v1_message_links_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MentionSet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MentionSet) ProtoMessage() {}

func (x *MentionSet) ProtoReflect() protoreflect.Message {
	mi := &file_chatim_v1_message_links_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MentionSet.ProtoReflect.Descriptor instead.
func (*MentionSet) Descriptor() ([]byte, []int) {
	return file_chatim_v1_message_links_proto_rawDescGZIP(), []int{3}
}

func (x *MentionSet) GetTargets() []*MentionTarget {
	if x != nil {
		return x.Targets
	}
	return nil
}

func (x *MentionSet) GetAll() bool {
	if x != nil {
		return x.All
	}
	return false
}

type ReplyPreview struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Seq           uint64                 `protobuf:"varint,1,opt,name=seq,proto3" json:"seq,omitempty"`
	Sender        string                 `protobuf:"bytes,2,opt,name=sender,proto3" json:"sender,omitempty"`
	Text          string                 `protobuf:"bytes,3,opt,name=text,proto3" json:"text,omitempty"`
	Deleted       bool                   `protobuf:"varint,4,opt,name=deleted,proto3" json:"deleted,omitempty"`
	Hidden        bool                   `protobuf:"varint,5,opt,name=hidden,proto3" json:"hidden,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReplyPreview) Reset() {
	*x = ReplyPreview{}
	mi := &file_chatim_v1_message_links_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplyPreview) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplyPreview) ProtoMessage() {}

func (x *ReplyPreview) ProtoReflect() protoreflect.Message {
	mi := &file_chatim_v1_message_links_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplyPreview.ProtoReflect.Descriptor instead.
func (*ReplyPreview) Descriptor() ([]byte, []int) {
	return file_chatim_v1_message_links_proto_rawDescGZIP(), []int{4}
}

func (x *ReplyPreview) GetSeq() uint64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *ReplyPreview) GetSender() string {
	if x != nil {
		return x.Sender
	}
	return ""
}

func (x *ReplyPreview) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *ReplyPreview) GetDeleted() bool {
	if x != nil {
		return x.Deleted
	}
	return false
}

func (x *ReplyPreview) GetHidden() bool {
	if x != nil {
		return x.Hidden
	}
	return false
}

type MentionGroup struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Since         *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=since,proto3" json:"since,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MentionGroup) Reset() {
	*x = MentionGroup{}
	mi := &file_chatim_v1_message_links_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MentionGroup) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MentionGroup) ProtoMessage() {}

func (x *MentionGroup) ProtoReflect() protoreflect.Message {
	mi := &file_chatim_v1_message_links_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MentionGroup.ProtoReflect.Descriptor instead.
func (*MentionGroup) Descriptor() ([]byte, []int) {
	return file_chatim_v1_message_links_proto_rawDescGZIP(), []int{5}
}

func (x *MentionGroup) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *MentionGroup) GetSince() *timestamppb.Timestamp {
	if x != nil {
		return x.Since
	}
	return nil
}

var File_chatim_v1_message_links_proto protoreflect.FileDescriptor

const file_chatim_v1_message_links_proto_rawDesc = "" +
	"\n" +
	"\x1dchatim/v1/message_links.proto\x12\tchatim.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"=\n" +
	"\bReplyRef\x12\x1f\n" +
	"\vthread_root\x18\x01 \x01(\x04R\n" +
	"threadRoot\x12\x10\n" +
	"\x03seq\x18\x02 \x01(\x04R\x03seq\"\xa5\x01\n" +
	"\n" +
	"ForwardRef\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\tR\x06roomId\x12\x1f\n" +
	"\vthread_root\x18\x02 \x01(\x04R\n" +
	"threadRoot\x12\x10\n" +
	"\x03seq\x18\x03 \x01(\x04R\x03seq\x12\x16\n" +
	"\x06author\x18\x04 \x01(\tR\x06author\x123\n" +
	"\asent_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\x06sentAt\"K\n" +
	"\rMentionTarget\x12*\n" +
	"\x04kind\x18\x01 \x01(\x0e2\x16.chatim.v1.MentionKindR\x04kind\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\"R\n" +
	"\n" +
	"MentionSet\x122\n" +
	"\atargets\x18\x01 \x03(\v2\x18.chatim.v1.MentionTargetR\atargets\x12\x10\n" +
	"\x03all\x18\x02 \x01(\bR\x03all\"~\n" +
	"\fReplyPreview\x12\x10\n" +
	"\x03seq\x18\x01 \x01(\x04R\x03seq\x12\x16\n" +
	"\x06sender\x18\x02 \x01(\tR\x06sender\x12\x12\n" +
	"\x04text\x18\x03 \x01(\tR\x04text\x12\x18\n" +
	"\adeleted\x18\x04 \x01(\bR\adeleted\x12\x16\n" +
	"\x06hidden\x18\x05 \x01(\bR\x06hidden\"P\n" +
	"\fMentionGroup\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x120\n" +
	"\x05since\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\x05since*Z\n" +
	"\vMentionKind\x12\x1c\n" +
	"\x18MENTION_KIND_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11MENTION_KIND_USER\x10\x01\x12\x16\n" +
	"\x12MENTION_KIND_GROUP\x10\x02B\xa2\x01\n" +
	"\rcom.chatim.v1B\x11MessageLinksProtoP\x01Z9github.com/ivannguyendev/chatim/pkg/pb/chatim/v1;chatimv1\xa2\x02\x03CXX\xaa\x02\tChatim.V1\xca\x02\tChatim\\V1\xe2\x02\x15Chatim\\V1\\GPBMetadata\xea\x02\n" +
	"Chatim::V1b\x06proto3"

var (
	file_chatim_v1_message_links_proto_rawDescOnce sync.Once
	file_chatim_v1_message_links_proto_rawDescData []byte
)

func file_chatim_v1_message_links_proto_rawDescGZIP() []byte {
	file_chatim_v1_message_links_proto_rawDescOnce.Do(func() {
		file_chatim_v1_message_links_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_chatim_v1_message_links_proto_rawDesc), len(file_chatim_v1_message_links_proto_rawDesc)))
	})
	return file_chatim_v1_message_links_proto_rawDescData
}

var file_chatim_v1_message_links_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_chatim_v1_message_links_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_chatim_v1_message_links_proto_goTypes = []any{
	(MentionKind)(0),              // 0: chatim.v1.MentionKind
	(*ReplyRef)(nil),              // 1: chatim.v1.ReplyRef
	(*ForwardRef)(nil),            // 2: chatim.v1.ForwardRef
	(*MentionTarget)(nil),         // 3: chatim.v1.MentionTarget
	(*MentionSet)(nil),            // 4: chatim.v1.MentionSet
	(*ReplyPreview)(nil),          // 5: chatim.v1.ReplyPreview
	(*MentionGroup)(nil),          // 6: chatim.v1.MentionGroup
	(*timestamppb.Timestamp)(nil), // 7: google.protobuf.Timestamp
}
var file_chatim_v1_message_links_proto_depIdxs = []int32{
	7, // 0: chatim.v1.ForwardRef.sent_at:type_name -> google.protobuf.Timestamp
	0, // 1: chatim.v1.MentionTarget.kind:type_name -> chatim.v1.MentionKind
	3, // 2: chatim.v1.MentionSet.targets:type_name -> chatim.v1.MentionTarget
	7, // 3: chatim.v1.MentionGroup.since:type_name -> google.protobuf.Timestamp
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_chatim_v1_message_links_proto_init() }
func file_chatim_v1_message_links_proto_init() {
	if File_chatim_v1_message_links_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_chatim_v1_message_links_proto_rawDesc), len(file_chatim_v1_message_links_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_chatim_v1_message_links_proto_goTypes,
		DependencyIndexes: file_chatim_v1_message_links_proto_depIdxs,
		EnumInfos:         file_chatim_v1_message_links_proto_enumTypes,
		MessageInfos:      file_chatim_v1_message_links_proto_msgTypes,
	}.Build()
	File_chatim_v1_message_links_proto = out.File
	file_chatim_v1_message_links_proto_goTypes = nil
	file_chatim_v1_message_links_proto_depIdxs = nil
}
