// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: chatim/v1/reactions_pins.proto

package chatimv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ReactionCount struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Emoji         string                 `protobuf:"bytes,1,opt,name=emoji,proto3" json:"emoji,omitempty"`
	Count         uint32                 `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReactionCount) Reset() {
	*x = ReactionCount{}
	mi := &file_chatim_v1_reactions_pins_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReactionCount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReactionCount) ProtoMessage() {}

func (x *ReactionCount) ProtoReflect() protoreflect.Message {
	mi := &file_chatim_v1_reactions_pins_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReactionCount.ProtoReflect.Descriptor instead.
func (*ReactionCount) Descriptor() ([]byte, []int) {
	return file_chatim_v1_reactions_pins_proto_rawDescGZIP(), []int{0}
}

func (x *ReactionCount) GetEmoji() string {
	if x != nil {
		return x.Emoji
	}
	return ""
}

func (x *ReactionCount) GetCount() uint32 {
	if x != nil {
		return x.Count
	}
	return 0
}

type ReactionSummary struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Counts        []*ReactionCount       `protobuf:"bytes,1,rep,name=counts,proto3" json:"counts,omitempty"`
	Version       uint64                 `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReactionSummary) Reset() {
	*x = ReactionSummary{}
	mi := &file_chatim_v1_reactions_pins_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReactionSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReactionSummary) ProtoMessage() {}

func (x *ReactionSummary) ProtoReflect() protoreflect.Message {
	mi := &file_chatim_v1_reactions_pins_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReactionSummary.ProtoReflect.Descriptor instead.
func (*ReactionSummary) Descriptor() ([]byte, []int) {
	return file_chatim_v1_reactions_pins_proto_rawDescGZIP(), []int{1}
}

func (x *ReactionSummary) GetCounts() []*ReactionCount {
	if x != nil {
		return x.Counts
	}
	return nil
}

func (x *ReactionSummary) GetVersion() uint64 {
	if x != nil {
		return x.Version
	}
	return 0
}

type Pin struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ThreadRoot    uint64                 `protobuf:"varint,1,opt,name=thread_root,json=threadRoot,proto3" json:"thread_root,omitempty"`
	Seq           uint64                 `protobuf:"varint,2,opt,name=seq,proto3" json:"seq,omitempty"`
	By            string                 `protobuf:"bytes,3,opt,name=by,proto3" json:"by,omitempty"`
	PinnedAt      *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=pinned_at,json=pinnedAt,proto3" json:"pinned_at,omitempty"`
	PinVersion    uint64                 `protobuf:"varint,5,opt,name=pin_version,json=pinVersion,proto3" json:"pin_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Pin) Reset() {
	*x = Pin{}
	mi := &file_chatim_v1_reactions_pins_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Pin) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pin) ProtoMessage() {}

func (x *Pin) ProtoReflect() protoreflect.Message {
	mi := &file_chatim_v1_reactions_pins_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pin.ProtoReflect.Descriptor instead.
func (*Pin) Descriptor() ([]byte, []int) {
	return file_chatim_v1_reactions_pins_proto_rawDescGZIP(), []int{2}
}

func (x *Pin) GetThreadRoot() uint64 {
	if x != nil {
		return x.ThreadRoot
	}
	return 0
}

func (x *Pin) GetSeq() uint64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *Pin) GetBy() string {
	if x != nil {
		return x.By
	}
	return ""
}

func (x *Pin) GetPinnedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.PinnedAt
	}
	return nil
}

func (x *Pin) GetPinVersion() uint64 {
	if x != nil {
		return x.PinVersion
	}
	return 0
}

type ReactMessageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        string                 `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	ThreadRoot    uint64                 `protobuf:"varint,2,opt,name=thread_root,json=threadRoot,proto3" json:"thread_root,omitempty"`
	Seq           uint64                 `protobuf:"varint,3,opt,name=seq,proto3" json:"seq,omitempty"`
	Emoji         string                 `protobuf:"bytes,4,opt,name=emoji,proto3" json:"emoji,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReactMessageRequest) Reset() {
	*x = ReactMessageRequest{}
	mi := &file_chatim_v1_reactions_pins_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReactMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReactMessageRequest) ProtoMessage() {}

func (x *ReactMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chatim_v1_reactions_pins_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReactMessageRequest.ProtoReflect.Descriptor instead.
func (*ReactMessageRequest) Descriptor() ([]byte, []int) {
	return file_chatim_v1_reactions_pins_proto_rawDescGZIP(), []int{3}
}

func (x *ReactMessageRequest) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *ReactMessageRequest) GetThreadRoot() uint64 {
	if x != nil {
		return x.ThreadRoot
	}
	return 0
}

func (x *ReactMessageRequest) GetSeq() uint64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *ReactMessageRequest) GetEmoji() string {
	if x != nil {
		return x.Emoji
	}
	return ""
}

type ReactMessageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Change        uint32                 `protobuf:"varint,1,opt,name=change,proto3" json:"change,omitempty"`
	Reactions     *ReactionSummary       `protobuf:"bytes,2,opt,name=reactions,proto3" json:"reactions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReactMessageResponse) Reset() {
	*x = ReactMessageResponse{}
	mi := &file_chatim_v1_reactions_pins_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReactMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReactMessageResponse) ProtoMessage() {}

func (x *ReactMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chatim_v1_reactions_pins_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReactMessageResponse.ProtoReflect.Descriptor instead.
func (*ReactMessageResponse) Descriptor() ([]byte, []int) {
	return file_chatim_v1_reactions_pins_proto_rawDescGZIP(), []int{4}
}

func (x *ReactMessageResponse) GetChange() uint32 {
	if x != nil {
		return x.Change
	}
	return 0
}

func (x *ReactMessageResponse) GetReactions() *ReactionSummary {
	if x != nil {
		return x.Reactions
	}
	return nil
}

type PinMessageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        string                 `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	ThreadRoot    uint64                 `protobuf:"varint,2,opt,name=thread_root,json=threadRoot,proto3" json:"thread_root,omitempty"`
	Seq           uint64                 `protobuf:"varint,3,opt,name=seq,proto3" json:"seq,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PinMessageRequest) Reset() {
	*x = PinMessageRequest{}
	mi := &file_chatim_v1_reactions_pins_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PinMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PinMessageRequest) ProtoMessage() {}

func (x *PinMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chatim_v1_reactions_pins_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PinMessageRequest.ProtoReflect.Descriptor instead.
func (*PinMessageRequest) Descriptor() ([]byte, []int) {
	return file_chatim_v1_reactions_pins_proto_rawDescGZIP(), []int{5}
}

func (x *PinMessageRequest) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *PinMessageRequest) GetThreadRoot() uint64 {
	if x != nil {
		return x.ThreadRoot
	}
	return 0
}

func (x *PinMessageRequest) GetSeq() uint64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

type PinMessageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PinVersion    uint64                 `protobuf:"varint,1,opt,name=pin_version,json=pinVersion,proto3" json:"pin_version,omitempty"`
	Pins          []*Pin                 `protobuf:"bytes,2,rep,name=pins,proto3" json:"pins,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PinMessageResponse) Reset() {
	*x = PinMessageResponse{}
	mi := &file_chatim_v1_reactions_pins_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PinMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PinMessageResponse) ProtoMessage() {}

func (x *PinMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chatim_v1_reactions_pins_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PinMessageResponse.ProtoReflect.Descriptor instead.
func (*PinMessageResponse) Descriptor() ([]byte, []int) {
	return file_chatim_v1_reactions_pins_proto_rawDescGZIP(), []int{6}
}

func (x *PinMessageResponse) GetPinVersion() uint64 {
	if x != nil {
		return x.PinVersion
	}
	return 0
}

func (x *PinMessageResponse) GetPins() []*Pin {
	if x != nil {
		return x.Pins
	}
	return nil
}

type UnpinMessageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        string                 `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	ThreadRoot    uint64                 `protobuf:"varint,2,opt,name=thread_root,json=threadRoot,proto3" json:"thread_root,omitempty"`
	Seq           uint64                 `protobuf:"varint,3,opt,name=seq,proto3" json:"seq,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnpinMessageRequest) Reset() {
	*x = UnpinMessageRequest{}
	mi := &file_chatim_v1_reactions_pins_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnpinMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnpinMessageRequest) ProtoMessage() {}

func (x *UnpinMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chatim_v1_reactions_pins_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnpinMessageRequest.ProtoReflect.Descriptor instead.
func (*UnpinMessageRequest) Descriptor() ([]byte, []int) {
	return file_chatim_v1_reactions_pins_proto_rawDescGZIP(), []int{7}
}

func (x *UnpinMessageRequest) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *UnpinMessageRequest) GetThreadRoot() uint64 {
	if x != nil {
		return x.ThreadRoot
	}
	return 0
}

func (x *UnpinMessageRequest) GetSeq() uint64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

type UnpinMessageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PinVersion    uint64                 `protobuf:"varint,1,opt,name=pin_version,json=pinVersion,proto3" json:"pin_version,omitempty"`
	Pins          []*Pin                 `protobuf:"bytes,2,rep,name=pins,proto3" json:"pins,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnpinMessageResponse) Reset() {
	*x = UnpinMessageResponse{}
	mi := &file_chatim_v1_reactions_pins_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnpinMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnpinMessageResponse) ProtoMessage() {}

func (x *UnpinMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chatim_v1_reactions_pins_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnpinMessageResponse.ProtoReflect.Descriptor instead.
func (*UnpinMessageResponse) Descriptor() ([]byte, []int) {
	return file_chatim_v1_reactions_pins_proto_rawDescGZIP(), []int{8}
}

func (x *UnpinMessageResponse) GetPinVersion() uint64 {
	if x != nil {
		return x.PinVersion
	}
	return 0
}

func (x *UnpinMessageResponse) GetPins() []*Pin {
	if x != nil {
		return x.Pins
	}
	return nil
}

type GetReactionSettingsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetReactionSettingsRequest) Reset() {
	*x = GetReactionSettingsRequest{}
	mi := &file_chatim_v1_reactions_pins_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetReactionSettingsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetReactionSettingsRequest) ProtoMessage() {}

func (x *GetReactionSettingsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chatim_v1_reactions_pins_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetReactionSettingsRequest.ProtoReflect.Descriptor instead.
func (*GetReactionSettingsRequest) Descriptor() ([]byte, []int) {
	return file_chatim_v1_reactions_pins_proto_rawDescGZIP(), []int{9}
}

type GetReactionSettingsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Emojis        []string               `protobuf:"bytes,1,rep,name=emojis,proto3" json:"emojis,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetReactionSettingsResponse) Reset() {
	*x = GetReactionSettingsResponse{}
	mi := &file_chatim_v1_reactions_pins_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetReactionSettingsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetReactionSettingsResponse) ProtoMessage() {}

func (x *GetReactionSettingsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chatim_v1_reactions_pins_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetReactionSettingsResponse.ProtoReflect.Descriptor instead.
func (*GetReactionSettingsResponse) Descriptor() ([]byte, []int) {
	return file_chatim_v1_reactions_pins_proto_rawDescGZIP(), []int{10}
}

func (x *GetReactionSettingsResponse) GetEmojis() []string {
	if x != nil {
		return x.Emojis
	}
	return nil
}

var File_chatim_v1_reactions_pins_proto protoreflect.FileDescriptor

const file_chatim_v1_reactions_pins_proto_rawDesc = "" +
	"\n" +
	"\x1echatim/v1/reactions_pins.proto\x12\tchatim.v1\x1a\x1fgoogle/protobuf/timestamp.proto\";\n" +
	"\rReactionCount\x12\x14\n" +
	"\x05emoji\x18\x01 \x01(\tR\x05emoji\x12\x14\n" +
	"\x05count\x18\x02 \x01(\rR\x05count\"]\n" +
	"\x0fReactionSummary\x120\n" +
	"\x06counts\x18\x01 \x03(\v2\x18.chatim.v1.ReactionCountR\x06counts\x12\x18\n" +
	"\aversion\x18\x02 \x01(\x04R\aversion\"\xa2\x01\n" +
	"\x03Pin\x12\x1f\n" +
	"\vthread_root\x18\x01 \x01(\x04R\n" +
	"threadRoot\x12\x10\n" +
	"\x03seq\x18\x02 \x01(\x04R\x03seq\x12\x0e\n" +
	"\x02by\x18\x03 \x01(\tR\x02by\x127\n" +
	"\tpinned_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\bpinnedAt\x12\x1f\n" +
	"\vpin_version\x18\x05 \x01(\x04R\n" +
	"pinVersion\"w\n" +
	"\x13ReactMessageRequest\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\tR\x06roomId\x12\x1f\n" +
	"\vthread_root\x18\x02 \x01(\x04R\n" +
	"threadRoot\x12\x10\n" +
	"\x03seq\x18\x03 \x01(\x04R\x03seq\x12\x14\n" +
	"\x05emoji\x18\x04 \x01(\tR\x05emoji\"h\n" +
	"\x14ReactMessageResponse\x12\x16\n" +
	"\x06change\x18\x01 \x01(\rR\x06change\x128\n" +
	"\treactions\x18\x02 \x01(\v2\x1a.chatim.v1.ReactionSummaryR\treactions\"_\n" +
	"\x11PinMessageRequest\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\tR\x06roomId\x12\x1f\n" +
	"\vthread_root\x18\x02 \x01(\x04R\n" +
	"threadRoot\x12\x10\n" +
	"\x03seq\x18\x03 \x01(\x04R\x03seq\"Y\n" +
	"\x12PinMessageResponse\x12\x1f\n" +
	"\vpin_version\x18\x01 \x01(\x04R\n" +
	"pinVersion\x12\"\n" +
	"\x04pins\x18\x02 \x03(\v2\x0e.chatim.v1.PinR\x04pins\"a\n" +
	"\x13UnpinMessageRequest\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\tR\x06roomId\x12\x1f\n" +
	"\vthread_root\x18\x02 \x01(\x04R\n" +
	"threadRoot\x12\x10\n" +
	"\x03seq\x18\x03 \x01(\x04R\x03seq\"[\n" +
	"\x14UnpinMessageResponse\x12\x1f\n" +
	"\vpin_version\x18\x01 \x01(\x04R\n" +
	"pinVersion\x12\"\n" +
	"\x04pins\x18\x02 \x03(\v2\x0e.chatim.v1.PinR\x04pins\"\x1c\n" +
	"\x1aGetReactionSettingsRequest\"5\n" +
	"\x1bGetReactionSettingsResponse\x12\x16\n" +
	"\x06emojis\x18\x01 \x03(\tR\x06emojisB\xa3\x01\n" +
	"\rcom.chatim.v1B\x12ReactionsPinsProtoP\x01Z9github.com/ivannguyendev/chatim/pkg/pb/chatim/v1;chatimv1\xa2\x02\x03CXX\xaa\x02\tChatim.V1\xca\x02\tChatim\\V1\xe2\x02\x15Chatim\\V1\\GPBMetadata\xea\x02\n" +
	"Chatim::V1b\x06proto3"

var (
	file_chatim_v1_reactions_pins_proto_rawDescOnce sync.Once
	file_chatim_v1_reactions_pins_proto_rawDescData []byte
)

func file_chatim_v1_reactions_pins_proto_rawDescGZIP() []byte {
	file_chatim_v1_reactions_pins_proto_rawDescOnce.Do(func() {
		file_chatim_v1_reactions_pins_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_chatim_v1_reactions_pins_proto_rawDesc), len(file_chatim_v1_reactions_pins_proto_rawDesc)))
	})
	return file_chatim_v1_reactions_pins_proto_rawDescData
}

var file_chatim_v1_reactions_pins_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_chatim_v1_reactions_pins_proto_goTypes = []any{
	(*ReactionCount)(nil),               // 0: chatim.v1.ReactionCount
	(*ReactionSummary)(nil),             // 1: chatim.v1.ReactionSummary
	(*Pin)(nil),                         // 2: chatim.v1.Pin
	(*ReactMessageRequest)(nil),         // 3: chatim.v1.ReactMessageRequest
	(*ReactMessageResponse)(nil),        // 4: chatim.v1.ReactMessageResponse
	(*PinMessageRequest)(nil),           // 5: chatim.v1.PinMessageRequest
	(*PinMessageResponse)(nil),          // 6: chatim.v1.PinMessageResponse
	(*UnpinMessageRequest)(nil),         // 7: chatim.v1.UnpinMessageRequest
	(*UnpinMessageResponse)(nil),        // 8: chatim.v1.UnpinMessageResponse
	(*GetReactionSettingsRequest)(nil),  // 9: chatim.v1.GetReactionSettingsRequest
	(*GetReactionSettingsResponse)(nil), // 10: chatim.v1.GetReactionSettingsResponse
	(*timestamppb.Timestamp)(nil),       // 11: google.protobuf.Timestamp
}
var file_chatim_v1_reactions_pins_proto_depIdxs = []int32{
	0,  // 0: chatim.v1.ReactionSummary.counts:type_name -> chatim.v1.ReactionCount
	11, // 1: chatim.v1.Pin.pinned_at:type_name -> google.protobuf.Timestamp
	1,  // 2: chatim.v1.ReactMessageResponse.reactions:type_name -> chatim.v1.ReactionSummary
	2,  // 3: chatim.v1.PinMessageResponse.pins:type_name -> chatim.v1.Pin
	2,  // 4: chatim.v1.UnpinMessageResponse.pins:type_name -> chatim.v1.Pin
	5,  // [5:5] is the sub-list for method output_type
	5,  // [5:5] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_chatim_v1_reactions_pins_proto_init() }
func file_chatim_v1_reactions_pins_proto_init() {
	if File_chatim_v1_reactions_pins_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_chatim_v1_reactions_pins_proto_rawDesc), len(file_chatim_v1_reactions_pins_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_chatim_v1_reactions_pins_proto_goTypes,
		DependencyIndexes: file_chatim_v1_reactions_pins_proto_depIdxs,
		MessageInfos:      file_chatim_v1_reactions_pins_proto_msgTypes,
	}.Build()
	File_chatim_v1_reactions_pins_proto = out.File
	file_chatim_v1_reactions_pins_proto_goTypes = nil
	file_chatim_v1_reactions_pins_proto_depIdxs = nil
}
