// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: chatim/v1/replies_bookmarks_mentions.proto

package chatimv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SetBookmarkRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        string                 `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	ThreadRoot    uint64                 `protobuf:"varint,2,opt,name=thread_root,json=threadRoot,proto3" json:"thread_root,omitempty"`
	Seq           uint64                 `protobuf:"varint,3,opt,name=seq,proto3" json:"seq,omitempty"`
	On            bool                   `protobuf:"varint,4,opt,name=on,proto3" json:"on,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetBookmarkRequest) Reset() {
	*x = SetBookmarkRequest{}
	mi := &file_chatim_v1_replies_bookmarks_mentions_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetBookmarkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetBookmarkRequest) ProtoMessage() {}

func (x *SetBookmarkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chatim_v1_replies_bookmarks_mentions_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetBookmarkRequest.ProtoReflect.Descriptor instead.
func (*SetBookmarkRequest) Descriptor() ([]byte, []int) {
	return file_chatim_v1_replies_bookmarks_mentions_proto_rawDescGZIP(), []int{0}
}

func (x *SetBookmarkRequest) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *SetBookmarkRequest) GetThreadRoot() uint64 {
	if x != nil {
		return x.ThreadRoot
	}
	return 0
}

func (x *SetBookmarkRequest) GetSeq() uint64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *SetBookmarkRequest) GetOn() bool {
	if x != nil {
		return x.On
	}
	return false
}

type SetBookmarkResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Changed       bool                   `protobuf:"varint,1,opt,name=changed,proto3" json:"changed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetBookmarkResponse) Reset() {
	*x = SetBookmarkResponse{}
	mi := &file_chatim_v1_replies_bookmarks_mentions_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetBookmarkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetBookmarkResponse) ProtoMessage() {}

func (x *SetBookmarkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chatim_v1_replies_bookmarks_mentions_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetBookmarkResponse.ProtoReflect.Descriptor instead.
func (*SetBookmarkResponse) Descriptor() ([]byte, []int) {
	return file_chatim_v1_replies_bookmarks_mentions_proto_rawDescGZIP(), []int{1}
}

func (x *SetBookmarkResponse) GetChanged() bool {
	if x != nil {
		return x.Changed
	}
	return false
}

type GetRepliesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        string                 `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	Seq           uint64                 `protobuf:"varint,2,opt,name=seq,proto3" json:"seq,omitempty"`
	After         uint64                 `protobuf:"varint,3,opt,name=after,proto3" json:"after,omitempty"`
	Limit         uint32                 `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRepliesRequest) Reset() {
	*x = GetRepliesRequest{}
	mi := &file_chatim_v1_replies_bookmarks_mentions_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRepliesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRepliesRequest) ProtoMessage() {}

func (x *GetRepliesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chatim_v1_replies_bookmarks_mentions_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRepliesRequest.ProtoReflect.Descriptor instead.
func (*GetRepliesRequest) Descriptor() ([]byte, []int) {
	return file_chatim_v1_replies_bookmarks_mentions_proto_rawDescGZIP(), []int{2}
}

func (x *GetRepliesRequest) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *GetRepliesRequest) GetSeq() uint64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *GetRepliesRequest) GetAfter() uint64 {
	if x != nil {
		return x.After
	}
	return 0
}

func (x *GetRepliesRequest) GetLimit() uint32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type GetRepliesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Messages      []*Message             `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"`
	Next          uint64                 `protobuf:"varint,2,opt,name=next,proto3" json:"next,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRepliesResponse) Reset() {
	*x = GetRepliesResponse{}
	mi := &file_chatim_v1_replies_bookmarks_mentions_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRepliesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRepliesResponse) ProtoMessage() {}

func (x *GetRepliesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chatim_v1_replies_bookmarks_mentions_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRepliesResponse.ProtoReflect.Descriptor instead.
func (*GetRepliesResponse) Descriptor() ([]byte, []int) {
	return file_chatim_v1_replies_bookmarks_mentions_proto_rawDescGZIP(), []int{3}
}

func (x *GetRepliesResponse) GetMessages() []*Message {
	if x != nil {
		return x.Messages
	}
	return nil
}

func (x *GetRepliesResponse) GetNext() uint64 {
	if x != nil {
		return x.Next
	}
	return 0
}

type BookmarkItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       *Message               `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Available     bool                   `protobuf:"varint,2,opt,name=available,proto3" json:"available,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BookmarkItem) Reset() {
	*x = BookmarkItem{}
	mi := &file_chatim_v1_replies_bookmarks_mentions_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BookmarkItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BookmarkItem) ProtoMessage() {}

func (x *BookmarkItem) ProtoReflect() protoreflect.Message {
	mi := &file_chatim_v1_replies_bookmarks_mentions_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BookmarkItem.ProtoReflect.Descriptor instead.
func (*BookmarkItem) Descriptor() ([]byte, []int) {
	return file_chatim_v1_replies_bookmarks_mentions_proto_rawDescGZIP(), []int{4}
}

func (x *BookmarkItem) GetMessage() *Message {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *BookmarkItem) GetAvailable() bool {
	if x != nil {
		return x.Available
	}
	return false
}

type ListBookmarksRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Before        string                 `protobuf:"bytes,1,opt,name=before,proto3" json:"before,omitempty"`
	Limit         uint32                 `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListBookmarksRequest) Reset() {
	*x = ListBookmarksRequest{}
	mi := &file_chatim_v1_replies_bookmarks_mentions_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListBookmarksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBookmarksRequest) ProtoMessage() {}

func (x *ListBookmarksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chatim_v1_replies_bookmarks_mentions_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBookmarksRequest.ProtoReflect.Descriptor instead.
func (*ListBookmarksRequest) Descriptor() ([]byte, []int) {
	return file_chatim_v1_replies_bookmarks_mentions_proto_rawDescGZIP(), []int{5}
}

func (x *ListBookmarksRequest) GetBefore() string {
	if x != nil {
		return x.Before
	}
	return ""
}

func (x *ListBookmarksRequest) GetLimit() uint32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type ListBookmarksResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*BookmarkItem        `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	Next          string                 `protobuf:"bytes,2,opt,name=next,proto3" json:"next,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListBookmarksResponse) Reset() {
	*x = ListBookmarksResponse{}
	mi := &file_chatim_v1_replies_bookmarks_mentions_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListBookmarksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBookmarksResponse) ProtoMessage() {}

func (x *ListBookmarksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chatim_v1_replies_bookmarks_mentions_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBookmarksResponse.ProtoReflect.Descriptor instead.
func (*ListBookmarksResponse) Descriptor() ([]byte, []int) {
	return file_chatim_v1_replies_bookmarks_mentions_proto_rawDescGZIP(), []int{6}
}

func (x *ListBookmarksResponse) GetItems() []*BookmarkItem {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *ListBookmarksResponse) GetNext() string {
	if x != nil {
		return x.Next
	}
	return ""
}

type ListMentionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Groups        []*MentionGroup        `protobuf:"bytes,1,rep,name=groups,proto3" json:"groups,omitempty"`
	Before        string                 `protobuf:"bytes,2,opt,name=before,proto3" json:"before,omitempty"`
	Limit         uint32                 `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMentionsRequest) Reset() {
	*x = ListMentionsRequest{}
	mi := &file_chatim_v1_replies_bookmarks_mentions_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMentionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMentionsRequest) ProtoMessage() {}

func (x *ListMentionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chatim_v1_replies_bookmarks_mentions_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMentionsRequest.ProtoReflect.Descriptor instead.
func (*ListMentionsRequest) Descriptor() ([]byte, []int) {
	return file_chatim_v1_replies_bookmarks_mentions_proto_rawDescGZIP(), []int{7}
}

func (x *ListMentionsRequest) GetGroups() []*MentionGroup {
	if x != nil {
		return x.Groups
	}
	return nil
}

func (x *ListMentionsRequest) GetBefore() string {
	if x != nil {
		return x.Before
	}
	return ""
}

func (x *ListMentionsRequest) GetLimit() uint32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type ListMentionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Messages      []*Message             `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"`
	Next          string                 `protobuf:"bytes,2,opt,name=next,proto3" json:"next,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMentionsResponse) Reset() {
	*x = ListMentionsResponse{}
	mi := &file_chatim_v1_replies_bookmarks_mentions_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMentionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMentionsResponse) ProtoMessage() {}

func (x *ListMentionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chatim_v1_replies_bookmarks_mentions_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMentionsResponse.ProtoReflect.Descriptor instead.
func (*ListMentionsResponse) Descriptor() ([]byte, []int) {
	return file_chatim_v1_replies_bookmarks_mentions_proto_rawDescGZIP(), []int{8}
}

func (x *ListMentionsResponse) GetMessages() []*Message {
	if x != nil {
		return x.Messages
	}
	return nil
}

func (x *ListMentionsResponse) GetNext() string {
	if x != nil {
		return x.Next
	}
	return ""
}

var File_chatim_v1_replies_bookmarks_mentions_proto protoreflect.FileDescriptor

const file_chatim_v1_replies_bookmarks_mentions_proto_rawDesc = "" +
	"\n" +
	"*chatim/v1/replies_bookmarks_mentions.proto\x12\tchatim.v1\x1a\x14chatim/v1/core.proto\x1a\x1dchatim/v1/message_links.proto\"p\n" +
	"\x12SetBookmarkRequest\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\tR\x06roomId\x12\x1f\n" +
	"\vthread_root\x18\x02 \x01(\x04R\n" +
	"threadRoot\x12\x10\n" +
	"\x03seq\x18\x03 \x01(\x04R\x03seq\x12\x0e\n" +
	"\x02on\x18\x04 \x01(\bR\x02on\"/\n" +
	"\x13SetBookmarkResponse\x12\x18\n" +
	"\achanged\x18\x01 \x01(\bR\achanged\"j\n" +
	"\x11GetRepliesRequest\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\tR\x06roomId\x12\x10\n" +
	"\x03seq\x18\x02 \x01(\x04R\x03seq\x12\x14\n" +
	"\x05after\x18\x03 \x01(\x04R\x05after\x12\x14\n" +
	"\x05limit\x18\x04 \x01(\rR\x05limit\"X\n" +
	"\x12GetRepliesResponse\x12.\n" +
	"\bmessages\x18\x01 \x03(\v2\x12.chatim.v1.MessageR\bmessages\x12\x12\n" +
	"\x04next\x18\x02 \x01(\x04R\x04next\"Z\n" +
	"\fBookmarkItem\x12,\n" +
	"\amessage\x18\x01 \x01(\v2\x12.chatim.v1.MessageR\amessage\x12\x1c\n" +
	"\tavailable\x18\x02 \x01(\bR\tavailable\"D\n" +
	"\x14ListBookmarksRequest\x12\x16\n" +
	"\x06before\x18\x01 \x01(\tR\x06before\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\rR\x05limit\"Z\n" +
	"\x15ListBookmarksResponse\x12-\n" +
	"\x05items\x18\x01 \x03(\v2\x17.chatim.v1.BookmarkItemR\x05items\x12\x12\n" +
	"\x04next\x18\x02 \x01(\tR\x04next\"t\n" +
	"\x13ListMentionsRequest\x12/\n" +
	"\x06groups\x18\x01 \x03(\v2\x17.chatim.v1.MentionGroupR\x06groups\x12\x16\n" +
	"\x06before\x18\x02 \x01(\tR\x06before\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\rR\x05limit\"Z\n" +
	"\x14ListMentionsResponse\x12.\n" +
	"\bmessages\x18\x01 \x03(\v2\x12.chatim.v1.MessageR\bmessages\x12\x12\n" +
	"\x04next\x18\x02 \x01(\tR\x04nextB\xae\x01\n" +
	"\rcom.chatim.v1B\x1dRepliesBookmarksMentionsProtoP\x01Z9github.com/ivannguyendev/chatim/pkg/pb/chatim/v1;chatimv1\xa2\x02\x03CXX\xaa\x02\tChatim.V1\xca\x02\tChatim\\V1\xe2\x02\x15Chatim\\V1\\GPBMetadata\xea\x02\n" +
	"Chatim::V1b\x06proto3"

var (
	file_chatim_v1_replies_bookmarks_mentions_proto_rawDescOnce sync.Once
	file_chatim_v1_replies_bookmarks_mentions_proto_rawDescData []byte
)

func file_chatim_v1_replies_bookmarks_mentions_proto_rawDescGZIP() []byte {
	file_chatim_v1_replies_bookmarks_mentions_proto_rawDescOnce.Do(func() {
		file_chatim_v1_replies_bookmarks_mentions_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_chatim_v1_replies_bookmarks_mentions_proto_rawDesc), len(file_chatim_v1_replies_bookmarks_mentions_proto_rawDesc)))
	})
	return file_chatim_v1_replies_bookmarks_mentions_proto_rawDescData
}

var file_chatim_v1_replies_bookmarks_mentions_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_chatim_v1_replies_bookmarks_mentions_proto_goTypes = []any{
	(*SetBookmarkRequest)(nil),    // 0: chatim.v1.SetBookmarkRequest
	(*SetBookmarkResponse)(nil),   // 1: chatim.v1.SetBookmarkResponse
	(*GetRepliesRequest)(nil),     // 2: chatim.v1.GetRepliesRequest
	(*GetRepliesResponse)(nil),    // 3: chatim.v1.GetRepliesResponse
	(*BookmarkItem)(nil),          // 4: chatim.v1.BookmarkItem
	(*ListBookmarksRequest)(nil),  // 5: chatim.v1.ListBookmarksRequest
	(*ListBookmarksResponse)(nil), // 6: chatim.v1.ListBookmarksResponse
	(*ListMentionsRequest)(nil),   // 7: chatim.v1.ListMentionsRequest
	(*ListMentionsResponse)(nil),  // 8: chatim.v1.ListMentionsResponse
	(*Message)(nil),               // 9: chatim.v1.Message
	(*MentionGroup)(nil),          // 10: chatim.v1.MentionGroup
}
var file_chatim_v1_replies_bookmarks_mentions_proto_depIdxs = []int32{
	9,  // 0: chatim.v1.GetRepliesResponse.messages:type_name -> chatim.v1.Message
	9,  // 1: chatim.v1.BookmarkItem.message:type_name -> chatim.v1.Message
	4,  // 2: chatim.v1.ListBookmarksResponse.items:type_name -> chatim.v1.BookmarkItem
	10, // 3: chatim.v1.ListMentionsRequest.groups:type_name -> chatim.v1.MentionGroup
	9,  // 4: chatim.v1.ListMentionsResponse.messages:type_name -> chatim.v1.Message
	5,  // [5:5] is the sub-list for method output_type
	5,  // [5:5] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_chatim_v1_replies_bookmarks_mentions_proto_init() }
func file_chatim_v1_replies_bookmarks_mentions_proto_init() {
	if File_chatim_v1_replies_bookmarks_mentions_proto != nil {
		return
	}
	file_chatim_v1_core_proto_init()
	file_chatim_v1_message_links_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_chatim_v1_replies_bookmarks_mentions_proto_rawDesc), len(file_chatim_v1_replies_bookmarks_mentions_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_chatim_v1_replies_bookmarks_mentions_proto_goTypes,
		DependencyIndexes: file_chatim_v1_replies_bookmarks_mentions_proto_depIdxs,
		MessageInfos:      file_chatim_v1_replies_bookmarks_mentions_proto_msgTypes,
	}.Build()
	File_chatim_v1_replies_bookmarks_mentions_proto = out.File
	file_chatim_v1_replies_bookmarks_mentions_proto_goTypes = nil
	file_chatim_v1_replies_bookmarks_mentions_proto_depIdxs = nil
}
