package config_test

import "testing"

const testMongoURI = "mongodb://chatim-mongodb:27017/?replicaSet=rs0"

var envKeys = []string{
	"CORE_ID", "CORE_GRPC_ADDR", "CORE_ADVERTISE_ADDR", "CORE_ADMIN_ADDR",
	"MONGO_URI", "MONGO_DB", "MONGO_USER", "MONGO_PASSWORD", "MONGO_AUTH_SOURCE", "REDIS_ADDR", "REDIS_DB", "REDIS_PASSWORD", "NATS_URL",
	"REDIS_DEDUPE_ADDR", "REDIS_DEDUPE_DB", "REDIS_DEDUPE_PASSWORD",
	"CORE_CONNECT_TIMEOUT", "CORE_REQUEST_DEADLINE", "CORE_SLOW_RPC", "CORE_QUEUE_WAIT", "CORE_MAX_INFLIGHT",
	"CORE_DRAIN_DELAY", "CORE_GRPC_SHUTDOWN", "CORE_PUBLISHER_DRAIN", "CORE_SHUTDOWN_BUDGET",
	"CID_PENDING_TTL", "CID_COMMITTED_TTL", "REDIS_OP_TIMEOUT", "REDIS_COOLDOWN",
	"CID_BATCH_SHARDS", "CID_BATCH_MAX_KEYS", "CID_BATCH_QUEUE",
	"FLUSH_SHARDS", "FLUSH_WINDOW", "FLUSH_MAX_BATCH", "FLUSH_QUEUE", "FLUSH_INSERT_TIMEOUT",
	"ACTOR_MAILBOX", "ACTOR_IDLE", "ACTOR_MAX_GROUP", "ACTOR_MAX",
	"PUB_SHARDS", "PUB_QUEUE", "PUB_MAX_PENDING", "PUB_ACK_TIMEOUT",
	"EVT_STREAM", "EVT_SUBJECT_ROOT", "EVT_LIVE_ROOT", "EVT_STREAM_REPLICAS", "EVT_STREAM_MAX_AGE", "EVT_STREAM_DUPLICATES",
	"WORK_STREAM", "WORK_SUBJECT_ROOT", "WORK_PARTITIONS", "WORK_MAX_AGE", "WORK_DUPLICATES",
	"SLOT_TICK", "SLOT_HEARTBEAT_TTL", "SLOT_LEASE_TTL", "SLOT_HOOK_TIMEOUT",
	"RECONCILE_ENABLED", "RECONCILE_DELAY", "RECONCILE_WINDOW", "RECONCILE_BATCH", "RECONCILE_CONFIRM_EVERY", "RECONCILE_DRAIN", "RECONCILE_ROOM_CACHE", "EVT_ACK_MARK_TTL",
	"WORK_FETCH_BATCH", "WORK_FETCH_WAIT", "WORK_RETRY_DELAY", "WORK_DRAIN",
}

var overrides = map[string]string{
	"CORE_ID": "core-a", "CORE_GRPC_ADDR": ":7000", "CORE_ADVERTISE_ADDR": "10.0.0.5:7000", "CORE_ADMIN_ADDR": "127.0.0.1:7090",
	"MONGO_URI": "mongodb://m1,m2/?replicaSet=rs1", "MONGO_DB": "chatim_it",
	"MONGO_USER": "core-user", "MONGO_PASSWORD": "mongo-pw", "MONGO_AUTH_SOURCE": "chatim", "REDIS_ADDR": "redis:6380", "REDIS_DB": "3",
	"REDIS_PASSWORD": "state-pw", "REDIS_DEDUPE_ADDR": "dedupe:6381", "REDIS_DEDUPE_DB": "2", "REDIS_DEDUPE_PASSWORD": "dedupe-pw",
	"NATS_URL": "nats://n1:4222", "CORE_CONNECT_TIMEOUT": "4s", "CORE_REQUEST_DEADLINE": "2s", "CORE_SLOW_RPC": "750ms", "CORE_QUEUE_WAIT": "10ms",
	"CORE_MAX_INFLIGHT": "100", "CORE_DRAIN_DELAY": "1s", "CORE_GRPC_SHUTDOWN": "4s", "CORE_PUBLISHER_DRAIN": "3s",
	"CORE_SHUTDOWN_BUDGET": "20s", "CID_PENDING_TTL": "8s", "CID_COMMITTED_TTL": "30m", "REDIS_OP_TIMEOUT": "50ms",
	"REDIS_COOLDOWN": "2s", "CID_BATCH_SHARDS": "2", "CID_BATCH_MAX_KEYS": "64", "CID_BATCH_QUEUE": "512", "FLUSH_SHARDS": "8", "FLUSH_WINDOW": "5ms", "FLUSH_MAX_BATCH": "512", "FLUSH_QUEUE": "256",
	"FLUSH_INSERT_TIMEOUT": "500ms", "ACTOR_MAILBOX": "64", "ACTOR_IDLE": "1m", "ACTOR_MAX_GROUP": "32", "ACTOR_MAX": "5000",
	"PUB_SHARDS": "2", "PUB_QUEUE": "512", "PUB_MAX_PENDING": "128", "PUB_ACK_TIMEOUT": "1s",
	"EVT_STREAM": "CHATIM_EVT_IT", "EVT_SUBJECT_ROOT": "evt_it", "EVT_LIVE_ROOT": "live_it",
	"EVT_STREAM_REPLICAS": "3", "EVT_STREAM_MAX_AGE": "48h", "EVT_STREAM_DUPLICATES": "5m",
	"WORK_STREAM": "CHATIM_WORK_IT", "WORK_SUBJECT_ROOT": "work_it", "WORK_PARTITIONS": "16", "WORK_MAX_AGE": "1h", "WORK_DUPLICATES": "3m",
	"SLOT_TICK": "500ms", "SLOT_HEARTBEAT_TTL": "3s",
	"SLOT_LEASE_TTL": "6s", "SLOT_HOOK_TIMEOUT": "200ms",
	"RECONCILE_ENABLED": "false", "RECONCILE_DELAY": "20s", "RECONCILE_WINDOW": "64", "RECONCILE_BATCH": "32", "RECONCILE_CONFIRM_EVERY": "2s",
	"RECONCILE_DRAIN": "500ms", "RECONCILE_ROOM_CACHE": "128", "EVT_ACK_MARK_TTL": "30m",
	"WORK_FETCH_BATCH": "64", "WORK_FETCH_WAIT": "500ms", "WORK_RETRY_DELAY": "2s", "WORK_DRAIN": "500ms",
}

var secretFileKeys = []string{"MONGO_PASSWORD_FILE", "REDIS_PASSWORD_FILE", "REDIS_DEDUPE_PASSWORD_FILE"}

func setEnv(t *testing.T, env map[string]string) {
	t.Helper()
	for _, k := range append(envKeys, secretFileKeys...) {
		t.Setenv(k, "")
	}
	t.Setenv("MONGO_URI", testMongoURI)
	for k, v := range env {
		t.Setenv(k, v)
	}
}
