syntax = "proto3";

package chatim.v1;

import "chatim/v1/core.proto";
import "google/protobuf/timestamp.proto";

message Event {
  reserved 7;
  reserved "pts";
  string id = 1;
  string tenant = 2;
  string room_id = 3;
  RoomType room_type = 4;
  uint64 thread_root = 5;
  uint64 seq = 6;
  string actor = 8;
  google.protobuf.Timestamp ts = 9;
  oneof payload {
    MessageCreated message_created = 20;
    RoomCreated room_created = 21;
  }
}

message MessageCreated {
  Message message = 1;
}

message RoomCreated {
  Room room = 1;
}
